# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planetmintgo/asset/asset.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eplanetmintgo/asset/asset.proto\x12\x12planetmintgo.asset\"\x14\n\x05\x41sset\x12\x0b\n\x03\x63id\x18\x01 \x01(\tB3Z1github.com/planetmint/planetmint-go/x/asset/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planetmintgo.asset.asset_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/planetmint/planetmint-go/x/asset/types'
  _ASSET._serialized_start=54
  _ASSET._serialized_end=74
# @@protoc_insertion_point(module_scope)
