# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planetmintgo/asset/tx.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bplanetmintgo/asset/tx.proto\x12\x12planetmintgo.asset\"0\n\x10MsgNotarizeAsset\x12\x0f\n\x07\x63reator\x18\x01 \x01(\t\x12\x0b\n\x03\x63id\x18\x02 \x01(\t\"\x1a\n\x18MsgNotarizeAssetResponse2j\n\x03Msg\x12\x63\n\rNotarizeAsset\x12$.planetmintgo.asset.MsgNotarizeAsset\x1a,.planetmintgo.asset.MsgNotarizeAssetResponseB3Z1github.com/planetmint/planetmint-go/x/asset/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planetmintgo.asset.tx_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z1github.com/planetmint/planetmint-go/x/asset/types'
  _MSGNOTARIZEASSET._serialized_start=51
  _MSGNOTARIZEASSET._serialized_end=99
  _MSGNOTARIZEASSETRESPONSE._serialized_start=101
  _MSGNOTARIZEASSETRESPONSE._serialized_end=127
  _MSG._serialized_start=129
  _MSG._serialized_end=235
# @@protoc_insertion_point(module_scope)
