/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PLANETMINTGO_DAO_PLANETMINTGO_DAO_DISTRIBUTION_ORDER_PB_H_INCLUDED
#define PB_PLANETMINTGO_DAO_PLANETMINTGO_DAO_DISTRIBUTION_ORDER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _planetmintgo_dao_DistributionOrder {
    pb_callback_t daoAddr;
    pb_callback_t daoAmount;
    pb_callback_t daoTxID;
    pb_callback_t investorAddr;
    pb_callback_t investorAmount;
    pb_callback_t investorTxID;
    pb_callback_t popAddr;
    pb_callback_t popAmount;
    pb_callback_t popTxID;
    int64_t firstPop;
    int64_t lastPop;
    pb_callback_t proposer;
} planetmintgo_dao_DistributionOrder;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define planetmintgo_dao_DistributionOrder_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}}
#define planetmintgo_dao_DistributionOrder_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define planetmintgo_dao_DistributionOrder_daoAddr_tag 1
#define planetmintgo_dao_DistributionOrder_daoAmount_tag 2
#define planetmintgo_dao_DistributionOrder_daoTxID_tag 3
#define planetmintgo_dao_DistributionOrder_investorAddr_tag 4
#define planetmintgo_dao_DistributionOrder_investorAmount_tag 5
#define planetmintgo_dao_DistributionOrder_investorTxID_tag 6
#define planetmintgo_dao_DistributionOrder_popAddr_tag 7
#define planetmintgo_dao_DistributionOrder_popAmount_tag 8
#define planetmintgo_dao_DistributionOrder_popTxID_tag 9
#define planetmintgo_dao_DistributionOrder_firstPop_tag 10
#define planetmintgo_dao_DistributionOrder_lastPop_tag 11
#define planetmintgo_dao_DistributionOrder_proposer_tag 12

/* Struct field encoding specification for nanopb */
#define planetmintgo_dao_DistributionOrder_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   daoAddr,           1) \
X(a, CALLBACK, SINGULAR, STRING,   daoAmount,         2) \
X(a, CALLBACK, SINGULAR, STRING,   daoTxID,           3) \
X(a, CALLBACK, SINGULAR, STRING,   investorAddr,      4) \
X(a, CALLBACK, SINGULAR, STRING,   investorAmount,    5) \
X(a, CALLBACK, SINGULAR, STRING,   investorTxID,      6) \
X(a, CALLBACK, SINGULAR, STRING,   popAddr,           7) \
X(a, CALLBACK, SINGULAR, STRING,   popAmount,         8) \
X(a, CALLBACK, SINGULAR, STRING,   popTxID,           9) \
X(a, STATIC,   SINGULAR, INT64,    firstPop,         10) \
X(a, STATIC,   SINGULAR, INT64,    lastPop,          11) \
X(a, CALLBACK, SINGULAR, STRING,   proposer,         12)
#define planetmintgo_dao_DistributionOrder_CALLBACK pb_default_field_callback
#define planetmintgo_dao_DistributionOrder_DEFAULT NULL

extern const pb_msgdesc_t planetmintgo_dao_DistributionOrder_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define planetmintgo_dao_DistributionOrder_fields &planetmintgo_dao_DistributionOrder_msg

/* Maximum encoded size of messages (where known) */
/* planetmintgo_dao_DistributionOrder_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
