/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "planetmintgo/dao/mint_request.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(planetmintgo_dao_MintRequest, planetmintgo_dao_MintRequest, AUTO)



