/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PLANETMINTGO_DAO_PLANETMINTGO_DAO_MINT_REQUEST_PB_H_INCLUDED
#define PB_PLANETMINTGO_DAO_PLANETMINTGO_DAO_MINT_REQUEST_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _planetmintgo_dao_MintRequest {
    pb_callback_t beneficiary;
    uint64_t amount;
    pb_callback_t liquidTxHash;
} planetmintgo_dao_MintRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define planetmintgo_dao_MintRequest_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}}
#define planetmintgo_dao_MintRequest_init_zero   {{{NULL}, NULL}, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define planetmintgo_dao_MintRequest_beneficiary_tag 1
#define planetmintgo_dao_MintRequest_amount_tag  2
#define planetmintgo_dao_MintRequest_liquidTxHash_tag 3

/* Struct field encoding specification for nanopb */
#define planetmintgo_dao_MintRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   beneficiary,       1) \
X(a, STATIC,   SINGULAR, UINT64,   amount,            2) \
X(a, CALLBACK, SINGULAR, STRING,   liquidTxHash,      3)
#define planetmintgo_dao_MintRequest_CALLBACK pb_default_field_callback
#define planetmintgo_dao_MintRequest_DEFAULT NULL

extern const pb_msgdesc_t planetmintgo_dao_MintRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define planetmintgo_dao_MintRequest_fields &planetmintgo_dao_MintRequest_msg

/* Maximum encoded size of messages (where known) */
/* planetmintgo_dao_MintRequest_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
