/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PLANETMINTGO_DAO_PLANETMINTGO_DAO_TX_PB_H_INCLUDED
#define PB_PLANETMINTGO_DAO_PLANETMINTGO_DAO_TX_PB_H_INCLUDED
#include <pb.h>
#include "planetmintgo/dao/challenge.pb.h"
#include "planetmintgo/dao/mint_request.pb.h"
#include "planetmintgo/dao/distribution_order.pb.h"
#include "planetmintgo/dao/params.pb.h"
#include "amino/amino.pb.h"
#include "gogoproto/gogo.pb.h"
#include "cosmos_proto/cosmos.pb.h"
#include "cosmos/msg/v1/msg.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _planetmintgo_dao_MsgReportPopResult {
    pb_callback_t creator;
    bool has_challenge;
    planetmintgo_dao_Challenge challenge;
} planetmintgo_dao_MsgReportPopResult;

typedef struct _planetmintgo_dao_MsgReportPopResultResponse {
    char dummy_field;
} planetmintgo_dao_MsgReportPopResultResponse;

typedef struct _planetmintgo_dao_MsgReissueRDDLProposal {
    pb_callback_t creator;
    pb_callback_t proposer;
    pb_callback_t tx;
    int64_t blockHeight;
    int64_t firstIncludedPop;
    int64_t lastIncludedPop;
} planetmintgo_dao_MsgReissueRDDLProposal;

typedef struct _planetmintgo_dao_MsgReissueRDDLProposalResponse {
    char dummy_field;
} planetmintgo_dao_MsgReissueRDDLProposalResponse;

typedef struct _planetmintgo_dao_MsgMintToken {
    pb_callback_t creator;
    bool has_mintRequest;
    planetmintgo_dao_MintRequest mintRequest;
} planetmintgo_dao_MsgMintToken;

typedef struct _planetmintgo_dao_MsgMintTokenResponse {
    char dummy_field;
} planetmintgo_dao_MsgMintTokenResponse;

typedef struct _planetmintgo_dao_MsgReissueRDDLResult {
    pb_callback_t creator;
    pb_callback_t proposer;
    pb_callback_t txID;
    int64_t blockHeight;
} planetmintgo_dao_MsgReissueRDDLResult;

typedef struct _planetmintgo_dao_MsgReissueRDDLResultResponse {
    char dummy_field;
} planetmintgo_dao_MsgReissueRDDLResultResponse;

typedef struct _planetmintgo_dao_MsgDistributionResult {
    pb_callback_t creator;
    int64_t lastPop;
    pb_callback_t daoTxID;
    pb_callback_t investorTxID;
    pb_callback_t popTxID;
} planetmintgo_dao_MsgDistributionResult;

typedef struct _planetmintgo_dao_MsgDistributionResultResponse {
    char dummy_field;
} planetmintgo_dao_MsgDistributionResultResponse;

typedef struct _planetmintgo_dao_MsgDistributionRequest {
    pb_callback_t creator;
    bool has_distribution;
    planetmintgo_dao_DistributionOrder distribution;
} planetmintgo_dao_MsgDistributionRequest;

typedef struct _planetmintgo_dao_MsgDistributionRequestResponse {
    char dummy_field;
} planetmintgo_dao_MsgDistributionRequestResponse;

typedef struct _planetmintgo_dao_MsgUpdateParams {
    /* authority is the address that controls the module (defaults to x/gov unless overwritten). */
    pb_callback_t authority;
    /* NOTE: All parameters must be supplied. */
    bool has_params;
    planetmintgo_dao_Params params;
} planetmintgo_dao_MsgUpdateParams;

typedef struct _planetmintgo_dao_MsgUpdateParamsResponse {
    char dummy_field;
} planetmintgo_dao_MsgUpdateParamsResponse;

typedef struct _planetmintgo_dao_MsgInitPop {
    pb_callback_t creator;
    pb_callback_t initiator;
    pb_callback_t challenger;
    pb_callback_t challengee;
    int64_t height;
} planetmintgo_dao_MsgInitPop;

typedef struct _planetmintgo_dao_MsgInitPopResponse {
    char dummy_field;
} planetmintgo_dao_MsgInitPopResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define planetmintgo_dao_MsgReportPopResult_init_default {{{NULL}, NULL}, false, planetmintgo_dao_Challenge_init_default}
#define planetmintgo_dao_MsgReportPopResultResponse_init_default {0}
#define planetmintgo_dao_MsgReissueRDDLProposal_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define planetmintgo_dao_MsgReissueRDDLProposalResponse_init_default {0}
#define planetmintgo_dao_MsgMintToken_init_default {{{NULL}, NULL}, false, planetmintgo_dao_MintRequest_init_default}
#define planetmintgo_dao_MsgMintTokenResponse_init_default {0}
#define planetmintgo_dao_MsgReissueRDDLResult_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define planetmintgo_dao_MsgReissueRDDLResultResponse_init_default {0}
#define planetmintgo_dao_MsgDistributionResult_init_default {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define planetmintgo_dao_MsgDistributionResultResponse_init_default {0}
#define planetmintgo_dao_MsgDistributionRequest_init_default {{{NULL}, NULL}, false, planetmintgo_dao_DistributionOrder_init_default}
#define planetmintgo_dao_MsgDistributionRequestResponse_init_default {0}
#define planetmintgo_dao_MsgUpdateParams_init_default {{{NULL}, NULL}, false, planetmintgo_dao_Params_init_default}
#define planetmintgo_dao_MsgUpdateParamsResponse_init_default {0}
#define planetmintgo_dao_MsgInitPop_init_default {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define planetmintgo_dao_MsgInitPopResponse_init_default {0}
#define planetmintgo_dao_MsgReportPopResult_init_zero {{{NULL}, NULL}, false, planetmintgo_dao_Challenge_init_zero}
#define planetmintgo_dao_MsgReportPopResultResponse_init_zero {0}
#define planetmintgo_dao_MsgReissueRDDLProposal_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, 0, 0}
#define planetmintgo_dao_MsgReissueRDDLProposalResponse_init_zero {0}
#define planetmintgo_dao_MsgMintToken_init_zero  {{{NULL}, NULL}, false, planetmintgo_dao_MintRequest_init_zero}
#define planetmintgo_dao_MsgMintTokenResponse_init_zero {0}
#define planetmintgo_dao_MsgReissueRDDLResult_init_zero {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define planetmintgo_dao_MsgReissueRDDLResultResponse_init_zero {0}
#define planetmintgo_dao_MsgDistributionResult_init_zero {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define planetmintgo_dao_MsgDistributionResultResponse_init_zero {0}
#define planetmintgo_dao_MsgDistributionRequest_init_zero {{{NULL}, NULL}, false, planetmintgo_dao_DistributionOrder_init_zero}
#define planetmintgo_dao_MsgDistributionRequestResponse_init_zero {0}
#define planetmintgo_dao_MsgUpdateParams_init_zero {{{NULL}, NULL}, false, planetmintgo_dao_Params_init_zero}
#define planetmintgo_dao_MsgUpdateParamsResponse_init_zero {0}
#define planetmintgo_dao_MsgInitPop_init_zero    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define planetmintgo_dao_MsgInitPopResponse_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define planetmintgo_dao_MsgReportPopResult_creator_tag 1
#define planetmintgo_dao_MsgReportPopResult_challenge_tag 2
#define planetmintgo_dao_MsgReissueRDDLProposal_creator_tag 1
#define planetmintgo_dao_MsgReissueRDDLProposal_proposer_tag 2
#define planetmintgo_dao_MsgReissueRDDLProposal_tx_tag 3
#define planetmintgo_dao_MsgReissueRDDLProposal_blockHeight_tag 4
#define planetmintgo_dao_MsgReissueRDDLProposal_firstIncludedPop_tag 5
#define planetmintgo_dao_MsgReissueRDDLProposal_lastIncludedPop_tag 6
#define planetmintgo_dao_MsgMintToken_creator_tag 1
#define planetmintgo_dao_MsgMintToken_mintRequest_tag 2
#define planetmintgo_dao_MsgReissueRDDLResult_creator_tag 1
#define planetmintgo_dao_MsgReissueRDDLResult_proposer_tag 2
#define planetmintgo_dao_MsgReissueRDDLResult_txID_tag 3
#define planetmintgo_dao_MsgReissueRDDLResult_blockHeight_tag 4
#define planetmintgo_dao_MsgDistributionResult_creator_tag 1
#define planetmintgo_dao_MsgDistributionResult_lastPop_tag 2
#define planetmintgo_dao_MsgDistributionResult_daoTxID_tag 3
#define planetmintgo_dao_MsgDistributionResult_investorTxID_tag 4
#define planetmintgo_dao_MsgDistributionResult_popTxID_tag 5
#define planetmintgo_dao_MsgDistributionRequest_creator_tag 1
#define planetmintgo_dao_MsgDistributionRequest_distribution_tag 2
#define planetmintgo_dao_MsgUpdateParams_authority_tag 1
#define planetmintgo_dao_MsgUpdateParams_params_tag 2
#define planetmintgo_dao_MsgInitPop_creator_tag  1
#define planetmintgo_dao_MsgInitPop_initiator_tag 2
#define planetmintgo_dao_MsgInitPop_challenger_tag 3
#define planetmintgo_dao_MsgInitPop_challengee_tag 4
#define planetmintgo_dao_MsgInitPop_height_tag   5

/* Struct field encoding specification for nanopb */
#define planetmintgo_dao_MsgReportPopResult_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   creator,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  challenge,         2)
#define planetmintgo_dao_MsgReportPopResult_CALLBACK pb_default_field_callback
#define planetmintgo_dao_MsgReportPopResult_DEFAULT NULL
#define planetmintgo_dao_MsgReportPopResult_challenge_MSGTYPE planetmintgo_dao_Challenge

#define planetmintgo_dao_MsgReportPopResultResponse_FIELDLIST(X, a) \

#define planetmintgo_dao_MsgReportPopResultResponse_CALLBACK NULL
#define planetmintgo_dao_MsgReportPopResultResponse_DEFAULT NULL

#define planetmintgo_dao_MsgReissueRDDLProposal_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   creator,           1) \
X(a, CALLBACK, SINGULAR, STRING,   proposer,          2) \
X(a, CALLBACK, SINGULAR, STRING,   tx,                3) \
X(a, STATIC,   SINGULAR, INT64,    blockHeight,       4) \
X(a, STATIC,   SINGULAR, INT64,    firstIncludedPop,   5) \
X(a, STATIC,   SINGULAR, INT64,    lastIncludedPop,   6)
#define planetmintgo_dao_MsgReissueRDDLProposal_CALLBACK pb_default_field_callback
#define planetmintgo_dao_MsgReissueRDDLProposal_DEFAULT NULL

#define planetmintgo_dao_MsgReissueRDDLProposalResponse_FIELDLIST(X, a) \

#define planetmintgo_dao_MsgReissueRDDLProposalResponse_CALLBACK NULL
#define planetmintgo_dao_MsgReissueRDDLProposalResponse_DEFAULT NULL

#define planetmintgo_dao_MsgMintToken_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   creator,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mintRequest,       2)
#define planetmintgo_dao_MsgMintToken_CALLBACK pb_default_field_callback
#define planetmintgo_dao_MsgMintToken_DEFAULT NULL
#define planetmintgo_dao_MsgMintToken_mintRequest_MSGTYPE planetmintgo_dao_MintRequest

#define planetmintgo_dao_MsgMintTokenResponse_FIELDLIST(X, a) \

#define planetmintgo_dao_MsgMintTokenResponse_CALLBACK NULL
#define planetmintgo_dao_MsgMintTokenResponse_DEFAULT NULL

#define planetmintgo_dao_MsgReissueRDDLResult_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   creator,           1) \
X(a, CALLBACK, SINGULAR, STRING,   proposer,          2) \
X(a, CALLBACK, SINGULAR, STRING,   txID,              3) \
X(a, STATIC,   SINGULAR, INT64,    blockHeight,       4)
#define planetmintgo_dao_MsgReissueRDDLResult_CALLBACK pb_default_field_callback
#define planetmintgo_dao_MsgReissueRDDLResult_DEFAULT NULL

#define planetmintgo_dao_MsgReissueRDDLResultResponse_FIELDLIST(X, a) \

#define planetmintgo_dao_MsgReissueRDDLResultResponse_CALLBACK NULL
#define planetmintgo_dao_MsgReissueRDDLResultResponse_DEFAULT NULL

#define planetmintgo_dao_MsgDistributionResult_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   creator,           1) \
X(a, STATIC,   SINGULAR, INT64,    lastPop,           2) \
X(a, CALLBACK, SINGULAR, STRING,   daoTxID,           3) \
X(a, CALLBACK, SINGULAR, STRING,   investorTxID,      4) \
X(a, CALLBACK, SINGULAR, STRING,   popTxID,           5)
#define planetmintgo_dao_MsgDistributionResult_CALLBACK pb_default_field_callback
#define planetmintgo_dao_MsgDistributionResult_DEFAULT NULL

#define planetmintgo_dao_MsgDistributionResultResponse_FIELDLIST(X, a) \

#define planetmintgo_dao_MsgDistributionResultResponse_CALLBACK NULL
#define planetmintgo_dao_MsgDistributionResultResponse_DEFAULT NULL

#define planetmintgo_dao_MsgDistributionRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   creator,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  distribution,      2)
#define planetmintgo_dao_MsgDistributionRequest_CALLBACK pb_default_field_callback
#define planetmintgo_dao_MsgDistributionRequest_DEFAULT NULL
#define planetmintgo_dao_MsgDistributionRequest_distribution_MSGTYPE planetmintgo_dao_DistributionOrder

#define planetmintgo_dao_MsgDistributionRequestResponse_FIELDLIST(X, a) \

#define planetmintgo_dao_MsgDistributionRequestResponse_CALLBACK NULL
#define planetmintgo_dao_MsgDistributionRequestResponse_DEFAULT NULL

#define planetmintgo_dao_MsgUpdateParams_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   authority,         1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  params,            2)
#define planetmintgo_dao_MsgUpdateParams_CALLBACK pb_default_field_callback
#define planetmintgo_dao_MsgUpdateParams_DEFAULT NULL
#define planetmintgo_dao_MsgUpdateParams_params_MSGTYPE planetmintgo_dao_Params

#define planetmintgo_dao_MsgUpdateParamsResponse_FIELDLIST(X, a) \

#define planetmintgo_dao_MsgUpdateParamsResponse_CALLBACK NULL
#define planetmintgo_dao_MsgUpdateParamsResponse_DEFAULT NULL

#define planetmintgo_dao_MsgInitPop_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   creator,           1) \
X(a, CALLBACK, SINGULAR, STRING,   initiator,         2) \
X(a, CALLBACK, SINGULAR, STRING,   challenger,        3) \
X(a, CALLBACK, SINGULAR, STRING,   challengee,        4) \
X(a, STATIC,   SINGULAR, INT64,    height,            5)
#define planetmintgo_dao_MsgInitPop_CALLBACK pb_default_field_callback
#define planetmintgo_dao_MsgInitPop_DEFAULT NULL

#define planetmintgo_dao_MsgInitPopResponse_FIELDLIST(X, a) \

#define planetmintgo_dao_MsgInitPopResponse_CALLBACK NULL
#define planetmintgo_dao_MsgInitPopResponse_DEFAULT NULL

extern const pb_msgdesc_t planetmintgo_dao_MsgReportPopResult_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgReportPopResultResponse_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgReissueRDDLProposal_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgReissueRDDLProposalResponse_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgMintToken_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgMintTokenResponse_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgReissueRDDLResult_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgReissueRDDLResultResponse_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgDistributionResult_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgDistributionResultResponse_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgDistributionRequest_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgDistributionRequestResponse_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgUpdateParams_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgUpdateParamsResponse_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgInitPop_msg;
extern const pb_msgdesc_t planetmintgo_dao_MsgInitPopResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define planetmintgo_dao_MsgReportPopResult_fields &planetmintgo_dao_MsgReportPopResult_msg
#define planetmintgo_dao_MsgReportPopResultResponse_fields &planetmintgo_dao_MsgReportPopResultResponse_msg
#define planetmintgo_dao_MsgReissueRDDLProposal_fields &planetmintgo_dao_MsgReissueRDDLProposal_msg
#define planetmintgo_dao_MsgReissueRDDLProposalResponse_fields &planetmintgo_dao_MsgReissueRDDLProposalResponse_msg
#define planetmintgo_dao_MsgMintToken_fields &planetmintgo_dao_MsgMintToken_msg
#define planetmintgo_dao_MsgMintTokenResponse_fields &planetmintgo_dao_MsgMintTokenResponse_msg
#define planetmintgo_dao_MsgReissueRDDLResult_fields &planetmintgo_dao_MsgReissueRDDLResult_msg
#define planetmintgo_dao_MsgReissueRDDLResultResponse_fields &planetmintgo_dao_MsgReissueRDDLResultResponse_msg
#define planetmintgo_dao_MsgDistributionResult_fields &planetmintgo_dao_MsgDistributionResult_msg
#define planetmintgo_dao_MsgDistributionResultResponse_fields &planetmintgo_dao_MsgDistributionResultResponse_msg
#define planetmintgo_dao_MsgDistributionRequest_fields &planetmintgo_dao_MsgDistributionRequest_msg
#define planetmintgo_dao_MsgDistributionRequestResponse_fields &planetmintgo_dao_MsgDistributionRequestResponse_msg
#define planetmintgo_dao_MsgUpdateParams_fields &planetmintgo_dao_MsgUpdateParams_msg
#define planetmintgo_dao_MsgUpdateParamsResponse_fields &planetmintgo_dao_MsgUpdateParamsResponse_msg
#define planetmintgo_dao_MsgInitPop_fields &planetmintgo_dao_MsgInitPop_msg
#define planetmintgo_dao_MsgInitPopResponse_fields &planetmintgo_dao_MsgInitPopResponse_msg

/* Maximum encoded size of messages (where known) */
/* planetmintgo_dao_MsgReportPopResult_size depends on runtime parameters */
/* planetmintgo_dao_MsgReissueRDDLProposal_size depends on runtime parameters */
/* planetmintgo_dao_MsgMintToken_size depends on runtime parameters */
/* planetmintgo_dao_MsgReissueRDDLResult_size depends on runtime parameters */
/* planetmintgo_dao_MsgDistributionResult_size depends on runtime parameters */
/* planetmintgo_dao_MsgDistributionRequest_size depends on runtime parameters */
/* planetmintgo_dao_MsgUpdateParams_size depends on runtime parameters */
/* planetmintgo_dao_MsgInitPop_size depends on runtime parameters */
#define planetmintgo_dao_MsgDistributionRequestResponse_size 0
#define planetmintgo_dao_MsgDistributionResultResponse_size 0
#define planetmintgo_dao_MsgInitPopResponse_size 0
#define planetmintgo_dao_MsgMintTokenResponse_size 0
#define planetmintgo_dao_MsgReissueRDDLProposalResponse_size 0
#define planetmintgo_dao_MsgReissueRDDLResultResponse_size 0
#define planetmintgo_dao_MsgReportPopResultResponse_size 0
#define planetmintgo_dao_MsgUpdateParamsResponse_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
