/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_GOGOPROTO_GOGOPROTO_GOGO_PB_H_INCLUDED
#define PB_GOGOPROTO_GOGOPROTO_GOGO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Extensions */
extern const pb_extension_type_t gogoproto_goproto_enum_prefix; /* field type: bool goproto_enum_prefix; */
extern const pb_extension_type_t gogoproto_goproto_enum_stringer; /* field type: bool goproto_enum_stringer; */
extern const pb_extension_type_t gogoproto_enum_stringer; /* field type: bool enum_stringer; */
extern const pb_extension_type_t gogoproto_enum_customname; /* field type: pb_callback_t enum_customname; */
extern const pb_extension_type_t gogoproto_enumdecl; /* field type: bool enumdecl; */
extern const pb_extension_type_t gogoproto_enumvalue_customname; /* field type: pb_callback_t enumvalue_customname; */
extern const pb_extension_type_t gogoproto_goproto_getters_all; /* field type: bool goproto_getters_all; */
extern const pb_extension_type_t gogoproto_goproto_enum_prefix_all; /* field type: bool goproto_enum_prefix_all; */
extern const pb_extension_type_t gogoproto_goproto_stringer_all; /* field type: bool goproto_stringer_all; */
extern const pb_extension_type_t gogoproto_verbose_equal_all; /* field type: bool verbose_equal_all; */
extern const pb_extension_type_t gogoproto_face_all; /* field type: bool face_all; */
extern const pb_extension_type_t gogoproto_gostring_all; /* field type: bool gostring_all; */
extern const pb_extension_type_t gogoproto_populate_all; /* field type: bool populate_all; */
extern const pb_extension_type_t gogoproto_stringer_all; /* field type: bool stringer_all; */
extern const pb_extension_type_t gogoproto_onlyone_all; /* field type: bool onlyone_all; */
extern const pb_extension_type_t gogoproto_equal_all; /* field type: bool equal_all; */
extern const pb_extension_type_t gogoproto_description_all; /* field type: bool description_all; */
extern const pb_extension_type_t gogoproto_testgen_all; /* field type: bool testgen_all; */
extern const pb_extension_type_t gogoproto_benchgen_all; /* field type: bool benchgen_all; */
extern const pb_extension_type_t gogoproto_marshaler_all; /* field type: bool marshaler_all; */
extern const pb_extension_type_t gogoproto_unmarshaler_all; /* field type: bool unmarshaler_all; */
extern const pb_extension_type_t gogoproto_stable_marshaler_all; /* field type: bool stable_marshaler_all; */
extern const pb_extension_type_t gogoproto_sizer_all; /* field type: bool sizer_all; */
extern const pb_extension_type_t gogoproto_goproto_enum_stringer_all; /* field type: bool goproto_enum_stringer_all; */
extern const pb_extension_type_t gogoproto_enum_stringer_all; /* field type: bool enum_stringer_all; */
extern const pb_extension_type_t gogoproto_unsafe_marshaler_all; /* field type: bool unsafe_marshaler_all; */
extern const pb_extension_type_t gogoproto_unsafe_unmarshaler_all; /* field type: bool unsafe_unmarshaler_all; */
extern const pb_extension_type_t gogoproto_goproto_extensions_map_all; /* field type: bool goproto_extensions_map_all; */
extern const pb_extension_type_t gogoproto_goproto_unrecognized_all; /* field type: bool goproto_unrecognized_all; */
extern const pb_extension_type_t gogoproto_gogoproto_import; /* field type: bool gogoproto_import; */
extern const pb_extension_type_t gogoproto_protosizer_all; /* field type: bool protosizer_all; */
extern const pb_extension_type_t gogoproto_compare_all; /* field type: bool compare_all; */
extern const pb_extension_type_t gogoproto_typedecl_all; /* field type: bool typedecl_all; */
extern const pb_extension_type_t gogoproto_enumdecl_all; /* field type: bool enumdecl_all; */
extern const pb_extension_type_t gogoproto_goproto_registration; /* field type: bool goproto_registration; */
extern const pb_extension_type_t gogoproto_messagename_all; /* field type: bool messagename_all; */
extern const pb_extension_type_t gogoproto_goproto_sizecache_all; /* field type: bool goproto_sizecache_all; */
extern const pb_extension_type_t gogoproto_goproto_unkeyed_all; /* field type: bool goproto_unkeyed_all; */
extern const pb_extension_type_t gogoproto_goproto_getters; /* field type: bool goproto_getters; */
extern const pb_extension_type_t gogoproto_goproto_stringer; /* field type: bool goproto_stringer; */
extern const pb_extension_type_t gogoproto_verbose_equal; /* field type: bool verbose_equal; */
extern const pb_extension_type_t gogoproto_face; /* field type: bool face; */
extern const pb_extension_type_t gogoproto_gostring; /* field type: bool gostring; */
extern const pb_extension_type_t gogoproto_populate; /* field type: bool populate; */
extern const pb_extension_type_t gogoproto_stringer; /* field type: bool stringer; */
extern const pb_extension_type_t gogoproto_onlyone; /* field type: bool onlyone; */
extern const pb_extension_type_t gogoproto_equal; /* field type: bool equal; */
extern const pb_extension_type_t gogoproto_description; /* field type: bool description; */
extern const pb_extension_type_t gogoproto_testgen; /* field type: bool testgen; */
extern const pb_extension_type_t gogoproto_benchgen; /* field type: bool benchgen; */
extern const pb_extension_type_t gogoproto_marshaler; /* field type: bool marshaler; */
extern const pb_extension_type_t gogoproto_unmarshaler; /* field type: bool unmarshaler; */
extern const pb_extension_type_t gogoproto_stable_marshaler; /* field type: bool stable_marshaler; */
extern const pb_extension_type_t gogoproto_sizer; /* field type: bool sizer; */
extern const pb_extension_type_t gogoproto_unsafe_marshaler; /* field type: bool unsafe_marshaler; */
extern const pb_extension_type_t gogoproto_unsafe_unmarshaler; /* field type: bool unsafe_unmarshaler; */
extern const pb_extension_type_t gogoproto_goproto_extensions_map; /* field type: bool goproto_extensions_map; */
extern const pb_extension_type_t gogoproto_goproto_unrecognized; /* field type: bool goproto_unrecognized; */
extern const pb_extension_type_t gogoproto_protosizer; /* field type: bool protosizer; */
extern const pb_extension_type_t gogoproto_compare; /* field type: bool compare; */
extern const pb_extension_type_t gogoproto_typedecl; /* field type: bool typedecl; */
extern const pb_extension_type_t gogoproto_messagename; /* field type: bool messagename; */
extern const pb_extension_type_t gogoproto_goproto_sizecache; /* field type: bool goproto_sizecache; */
extern const pb_extension_type_t gogoproto_goproto_unkeyed; /* field type: bool goproto_unkeyed; */
extern const pb_extension_type_t gogoproto_nullable; /* field type: bool nullable; */
extern const pb_extension_type_t gogoproto_embed; /* field type: bool embed; */
extern const pb_extension_type_t gogoproto_customtype; /* field type: pb_callback_t customtype; */
extern const pb_extension_type_t gogoproto_customname; /* field type: pb_callback_t customname; */
extern const pb_extension_type_t gogoproto_jsontag; /* field type: pb_callback_t jsontag; */
extern const pb_extension_type_t gogoproto_moretags; /* field type: pb_callback_t moretags; */
extern const pb_extension_type_t gogoproto_casttype; /* field type: pb_callback_t casttype; */
extern const pb_extension_type_t gogoproto_castkey; /* field type: pb_callback_t castkey; */
extern const pb_extension_type_t gogoproto_castvalue; /* field type: pb_callback_t castvalue; */
extern const pb_extension_type_t gogoproto_stdtime; /* field type: bool stdtime; */
extern const pb_extension_type_t gogoproto_stdduration; /* field type: bool stdduration; */
extern const pb_extension_type_t gogoproto_wktpointer; /* field type: bool wktpointer; */
extern const pb_extension_type_t gogoproto_castrepeated; /* field type: pb_callback_t castrepeated; */

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
