/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "gogoproto/gogo.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Definition for extension field gogoproto_goproto_enum_prefix */
typedef struct _gogoproto_goproto_enum_prefix_extmsg {
    bool goproto_enum_prefix;
} gogoproto_goproto_enum_prefix_extmsg;
#define gogoproto_goproto_enum_prefix_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_enum_prefix, 62001)
#define gogoproto_goproto_enum_prefix_extmsg_CALLBACK NULL
#define gogoproto_goproto_enum_prefix_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_enum_prefix_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_enum_prefix_extmsg, gogoproto_goproto_enum_prefix_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_enum_prefix = {
    NULL,
    NULL,
    &gogoproto_goproto_enum_prefix_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_enum_stringer */
typedef struct _gogoproto_goproto_enum_stringer_extmsg {
    bool goproto_enum_stringer;
} gogoproto_goproto_enum_stringer_extmsg;
#define gogoproto_goproto_enum_stringer_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_enum_stringer, 62021)
#define gogoproto_goproto_enum_stringer_extmsg_CALLBACK NULL
#define gogoproto_goproto_enum_stringer_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_enum_stringer_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_enum_stringer_extmsg, gogoproto_goproto_enum_stringer_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_enum_stringer = {
    NULL,
    NULL,
    &gogoproto_goproto_enum_stringer_extmsg_msg
};

/* Definition for extension field gogoproto_enum_stringer */
typedef struct _gogoproto_enum_stringer_extmsg {
    bool enum_stringer;
} gogoproto_enum_stringer_extmsg;
#define gogoproto_enum_stringer_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     enum_stringer,   62022)
#define gogoproto_enum_stringer_extmsg_CALLBACK NULL
#define gogoproto_enum_stringer_extmsg_DEFAULT NULL
pb_byte_t gogoproto_enum_stringer_extmsg_default[] = {0x00};
PB_BIND(gogoproto_enum_stringer_extmsg, gogoproto_enum_stringer_extmsg, 4)
const pb_extension_type_t gogoproto_enum_stringer = {
    NULL,
    NULL,
    &gogoproto_enum_stringer_extmsg_msg
};

/* Definition for extension field gogoproto_enum_customname */
typedef struct _gogoproto_enum_customname_extmsg {
    pb_callback_t enum_customname;
} gogoproto_enum_customname_extmsg;
#define gogoproto_enum_customname_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   enum_customname, 62023)
#define gogoproto_enum_customname_extmsg_CALLBACK pb_default_field_callback
#define gogoproto_enum_customname_extmsg_DEFAULT NULL
pb_byte_t gogoproto_enum_customname_extmsg_default[] = {0x00};
PB_BIND(gogoproto_enum_customname_extmsg, gogoproto_enum_customname_extmsg, 4)
const pb_extension_type_t gogoproto_enum_customname = {
    NULL,
    NULL,
    &gogoproto_enum_customname_extmsg_msg
};

/* Definition for extension field gogoproto_enumdecl */
typedef struct _gogoproto_enumdecl_extmsg {
    bool enumdecl;
} gogoproto_enumdecl_extmsg;
#define gogoproto_enumdecl_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     enumdecl,        62024)
#define gogoproto_enumdecl_extmsg_CALLBACK NULL
#define gogoproto_enumdecl_extmsg_DEFAULT NULL
pb_byte_t gogoproto_enumdecl_extmsg_default[] = {0x00};
PB_BIND(gogoproto_enumdecl_extmsg, gogoproto_enumdecl_extmsg, 4)
const pb_extension_type_t gogoproto_enumdecl = {
    NULL,
    NULL,
    &gogoproto_enumdecl_extmsg_msg
};

/* Definition for extension field gogoproto_enumvalue_customname */
typedef struct _gogoproto_enumvalue_customname_extmsg {
    pb_callback_t enumvalue_customname;
} gogoproto_enumvalue_customname_extmsg;
#define gogoproto_enumvalue_customname_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   enumvalue_customname, 66001)
#define gogoproto_enumvalue_customname_extmsg_CALLBACK pb_default_field_callback
#define gogoproto_enumvalue_customname_extmsg_DEFAULT NULL
pb_byte_t gogoproto_enumvalue_customname_extmsg_default[] = {0x00};
PB_BIND(gogoproto_enumvalue_customname_extmsg, gogoproto_enumvalue_customname_extmsg, 4)
const pb_extension_type_t gogoproto_enumvalue_customname = {
    NULL,
    NULL,
    &gogoproto_enumvalue_customname_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_getters_all */
typedef struct _gogoproto_goproto_getters_all_extmsg {
    bool goproto_getters_all;
} gogoproto_goproto_getters_all_extmsg;
#define gogoproto_goproto_getters_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_getters_all, 63001)
#define gogoproto_goproto_getters_all_extmsg_CALLBACK NULL
#define gogoproto_goproto_getters_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_getters_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_getters_all_extmsg, gogoproto_goproto_getters_all_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_getters_all = {
    NULL,
    NULL,
    &gogoproto_goproto_getters_all_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_enum_prefix_all */
typedef struct _gogoproto_goproto_enum_prefix_all_extmsg {
    bool goproto_enum_prefix_all;
} gogoproto_goproto_enum_prefix_all_extmsg;
#define gogoproto_goproto_enum_prefix_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_enum_prefix_all, 63002)
#define gogoproto_goproto_enum_prefix_all_extmsg_CALLBACK NULL
#define gogoproto_goproto_enum_prefix_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_enum_prefix_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_enum_prefix_all_extmsg, gogoproto_goproto_enum_prefix_all_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_enum_prefix_all = {
    NULL,
    NULL,
    &gogoproto_goproto_enum_prefix_all_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_stringer_all */
typedef struct _gogoproto_goproto_stringer_all_extmsg {
    bool goproto_stringer_all;
} gogoproto_goproto_stringer_all_extmsg;
#define gogoproto_goproto_stringer_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_stringer_all, 63003)
#define gogoproto_goproto_stringer_all_extmsg_CALLBACK NULL
#define gogoproto_goproto_stringer_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_stringer_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_stringer_all_extmsg, gogoproto_goproto_stringer_all_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_stringer_all = {
    NULL,
    NULL,
    &gogoproto_goproto_stringer_all_extmsg_msg
};

/* Definition for extension field gogoproto_verbose_equal_all */
typedef struct _gogoproto_verbose_equal_all_extmsg {
    bool verbose_equal_all;
} gogoproto_verbose_equal_all_extmsg;
#define gogoproto_verbose_equal_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     verbose_equal_all, 63004)
#define gogoproto_verbose_equal_all_extmsg_CALLBACK NULL
#define gogoproto_verbose_equal_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_verbose_equal_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_verbose_equal_all_extmsg, gogoproto_verbose_equal_all_extmsg, 4)
const pb_extension_type_t gogoproto_verbose_equal_all = {
    NULL,
    NULL,
    &gogoproto_verbose_equal_all_extmsg_msg
};

/* Definition for extension field gogoproto_face_all */
typedef struct _gogoproto_face_all_extmsg {
    bool face_all;
} gogoproto_face_all_extmsg;
#define gogoproto_face_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     face_all,        63005)
#define gogoproto_face_all_extmsg_CALLBACK NULL
#define gogoproto_face_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_face_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_face_all_extmsg, gogoproto_face_all_extmsg, 4)
const pb_extension_type_t gogoproto_face_all = {
    NULL,
    NULL,
    &gogoproto_face_all_extmsg_msg
};

/* Definition for extension field gogoproto_gostring_all */
typedef struct _gogoproto_gostring_all_extmsg {
    bool gostring_all;
} gogoproto_gostring_all_extmsg;
#define gogoproto_gostring_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     gostring_all,    63006)
#define gogoproto_gostring_all_extmsg_CALLBACK NULL
#define gogoproto_gostring_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_gostring_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_gostring_all_extmsg, gogoproto_gostring_all_extmsg, 4)
const pb_extension_type_t gogoproto_gostring_all = {
    NULL,
    NULL,
    &gogoproto_gostring_all_extmsg_msg
};

/* Definition for extension field gogoproto_populate_all */
typedef struct _gogoproto_populate_all_extmsg {
    bool populate_all;
} gogoproto_populate_all_extmsg;
#define gogoproto_populate_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     populate_all,    63007)
#define gogoproto_populate_all_extmsg_CALLBACK NULL
#define gogoproto_populate_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_populate_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_populate_all_extmsg, gogoproto_populate_all_extmsg, 4)
const pb_extension_type_t gogoproto_populate_all = {
    NULL,
    NULL,
    &gogoproto_populate_all_extmsg_msg
};

/* Definition for extension field gogoproto_stringer_all */
typedef struct _gogoproto_stringer_all_extmsg {
    bool stringer_all;
} gogoproto_stringer_all_extmsg;
#define gogoproto_stringer_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     stringer_all,    63008)
#define gogoproto_stringer_all_extmsg_CALLBACK NULL
#define gogoproto_stringer_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_stringer_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_stringer_all_extmsg, gogoproto_stringer_all_extmsg, 4)
const pb_extension_type_t gogoproto_stringer_all = {
    NULL,
    NULL,
    &gogoproto_stringer_all_extmsg_msg
};

/* Definition for extension field gogoproto_onlyone_all */
typedef struct _gogoproto_onlyone_all_extmsg {
    bool onlyone_all;
} gogoproto_onlyone_all_extmsg;
#define gogoproto_onlyone_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     onlyone_all,     63009)
#define gogoproto_onlyone_all_extmsg_CALLBACK NULL
#define gogoproto_onlyone_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_onlyone_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_onlyone_all_extmsg, gogoproto_onlyone_all_extmsg, 4)
const pb_extension_type_t gogoproto_onlyone_all = {
    NULL,
    NULL,
    &gogoproto_onlyone_all_extmsg_msg
};

/* Definition for extension field gogoproto_equal_all */
typedef struct _gogoproto_equal_all_extmsg {
    bool equal_all;
} gogoproto_equal_all_extmsg;
#define gogoproto_equal_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     equal_all,       63013)
#define gogoproto_equal_all_extmsg_CALLBACK NULL
#define gogoproto_equal_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_equal_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_equal_all_extmsg, gogoproto_equal_all_extmsg, 4)
const pb_extension_type_t gogoproto_equal_all = {
    NULL,
    NULL,
    &gogoproto_equal_all_extmsg_msg
};

/* Definition for extension field gogoproto_description_all */
typedef struct _gogoproto_description_all_extmsg {
    bool description_all;
} gogoproto_description_all_extmsg;
#define gogoproto_description_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     description_all, 63014)
#define gogoproto_description_all_extmsg_CALLBACK NULL
#define gogoproto_description_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_description_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_description_all_extmsg, gogoproto_description_all_extmsg, 4)
const pb_extension_type_t gogoproto_description_all = {
    NULL,
    NULL,
    &gogoproto_description_all_extmsg_msg
};

/* Definition for extension field gogoproto_testgen_all */
typedef struct _gogoproto_testgen_all_extmsg {
    bool testgen_all;
} gogoproto_testgen_all_extmsg;
#define gogoproto_testgen_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     testgen_all,     63015)
#define gogoproto_testgen_all_extmsg_CALLBACK NULL
#define gogoproto_testgen_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_testgen_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_testgen_all_extmsg, gogoproto_testgen_all_extmsg, 4)
const pb_extension_type_t gogoproto_testgen_all = {
    NULL,
    NULL,
    &gogoproto_testgen_all_extmsg_msg
};

/* Definition for extension field gogoproto_benchgen_all */
typedef struct _gogoproto_benchgen_all_extmsg {
    bool benchgen_all;
} gogoproto_benchgen_all_extmsg;
#define gogoproto_benchgen_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     benchgen_all,    63016)
#define gogoproto_benchgen_all_extmsg_CALLBACK NULL
#define gogoproto_benchgen_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_benchgen_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_benchgen_all_extmsg, gogoproto_benchgen_all_extmsg, 4)
const pb_extension_type_t gogoproto_benchgen_all = {
    NULL,
    NULL,
    &gogoproto_benchgen_all_extmsg_msg
};

/* Definition for extension field gogoproto_marshaler_all */
typedef struct _gogoproto_marshaler_all_extmsg {
    bool marshaler_all;
} gogoproto_marshaler_all_extmsg;
#define gogoproto_marshaler_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     marshaler_all,   63017)
#define gogoproto_marshaler_all_extmsg_CALLBACK NULL
#define gogoproto_marshaler_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_marshaler_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_marshaler_all_extmsg, gogoproto_marshaler_all_extmsg, 4)
const pb_extension_type_t gogoproto_marshaler_all = {
    NULL,
    NULL,
    &gogoproto_marshaler_all_extmsg_msg
};

/* Definition for extension field gogoproto_unmarshaler_all */
typedef struct _gogoproto_unmarshaler_all_extmsg {
    bool unmarshaler_all;
} gogoproto_unmarshaler_all_extmsg;
#define gogoproto_unmarshaler_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     unmarshaler_all, 63018)
#define gogoproto_unmarshaler_all_extmsg_CALLBACK NULL
#define gogoproto_unmarshaler_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_unmarshaler_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_unmarshaler_all_extmsg, gogoproto_unmarshaler_all_extmsg, 4)
const pb_extension_type_t gogoproto_unmarshaler_all = {
    NULL,
    NULL,
    &gogoproto_unmarshaler_all_extmsg_msg
};

/* Definition for extension field gogoproto_stable_marshaler_all */
typedef struct _gogoproto_stable_marshaler_all_extmsg {
    bool stable_marshaler_all;
} gogoproto_stable_marshaler_all_extmsg;
#define gogoproto_stable_marshaler_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     stable_marshaler_all, 63019)
#define gogoproto_stable_marshaler_all_extmsg_CALLBACK NULL
#define gogoproto_stable_marshaler_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_stable_marshaler_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_stable_marshaler_all_extmsg, gogoproto_stable_marshaler_all_extmsg, 4)
const pb_extension_type_t gogoproto_stable_marshaler_all = {
    NULL,
    NULL,
    &gogoproto_stable_marshaler_all_extmsg_msg
};

/* Definition for extension field gogoproto_sizer_all */
typedef struct _gogoproto_sizer_all_extmsg {
    bool sizer_all;
} gogoproto_sizer_all_extmsg;
#define gogoproto_sizer_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     sizer_all,       63020)
#define gogoproto_sizer_all_extmsg_CALLBACK NULL
#define gogoproto_sizer_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_sizer_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_sizer_all_extmsg, gogoproto_sizer_all_extmsg, 4)
const pb_extension_type_t gogoproto_sizer_all = {
    NULL,
    NULL,
    &gogoproto_sizer_all_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_enum_stringer_all */
typedef struct _gogoproto_goproto_enum_stringer_all_extmsg {
    bool goproto_enum_stringer_all;
} gogoproto_goproto_enum_stringer_all_extmsg;
#define gogoproto_goproto_enum_stringer_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_enum_stringer_all, 63021)
#define gogoproto_goproto_enum_stringer_all_extmsg_CALLBACK NULL
#define gogoproto_goproto_enum_stringer_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_enum_stringer_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_enum_stringer_all_extmsg, gogoproto_goproto_enum_stringer_all_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_enum_stringer_all = {
    NULL,
    NULL,
    &gogoproto_goproto_enum_stringer_all_extmsg_msg
};

/* Definition for extension field gogoproto_enum_stringer_all */
typedef struct _gogoproto_enum_stringer_all_extmsg {
    bool enum_stringer_all;
} gogoproto_enum_stringer_all_extmsg;
#define gogoproto_enum_stringer_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     enum_stringer_all, 63022)
#define gogoproto_enum_stringer_all_extmsg_CALLBACK NULL
#define gogoproto_enum_stringer_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_enum_stringer_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_enum_stringer_all_extmsg, gogoproto_enum_stringer_all_extmsg, 4)
const pb_extension_type_t gogoproto_enum_stringer_all = {
    NULL,
    NULL,
    &gogoproto_enum_stringer_all_extmsg_msg
};

/* Definition for extension field gogoproto_unsafe_marshaler_all */
typedef struct _gogoproto_unsafe_marshaler_all_extmsg {
    bool unsafe_marshaler_all;
} gogoproto_unsafe_marshaler_all_extmsg;
#define gogoproto_unsafe_marshaler_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     unsafe_marshaler_all, 63023)
#define gogoproto_unsafe_marshaler_all_extmsg_CALLBACK NULL
#define gogoproto_unsafe_marshaler_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_unsafe_marshaler_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_unsafe_marshaler_all_extmsg, gogoproto_unsafe_marshaler_all_extmsg, 4)
const pb_extension_type_t gogoproto_unsafe_marshaler_all = {
    NULL,
    NULL,
    &gogoproto_unsafe_marshaler_all_extmsg_msg
};

/* Definition for extension field gogoproto_unsafe_unmarshaler_all */
typedef struct _gogoproto_unsafe_unmarshaler_all_extmsg {
    bool unsafe_unmarshaler_all;
} gogoproto_unsafe_unmarshaler_all_extmsg;
#define gogoproto_unsafe_unmarshaler_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     unsafe_unmarshaler_all, 63024)
#define gogoproto_unsafe_unmarshaler_all_extmsg_CALLBACK NULL
#define gogoproto_unsafe_unmarshaler_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_unsafe_unmarshaler_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_unsafe_unmarshaler_all_extmsg, gogoproto_unsafe_unmarshaler_all_extmsg, 4)
const pb_extension_type_t gogoproto_unsafe_unmarshaler_all = {
    NULL,
    NULL,
    &gogoproto_unsafe_unmarshaler_all_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_extensions_map_all */
typedef struct _gogoproto_goproto_extensions_map_all_extmsg {
    bool goproto_extensions_map_all;
} gogoproto_goproto_extensions_map_all_extmsg;
#define gogoproto_goproto_extensions_map_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_extensions_map_all, 63025)
#define gogoproto_goproto_extensions_map_all_extmsg_CALLBACK NULL
#define gogoproto_goproto_extensions_map_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_extensions_map_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_extensions_map_all_extmsg, gogoproto_goproto_extensions_map_all_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_extensions_map_all = {
    NULL,
    NULL,
    &gogoproto_goproto_extensions_map_all_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_unrecognized_all */
typedef struct _gogoproto_goproto_unrecognized_all_extmsg {
    bool goproto_unrecognized_all;
} gogoproto_goproto_unrecognized_all_extmsg;
#define gogoproto_goproto_unrecognized_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_unrecognized_all, 63026)
#define gogoproto_goproto_unrecognized_all_extmsg_CALLBACK NULL
#define gogoproto_goproto_unrecognized_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_unrecognized_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_unrecognized_all_extmsg, gogoproto_goproto_unrecognized_all_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_unrecognized_all = {
    NULL,
    NULL,
    &gogoproto_goproto_unrecognized_all_extmsg_msg
};

/* Definition for extension field gogoproto_gogoproto_import */
typedef struct _gogoproto_gogoproto_import_extmsg {
    bool gogoproto_import;
} gogoproto_gogoproto_import_extmsg;
#define gogoproto_gogoproto_import_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     gogoproto_import, 63027)
#define gogoproto_gogoproto_import_extmsg_CALLBACK NULL
#define gogoproto_gogoproto_import_extmsg_DEFAULT NULL
pb_byte_t gogoproto_gogoproto_import_extmsg_default[] = {0x00};
PB_BIND(gogoproto_gogoproto_import_extmsg, gogoproto_gogoproto_import_extmsg, 4)
const pb_extension_type_t gogoproto_gogoproto_import = {
    NULL,
    NULL,
    &gogoproto_gogoproto_import_extmsg_msg
};

/* Definition for extension field gogoproto_protosizer_all */
typedef struct _gogoproto_protosizer_all_extmsg {
    bool protosizer_all;
} gogoproto_protosizer_all_extmsg;
#define gogoproto_protosizer_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     protosizer_all,  63028)
#define gogoproto_protosizer_all_extmsg_CALLBACK NULL
#define gogoproto_protosizer_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_protosizer_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_protosizer_all_extmsg, gogoproto_protosizer_all_extmsg, 4)
const pb_extension_type_t gogoproto_protosizer_all = {
    NULL,
    NULL,
    &gogoproto_protosizer_all_extmsg_msg
};

/* Definition for extension field gogoproto_compare_all */
typedef struct _gogoproto_compare_all_extmsg {
    bool compare_all;
} gogoproto_compare_all_extmsg;
#define gogoproto_compare_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     compare_all,     63029)
#define gogoproto_compare_all_extmsg_CALLBACK NULL
#define gogoproto_compare_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_compare_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_compare_all_extmsg, gogoproto_compare_all_extmsg, 4)
const pb_extension_type_t gogoproto_compare_all = {
    NULL,
    NULL,
    &gogoproto_compare_all_extmsg_msg
};

/* Definition for extension field gogoproto_typedecl_all */
typedef struct _gogoproto_typedecl_all_extmsg {
    bool typedecl_all;
} gogoproto_typedecl_all_extmsg;
#define gogoproto_typedecl_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     typedecl_all,    63030)
#define gogoproto_typedecl_all_extmsg_CALLBACK NULL
#define gogoproto_typedecl_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_typedecl_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_typedecl_all_extmsg, gogoproto_typedecl_all_extmsg, 4)
const pb_extension_type_t gogoproto_typedecl_all = {
    NULL,
    NULL,
    &gogoproto_typedecl_all_extmsg_msg
};

/* Definition for extension field gogoproto_enumdecl_all */
typedef struct _gogoproto_enumdecl_all_extmsg {
    bool enumdecl_all;
} gogoproto_enumdecl_all_extmsg;
#define gogoproto_enumdecl_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     enumdecl_all,    63031)
#define gogoproto_enumdecl_all_extmsg_CALLBACK NULL
#define gogoproto_enumdecl_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_enumdecl_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_enumdecl_all_extmsg, gogoproto_enumdecl_all_extmsg, 4)
const pb_extension_type_t gogoproto_enumdecl_all = {
    NULL,
    NULL,
    &gogoproto_enumdecl_all_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_registration */
typedef struct _gogoproto_goproto_registration_extmsg {
    bool goproto_registration;
} gogoproto_goproto_registration_extmsg;
#define gogoproto_goproto_registration_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_registration, 63032)
#define gogoproto_goproto_registration_extmsg_CALLBACK NULL
#define gogoproto_goproto_registration_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_registration_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_registration_extmsg, gogoproto_goproto_registration_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_registration = {
    NULL,
    NULL,
    &gogoproto_goproto_registration_extmsg_msg
};

/* Definition for extension field gogoproto_messagename_all */
typedef struct _gogoproto_messagename_all_extmsg {
    bool messagename_all;
} gogoproto_messagename_all_extmsg;
#define gogoproto_messagename_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     messagename_all, 63033)
#define gogoproto_messagename_all_extmsg_CALLBACK NULL
#define gogoproto_messagename_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_messagename_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_messagename_all_extmsg, gogoproto_messagename_all_extmsg, 4)
const pb_extension_type_t gogoproto_messagename_all = {
    NULL,
    NULL,
    &gogoproto_messagename_all_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_sizecache_all */
typedef struct _gogoproto_goproto_sizecache_all_extmsg {
    bool goproto_sizecache_all;
} gogoproto_goproto_sizecache_all_extmsg;
#define gogoproto_goproto_sizecache_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_sizecache_all, 63034)
#define gogoproto_goproto_sizecache_all_extmsg_CALLBACK NULL
#define gogoproto_goproto_sizecache_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_sizecache_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_sizecache_all_extmsg, gogoproto_goproto_sizecache_all_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_sizecache_all = {
    NULL,
    NULL,
    &gogoproto_goproto_sizecache_all_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_unkeyed_all */
typedef struct _gogoproto_goproto_unkeyed_all_extmsg {
    bool goproto_unkeyed_all;
} gogoproto_goproto_unkeyed_all_extmsg;
#define gogoproto_goproto_unkeyed_all_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_unkeyed_all, 63035)
#define gogoproto_goproto_unkeyed_all_extmsg_CALLBACK NULL
#define gogoproto_goproto_unkeyed_all_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_unkeyed_all_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_unkeyed_all_extmsg, gogoproto_goproto_unkeyed_all_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_unkeyed_all = {
    NULL,
    NULL,
    &gogoproto_goproto_unkeyed_all_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_getters */
typedef struct _gogoproto_goproto_getters_extmsg {
    bool goproto_getters;
} gogoproto_goproto_getters_extmsg;
#define gogoproto_goproto_getters_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_getters, 64001)
#define gogoproto_goproto_getters_extmsg_CALLBACK NULL
#define gogoproto_goproto_getters_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_getters_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_getters_extmsg, gogoproto_goproto_getters_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_getters = {
    NULL,
    NULL,
    &gogoproto_goproto_getters_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_stringer */
typedef struct _gogoproto_goproto_stringer_extmsg {
    bool goproto_stringer;
} gogoproto_goproto_stringer_extmsg;
#define gogoproto_goproto_stringer_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_stringer, 64003)
#define gogoproto_goproto_stringer_extmsg_CALLBACK NULL
#define gogoproto_goproto_stringer_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_stringer_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_stringer_extmsg, gogoproto_goproto_stringer_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_stringer = {
    NULL,
    NULL,
    &gogoproto_goproto_stringer_extmsg_msg
};

/* Definition for extension field gogoproto_verbose_equal */
typedef struct _gogoproto_verbose_equal_extmsg {
    bool verbose_equal;
} gogoproto_verbose_equal_extmsg;
#define gogoproto_verbose_equal_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     verbose_equal,   64004)
#define gogoproto_verbose_equal_extmsg_CALLBACK NULL
#define gogoproto_verbose_equal_extmsg_DEFAULT NULL
pb_byte_t gogoproto_verbose_equal_extmsg_default[] = {0x00};
PB_BIND(gogoproto_verbose_equal_extmsg, gogoproto_verbose_equal_extmsg, 4)
const pb_extension_type_t gogoproto_verbose_equal = {
    NULL,
    NULL,
    &gogoproto_verbose_equal_extmsg_msg
};

/* Definition for extension field gogoproto_face */
typedef struct _gogoproto_face_extmsg {
    bool face;
} gogoproto_face_extmsg;
#define gogoproto_face_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     face,            64005)
#define gogoproto_face_extmsg_CALLBACK NULL
#define gogoproto_face_extmsg_DEFAULT NULL
pb_byte_t gogoproto_face_extmsg_default[] = {0x00};
PB_BIND(gogoproto_face_extmsg, gogoproto_face_extmsg, 4)
const pb_extension_type_t gogoproto_face = {
    NULL,
    NULL,
    &gogoproto_face_extmsg_msg
};

/* Definition for extension field gogoproto_gostring */
typedef struct _gogoproto_gostring_extmsg {
    bool gostring;
} gogoproto_gostring_extmsg;
#define gogoproto_gostring_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     gostring,        64006)
#define gogoproto_gostring_extmsg_CALLBACK NULL
#define gogoproto_gostring_extmsg_DEFAULT NULL
pb_byte_t gogoproto_gostring_extmsg_default[] = {0x00};
PB_BIND(gogoproto_gostring_extmsg, gogoproto_gostring_extmsg, 4)
const pb_extension_type_t gogoproto_gostring = {
    NULL,
    NULL,
    &gogoproto_gostring_extmsg_msg
};

/* Definition for extension field gogoproto_populate */
typedef struct _gogoproto_populate_extmsg {
    bool populate;
} gogoproto_populate_extmsg;
#define gogoproto_populate_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     populate,        64007)
#define gogoproto_populate_extmsg_CALLBACK NULL
#define gogoproto_populate_extmsg_DEFAULT NULL
pb_byte_t gogoproto_populate_extmsg_default[] = {0x00};
PB_BIND(gogoproto_populate_extmsg, gogoproto_populate_extmsg, 4)
const pb_extension_type_t gogoproto_populate = {
    NULL,
    NULL,
    &gogoproto_populate_extmsg_msg
};

/* Definition for extension field gogoproto_stringer */
typedef struct _gogoproto_stringer_extmsg {
    bool stringer;
} gogoproto_stringer_extmsg;
#define gogoproto_stringer_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     stringer,        67008)
#define gogoproto_stringer_extmsg_CALLBACK NULL
#define gogoproto_stringer_extmsg_DEFAULT NULL
pb_byte_t gogoproto_stringer_extmsg_default[] = {0x00};
PB_BIND(gogoproto_stringer_extmsg, gogoproto_stringer_extmsg, 4)
const pb_extension_type_t gogoproto_stringer = {
    NULL,
    NULL,
    &gogoproto_stringer_extmsg_msg
};

/* Definition for extension field gogoproto_onlyone */
typedef struct _gogoproto_onlyone_extmsg {
    bool onlyone;
} gogoproto_onlyone_extmsg;
#define gogoproto_onlyone_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     onlyone,         64009)
#define gogoproto_onlyone_extmsg_CALLBACK NULL
#define gogoproto_onlyone_extmsg_DEFAULT NULL
pb_byte_t gogoproto_onlyone_extmsg_default[] = {0x00};
PB_BIND(gogoproto_onlyone_extmsg, gogoproto_onlyone_extmsg, 4)
const pb_extension_type_t gogoproto_onlyone = {
    NULL,
    NULL,
    &gogoproto_onlyone_extmsg_msg
};

/* Definition for extension field gogoproto_equal */
typedef struct _gogoproto_equal_extmsg {
    bool equal;
} gogoproto_equal_extmsg;
#define gogoproto_equal_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     equal,           64013)
#define gogoproto_equal_extmsg_CALLBACK NULL
#define gogoproto_equal_extmsg_DEFAULT NULL
pb_byte_t gogoproto_equal_extmsg_default[] = {0x00};
PB_BIND(gogoproto_equal_extmsg, gogoproto_equal_extmsg, 4)
const pb_extension_type_t gogoproto_equal = {
    NULL,
    NULL,
    &gogoproto_equal_extmsg_msg
};

/* Definition for extension field gogoproto_description */
typedef struct _gogoproto_description_extmsg {
    bool description;
} gogoproto_description_extmsg;
#define gogoproto_description_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     description,     64014)
#define gogoproto_description_extmsg_CALLBACK NULL
#define gogoproto_description_extmsg_DEFAULT NULL
pb_byte_t gogoproto_description_extmsg_default[] = {0x00};
PB_BIND(gogoproto_description_extmsg, gogoproto_description_extmsg, 4)
const pb_extension_type_t gogoproto_description = {
    NULL,
    NULL,
    &gogoproto_description_extmsg_msg
};

/* Definition for extension field gogoproto_testgen */
typedef struct _gogoproto_testgen_extmsg {
    bool testgen;
} gogoproto_testgen_extmsg;
#define gogoproto_testgen_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     testgen,         64015)
#define gogoproto_testgen_extmsg_CALLBACK NULL
#define gogoproto_testgen_extmsg_DEFAULT NULL
pb_byte_t gogoproto_testgen_extmsg_default[] = {0x00};
PB_BIND(gogoproto_testgen_extmsg, gogoproto_testgen_extmsg, 4)
const pb_extension_type_t gogoproto_testgen = {
    NULL,
    NULL,
    &gogoproto_testgen_extmsg_msg
};

/* Definition for extension field gogoproto_benchgen */
typedef struct _gogoproto_benchgen_extmsg {
    bool benchgen;
} gogoproto_benchgen_extmsg;
#define gogoproto_benchgen_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     benchgen,        64016)
#define gogoproto_benchgen_extmsg_CALLBACK NULL
#define gogoproto_benchgen_extmsg_DEFAULT NULL
pb_byte_t gogoproto_benchgen_extmsg_default[] = {0x00};
PB_BIND(gogoproto_benchgen_extmsg, gogoproto_benchgen_extmsg, 4)
const pb_extension_type_t gogoproto_benchgen = {
    NULL,
    NULL,
    &gogoproto_benchgen_extmsg_msg
};

/* Definition for extension field gogoproto_marshaler */
typedef struct _gogoproto_marshaler_extmsg {
    bool marshaler;
} gogoproto_marshaler_extmsg;
#define gogoproto_marshaler_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     marshaler,       64017)
#define gogoproto_marshaler_extmsg_CALLBACK NULL
#define gogoproto_marshaler_extmsg_DEFAULT NULL
pb_byte_t gogoproto_marshaler_extmsg_default[] = {0x00};
PB_BIND(gogoproto_marshaler_extmsg, gogoproto_marshaler_extmsg, 4)
const pb_extension_type_t gogoproto_marshaler = {
    NULL,
    NULL,
    &gogoproto_marshaler_extmsg_msg
};

/* Definition for extension field gogoproto_unmarshaler */
typedef struct _gogoproto_unmarshaler_extmsg {
    bool unmarshaler;
} gogoproto_unmarshaler_extmsg;
#define gogoproto_unmarshaler_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     unmarshaler,     64018)
#define gogoproto_unmarshaler_extmsg_CALLBACK NULL
#define gogoproto_unmarshaler_extmsg_DEFAULT NULL
pb_byte_t gogoproto_unmarshaler_extmsg_default[] = {0x00};
PB_BIND(gogoproto_unmarshaler_extmsg, gogoproto_unmarshaler_extmsg, 4)
const pb_extension_type_t gogoproto_unmarshaler = {
    NULL,
    NULL,
    &gogoproto_unmarshaler_extmsg_msg
};

/* Definition for extension field gogoproto_stable_marshaler */
typedef struct _gogoproto_stable_marshaler_extmsg {
    bool stable_marshaler;
} gogoproto_stable_marshaler_extmsg;
#define gogoproto_stable_marshaler_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     stable_marshaler, 64019)
#define gogoproto_stable_marshaler_extmsg_CALLBACK NULL
#define gogoproto_stable_marshaler_extmsg_DEFAULT NULL
pb_byte_t gogoproto_stable_marshaler_extmsg_default[] = {0x00};
PB_BIND(gogoproto_stable_marshaler_extmsg, gogoproto_stable_marshaler_extmsg, 4)
const pb_extension_type_t gogoproto_stable_marshaler = {
    NULL,
    NULL,
    &gogoproto_stable_marshaler_extmsg_msg
};

/* Definition for extension field gogoproto_sizer */
typedef struct _gogoproto_sizer_extmsg {
    bool sizer;
} gogoproto_sizer_extmsg;
#define gogoproto_sizer_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     sizer,           64020)
#define gogoproto_sizer_extmsg_CALLBACK NULL
#define gogoproto_sizer_extmsg_DEFAULT NULL
pb_byte_t gogoproto_sizer_extmsg_default[] = {0x00};
PB_BIND(gogoproto_sizer_extmsg, gogoproto_sizer_extmsg, 4)
const pb_extension_type_t gogoproto_sizer = {
    NULL,
    NULL,
    &gogoproto_sizer_extmsg_msg
};

/* Definition for extension field gogoproto_unsafe_marshaler */
typedef struct _gogoproto_unsafe_marshaler_extmsg {
    bool unsafe_marshaler;
} gogoproto_unsafe_marshaler_extmsg;
#define gogoproto_unsafe_marshaler_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     unsafe_marshaler, 64023)
#define gogoproto_unsafe_marshaler_extmsg_CALLBACK NULL
#define gogoproto_unsafe_marshaler_extmsg_DEFAULT NULL
pb_byte_t gogoproto_unsafe_marshaler_extmsg_default[] = {0x00};
PB_BIND(gogoproto_unsafe_marshaler_extmsg, gogoproto_unsafe_marshaler_extmsg, 4)
const pb_extension_type_t gogoproto_unsafe_marshaler = {
    NULL,
    NULL,
    &gogoproto_unsafe_marshaler_extmsg_msg
};

/* Definition for extension field gogoproto_unsafe_unmarshaler */
typedef struct _gogoproto_unsafe_unmarshaler_extmsg {
    bool unsafe_unmarshaler;
} gogoproto_unsafe_unmarshaler_extmsg;
#define gogoproto_unsafe_unmarshaler_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     unsafe_unmarshaler, 64024)
#define gogoproto_unsafe_unmarshaler_extmsg_CALLBACK NULL
#define gogoproto_unsafe_unmarshaler_extmsg_DEFAULT NULL
pb_byte_t gogoproto_unsafe_unmarshaler_extmsg_default[] = {0x00};
PB_BIND(gogoproto_unsafe_unmarshaler_extmsg, gogoproto_unsafe_unmarshaler_extmsg, 4)
const pb_extension_type_t gogoproto_unsafe_unmarshaler = {
    NULL,
    NULL,
    &gogoproto_unsafe_unmarshaler_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_extensions_map */
typedef struct _gogoproto_goproto_extensions_map_extmsg {
    bool goproto_extensions_map;
} gogoproto_goproto_extensions_map_extmsg;
#define gogoproto_goproto_extensions_map_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_extensions_map, 64025)
#define gogoproto_goproto_extensions_map_extmsg_CALLBACK NULL
#define gogoproto_goproto_extensions_map_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_extensions_map_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_extensions_map_extmsg, gogoproto_goproto_extensions_map_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_extensions_map = {
    NULL,
    NULL,
    &gogoproto_goproto_extensions_map_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_unrecognized */
typedef struct _gogoproto_goproto_unrecognized_extmsg {
    bool goproto_unrecognized;
} gogoproto_goproto_unrecognized_extmsg;
#define gogoproto_goproto_unrecognized_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_unrecognized, 64026)
#define gogoproto_goproto_unrecognized_extmsg_CALLBACK NULL
#define gogoproto_goproto_unrecognized_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_unrecognized_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_unrecognized_extmsg, gogoproto_goproto_unrecognized_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_unrecognized = {
    NULL,
    NULL,
    &gogoproto_goproto_unrecognized_extmsg_msg
};

/* Definition for extension field gogoproto_protosizer */
typedef struct _gogoproto_protosizer_extmsg {
    bool protosizer;
} gogoproto_protosizer_extmsg;
#define gogoproto_protosizer_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     protosizer,      64028)
#define gogoproto_protosizer_extmsg_CALLBACK NULL
#define gogoproto_protosizer_extmsg_DEFAULT NULL
pb_byte_t gogoproto_protosizer_extmsg_default[] = {0x00};
PB_BIND(gogoproto_protosizer_extmsg, gogoproto_protosizer_extmsg, 4)
const pb_extension_type_t gogoproto_protosizer = {
    NULL,
    NULL,
    &gogoproto_protosizer_extmsg_msg
};

/* Definition for extension field gogoproto_compare */
typedef struct _gogoproto_compare_extmsg {
    bool compare;
} gogoproto_compare_extmsg;
#define gogoproto_compare_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     compare,         64029)
#define gogoproto_compare_extmsg_CALLBACK NULL
#define gogoproto_compare_extmsg_DEFAULT NULL
pb_byte_t gogoproto_compare_extmsg_default[] = {0x00};
PB_BIND(gogoproto_compare_extmsg, gogoproto_compare_extmsg, 4)
const pb_extension_type_t gogoproto_compare = {
    NULL,
    NULL,
    &gogoproto_compare_extmsg_msg
};

/* Definition for extension field gogoproto_typedecl */
typedef struct _gogoproto_typedecl_extmsg {
    bool typedecl;
} gogoproto_typedecl_extmsg;
#define gogoproto_typedecl_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     typedecl,        64030)
#define gogoproto_typedecl_extmsg_CALLBACK NULL
#define gogoproto_typedecl_extmsg_DEFAULT NULL
pb_byte_t gogoproto_typedecl_extmsg_default[] = {0x00};
PB_BIND(gogoproto_typedecl_extmsg, gogoproto_typedecl_extmsg, 4)
const pb_extension_type_t gogoproto_typedecl = {
    NULL,
    NULL,
    &gogoproto_typedecl_extmsg_msg
};

/* Definition for extension field gogoproto_messagename */
typedef struct _gogoproto_messagename_extmsg {
    bool messagename;
} gogoproto_messagename_extmsg;
#define gogoproto_messagename_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     messagename,     64033)
#define gogoproto_messagename_extmsg_CALLBACK NULL
#define gogoproto_messagename_extmsg_DEFAULT NULL
pb_byte_t gogoproto_messagename_extmsg_default[] = {0x00};
PB_BIND(gogoproto_messagename_extmsg, gogoproto_messagename_extmsg, 4)
const pb_extension_type_t gogoproto_messagename = {
    NULL,
    NULL,
    &gogoproto_messagename_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_sizecache */
typedef struct _gogoproto_goproto_sizecache_extmsg {
    bool goproto_sizecache;
} gogoproto_goproto_sizecache_extmsg;
#define gogoproto_goproto_sizecache_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_sizecache, 64034)
#define gogoproto_goproto_sizecache_extmsg_CALLBACK NULL
#define gogoproto_goproto_sizecache_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_sizecache_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_sizecache_extmsg, gogoproto_goproto_sizecache_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_sizecache = {
    NULL,
    NULL,
    &gogoproto_goproto_sizecache_extmsg_msg
};

/* Definition for extension field gogoproto_goproto_unkeyed */
typedef struct _gogoproto_goproto_unkeyed_extmsg {
    bool goproto_unkeyed;
} gogoproto_goproto_unkeyed_extmsg;
#define gogoproto_goproto_unkeyed_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     goproto_unkeyed, 64035)
#define gogoproto_goproto_unkeyed_extmsg_CALLBACK NULL
#define gogoproto_goproto_unkeyed_extmsg_DEFAULT NULL
pb_byte_t gogoproto_goproto_unkeyed_extmsg_default[] = {0x00};
PB_BIND(gogoproto_goproto_unkeyed_extmsg, gogoproto_goproto_unkeyed_extmsg, 4)
const pb_extension_type_t gogoproto_goproto_unkeyed = {
    NULL,
    NULL,
    &gogoproto_goproto_unkeyed_extmsg_msg
};

/* Definition for extension field gogoproto_nullable */
typedef struct _gogoproto_nullable_extmsg {
    bool nullable;
} gogoproto_nullable_extmsg;
#define gogoproto_nullable_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     nullable,        65001)
#define gogoproto_nullable_extmsg_CALLBACK NULL
#define gogoproto_nullable_extmsg_DEFAULT NULL
pb_byte_t gogoproto_nullable_extmsg_default[] = {0x00};
PB_BIND(gogoproto_nullable_extmsg, gogoproto_nullable_extmsg, 4)
const pb_extension_type_t gogoproto_nullable = {
    NULL,
    NULL,
    &gogoproto_nullable_extmsg_msg
};

/* Definition for extension field gogoproto_embed */
typedef struct _gogoproto_embed_extmsg {
    bool embed;
} gogoproto_embed_extmsg;
#define gogoproto_embed_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     embed,           65002)
#define gogoproto_embed_extmsg_CALLBACK NULL
#define gogoproto_embed_extmsg_DEFAULT NULL
pb_byte_t gogoproto_embed_extmsg_default[] = {0x00};
PB_BIND(gogoproto_embed_extmsg, gogoproto_embed_extmsg, 4)
const pb_extension_type_t gogoproto_embed = {
    NULL,
    NULL,
    &gogoproto_embed_extmsg_msg
};

/* Definition for extension field gogoproto_customtype */
typedef struct _gogoproto_customtype_extmsg {
    pb_callback_t customtype;
} gogoproto_customtype_extmsg;
#define gogoproto_customtype_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   customtype,      65003)
#define gogoproto_customtype_extmsg_CALLBACK pb_default_field_callback
#define gogoproto_customtype_extmsg_DEFAULT NULL
pb_byte_t gogoproto_customtype_extmsg_default[] = {0x00};
PB_BIND(gogoproto_customtype_extmsg, gogoproto_customtype_extmsg, 4)
const pb_extension_type_t gogoproto_customtype = {
    NULL,
    NULL,
    &gogoproto_customtype_extmsg_msg
};

/* Definition for extension field gogoproto_customname */
typedef struct _gogoproto_customname_extmsg {
    pb_callback_t customname;
} gogoproto_customname_extmsg;
#define gogoproto_customname_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   customname,      65004)
#define gogoproto_customname_extmsg_CALLBACK pb_default_field_callback
#define gogoproto_customname_extmsg_DEFAULT NULL
pb_byte_t gogoproto_customname_extmsg_default[] = {0x00};
PB_BIND(gogoproto_customname_extmsg, gogoproto_customname_extmsg, 4)
const pb_extension_type_t gogoproto_customname = {
    NULL,
    NULL,
    &gogoproto_customname_extmsg_msg
};

/* Definition for extension field gogoproto_jsontag */
typedef struct _gogoproto_jsontag_extmsg {
    pb_callback_t jsontag;
} gogoproto_jsontag_extmsg;
#define gogoproto_jsontag_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   jsontag,         65005)
#define gogoproto_jsontag_extmsg_CALLBACK pb_default_field_callback
#define gogoproto_jsontag_extmsg_DEFAULT NULL
pb_byte_t gogoproto_jsontag_extmsg_default[] = {0x00};
PB_BIND(gogoproto_jsontag_extmsg, gogoproto_jsontag_extmsg, 4)
const pb_extension_type_t gogoproto_jsontag = {
    NULL,
    NULL,
    &gogoproto_jsontag_extmsg_msg
};

/* Definition for extension field gogoproto_moretags */
typedef struct _gogoproto_moretags_extmsg {
    pb_callback_t moretags;
} gogoproto_moretags_extmsg;
#define gogoproto_moretags_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   moretags,        65006)
#define gogoproto_moretags_extmsg_CALLBACK pb_default_field_callback
#define gogoproto_moretags_extmsg_DEFAULT NULL
pb_byte_t gogoproto_moretags_extmsg_default[] = {0x00};
PB_BIND(gogoproto_moretags_extmsg, gogoproto_moretags_extmsg, 4)
const pb_extension_type_t gogoproto_moretags = {
    NULL,
    NULL,
    &gogoproto_moretags_extmsg_msg
};

/* Definition for extension field gogoproto_casttype */
typedef struct _gogoproto_casttype_extmsg {
    pb_callback_t casttype;
} gogoproto_casttype_extmsg;
#define gogoproto_casttype_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   casttype,        65007)
#define gogoproto_casttype_extmsg_CALLBACK pb_default_field_callback
#define gogoproto_casttype_extmsg_DEFAULT NULL
pb_byte_t gogoproto_casttype_extmsg_default[] = {0x00};
PB_BIND(gogoproto_casttype_extmsg, gogoproto_casttype_extmsg, 4)
const pb_extension_type_t gogoproto_casttype = {
    NULL,
    NULL,
    &gogoproto_casttype_extmsg_msg
};

/* Definition for extension field gogoproto_castkey */
typedef struct _gogoproto_castkey_extmsg {
    pb_callback_t castkey;
} gogoproto_castkey_extmsg;
#define gogoproto_castkey_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   castkey,         65008)
#define gogoproto_castkey_extmsg_CALLBACK pb_default_field_callback
#define gogoproto_castkey_extmsg_DEFAULT NULL
pb_byte_t gogoproto_castkey_extmsg_default[] = {0x00};
PB_BIND(gogoproto_castkey_extmsg, gogoproto_castkey_extmsg, 4)
const pb_extension_type_t gogoproto_castkey = {
    NULL,
    NULL,
    &gogoproto_castkey_extmsg_msg
};

/* Definition for extension field gogoproto_castvalue */
typedef struct _gogoproto_castvalue_extmsg {
    pb_callback_t castvalue;
} gogoproto_castvalue_extmsg;
#define gogoproto_castvalue_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   castvalue,       65009)
#define gogoproto_castvalue_extmsg_CALLBACK pb_default_field_callback
#define gogoproto_castvalue_extmsg_DEFAULT NULL
pb_byte_t gogoproto_castvalue_extmsg_default[] = {0x00};
PB_BIND(gogoproto_castvalue_extmsg, gogoproto_castvalue_extmsg, 4)
const pb_extension_type_t gogoproto_castvalue = {
    NULL,
    NULL,
    &gogoproto_castvalue_extmsg_msg
};

/* Definition for extension field gogoproto_stdtime */
typedef struct _gogoproto_stdtime_extmsg {
    bool stdtime;
} gogoproto_stdtime_extmsg;
#define gogoproto_stdtime_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     stdtime,         65010)
#define gogoproto_stdtime_extmsg_CALLBACK NULL
#define gogoproto_stdtime_extmsg_DEFAULT NULL
pb_byte_t gogoproto_stdtime_extmsg_default[] = {0x00};
PB_BIND(gogoproto_stdtime_extmsg, gogoproto_stdtime_extmsg, 4)
const pb_extension_type_t gogoproto_stdtime = {
    NULL,
    NULL,
    &gogoproto_stdtime_extmsg_msg
};

/* Definition for extension field gogoproto_stdduration */
typedef struct _gogoproto_stdduration_extmsg {
    bool stdduration;
} gogoproto_stdduration_extmsg;
#define gogoproto_stdduration_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     stdduration,     65011)
#define gogoproto_stdduration_extmsg_CALLBACK NULL
#define gogoproto_stdduration_extmsg_DEFAULT NULL
pb_byte_t gogoproto_stdduration_extmsg_default[] = {0x00};
PB_BIND(gogoproto_stdduration_extmsg, gogoproto_stdduration_extmsg, 4)
const pb_extension_type_t gogoproto_stdduration = {
    NULL,
    NULL,
    &gogoproto_stdduration_extmsg_msg
};

/* Definition for extension field gogoproto_wktpointer */
typedef struct _gogoproto_wktpointer_extmsg {
    bool wktpointer;
} gogoproto_wktpointer_extmsg;
#define gogoproto_wktpointer_extmsg_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, BOOL,     wktpointer,      65012)
#define gogoproto_wktpointer_extmsg_CALLBACK NULL
#define gogoproto_wktpointer_extmsg_DEFAULT NULL
pb_byte_t gogoproto_wktpointer_extmsg_default[] = {0x00};
PB_BIND(gogoproto_wktpointer_extmsg, gogoproto_wktpointer_extmsg, 4)
const pb_extension_type_t gogoproto_wktpointer = {
    NULL,
    NULL,
    &gogoproto_wktpointer_extmsg_msg
};

/* Definition for extension field gogoproto_castrepeated */
typedef struct _gogoproto_castrepeated_extmsg {
    pb_callback_t castrepeated;
} gogoproto_castrepeated_extmsg;
#define gogoproto_castrepeated_extmsg_FIELDLIST(X, a) \
X(a, CALLBACK, REQUIRED, STRING,   castrepeated,    65013)
#define gogoproto_castrepeated_extmsg_CALLBACK pb_default_field_callback
#define gogoproto_castrepeated_extmsg_DEFAULT NULL
pb_byte_t gogoproto_castrepeated_extmsg_default[] = {0x00};
PB_BIND(gogoproto_castrepeated_extmsg, gogoproto_castrepeated_extmsg, 4)
const pb_extension_type_t gogoproto_castrepeated = {
    NULL,
    NULL,
    &gogoproto_castrepeated_extmsg_msg
};


