/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "cosmos/tx/v1beta1/tx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_tx_v1beta1_Tx, cosmos_tx_v1beta1_Tx, 2)


PB_BIND(cosmos_tx_v1beta1_TxRaw, cosmos_tx_v1beta1_TxRaw, AUTO)


PB_BIND(cosmos_tx_v1beta1_SignDoc, cosmos_tx_v1beta1_SignDoc, AUTO)


PB_BIND(cosmos_tx_v1beta1_SignDocDirectAux, cosmos_tx_v1beta1_SignDocDirectAux, AUTO)


PB_BIND(cosmos_tx_v1beta1_TxBody, cosmos_tx_v1beta1_TxBody, 4)


PB_BIND(cosmos_tx_v1beta1_AuthInfo, cosmos_tx_v1beta1_AuthInfo, AUTO)


PB_BIND(cosmos_tx_v1beta1_SignerInfo, cosmos_tx_v1beta1_SignerInfo, AUTO)


PB_BIND(cosmos_tx_v1beta1_ModeInfo, cosmos_tx_v1beta1_ModeInfo, AUTO)


PB_BIND(cosmos_tx_v1beta1_ModeInfo_Single, cosmos_tx_v1beta1_ModeInfo_Single, AUTO)


PB_BIND(cosmos_tx_v1beta1_ModeInfo_Multi, cosmos_tx_v1beta1_ModeInfo_Multi, AUTO)


PB_BIND(cosmos_tx_v1beta1_Fee, cosmos_tx_v1beta1_Fee, AUTO)


PB_BIND(cosmos_tx_v1beta1_Tip, cosmos_tx_v1beta1_Tip, AUTO)


PB_BIND(cosmos_tx_v1beta1_AuxSignerData, cosmos_tx_v1beta1_AuxSignerData, AUTO)



