# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planetmintgo/machine/liquid_asset.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'planetmintgo/machine/liquid_asset.proto\x12\x14planetmintgo.machine\"]\n\x0bLiquidAsset\x12\x11\n\tmachineID\x18\x01 \x01(\t\x12\x16\n\x0emachineAddress\x18\x02 \x01(\t\x12\x0f\n\x07\x61ssetID\x18\x03 \x01(\t\x12\x12\n\nregistered\x18\x04 \x01(\x08\x42\x35Z3github.com/planetmint/planetmint-go/x/machine/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planetmintgo.machine.liquid_asset_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/planetmint/planetmint-go/x/machine/types'
  _LIQUIDASSET._serialized_start=65
  _LIQUIDASSET._serialized_end=158
# @@protoc_insertion_point(module_scope)
