# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planetmintgo/machine/machine.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"planetmintgo/machine/machine.proto\x12\x14planetmintgo.machine\"\x9b\x02\n\x07Machine\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06ticker\x18\x02 \x01(\t\x12\x0e\n\x06\x64omain\x18\x03 \x01(\t\x12\x0f\n\x07reissue\x18\x04 \x01(\x08\x12\x0e\n\x06\x61mount\x18\x05 \x01(\x04\x12\x11\n\tprecision\x18\x06 \x01(\x04\x12\x18\n\x10issuerPlanetmint\x18\x07 \x01(\t\x12\x14\n\x0cissuerLiquid\x18\x08 \x01(\t\x12\x11\n\tmachineId\x18\t \x01(\t\x12\x30\n\x08metadata\x18\n \x01(\x0b\x32\x1e.planetmintgo.machine.Metadata\x12\x0c\n\x04type\x18\x0b \x01(\r\x12\x1a\n\x12machineIdSignature\x18\x0c \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\r \x01(\t\"[\n\x08Metadata\x12\x0b\n\x03gps\x18\x01 \x01(\t\x12\x0e\n\x06\x64\x65vice\x18\x02 \x01(\t\x12\x17\n\x0f\x61ssetDefinition\x18\x03 \x01(\t\x12\x19\n\x11\x61\x64\x64itionalDataCID\x18\x04 \x01(\t\"b\n\x0cMachineIndex\x12\x11\n\tmachineId\x18\x01 \x01(\t\x12\x18\n\x10issuerPlanetmint\x18\x02 \x01(\t\x12\x14\n\x0cissuerLiquid\x18\x03 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x04 \x01(\tB5Z3github.com/planetmint/planetmint-go/x/machine/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planetmintgo.machine.machine_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/planetmint/planetmint-go/x/machine/types'
  _MACHINE._serialized_start=61
  _MACHINE._serialized_end=344
  _METADATA._serialized_start=346
  _METADATA._serialized_end=437
  _MACHINEINDEX._serialized_start=439
  _MACHINEINDEX._serialized_end=537
# @@protoc_insertion_point(module_scope)
