# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planetmintgo/machine/params.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!planetmintgo/machine/params.proto\x12\x14planetmintgo.machine\x1a\x14gogoproto/gogo.proto\"\xb0\x01\n\x06Params\x12\x1d\n\x15\x61sset_registry_scheme\x18\x01 \x01(\t\x12\x1d\n\x15\x61sset_registry_domain\x18\x02 \x01(\t\x12\x1b\n\x13\x61sset_registry_path\x18\x03 \x01(\t\x12\"\n\x1a\x64\x61o_machine_funding_amount\x18\x04 \x01(\x04\x12!\n\x19\x64\x61o_machine_funding_denom\x18\x05 \x01(\t:\x04\x98\xa0\x1f\x00\x42\x35Z3github.com/planetmint/planetmint-go/x/machine/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planetmintgo.machine.params_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/planetmint/planetmint-go/x/machine/types'
  _PARAMS._options = None
  _PARAMS._serialized_options = b'\230\240\037\000'
  _PARAMS._serialized_start=82
  _PARAMS._serialized_end=258
# @@protoc_insertion_point(module_scope)
