/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_COSMOS_BASE_V1BETA1_COSMOS_BASE_V1BETA1_COIN_PB_H_INCLUDED
#define PB_COSMOS_BASE_V1BETA1_COSMOS_BASE_V1BETA1_COIN_PB_H_INCLUDED
#include <pb.h>
#include "gogoproto/gogo.pb.h"
#include "cosmos_proto/cosmos.pb.h"
#include "amino/amino.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Coin defines a token with a denomination and an amount.

 NOTE: The amount field is an Int which implements the custom method
 signatures required by gogoproto. */
typedef struct _cosmos_base_v1beta1_Coin {
    pb_callback_t denom;
    pb_callback_t amount;
} cosmos_base_v1beta1_Coin;

/* DecCoin defines a token with a denomination and a decimal amount.

 NOTE: The amount field is an Dec which implements the custom method
 signatures required by gogoproto. */
typedef struct _cosmos_base_v1beta1_DecCoin {
    pb_callback_t denom;
    pb_callback_t amount;
} cosmos_base_v1beta1_DecCoin;

/* IntProto defines a Protobuf wrapper around an Int object. */
typedef struct _cosmos_base_v1beta1_IntProto {
    pb_callback_t int_;
} cosmos_base_v1beta1_IntProto;

/* DecProto defines a Protobuf wrapper around a Dec object. */
typedef struct _cosmos_base_v1beta1_DecProto {
    pb_callback_t dec;
} cosmos_base_v1beta1_DecProto;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_base_v1beta1_Coin_init_default    {{{NULL}, NULL}, {{NULL}, NULL}}
#define cosmos_base_v1beta1_DecCoin_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define cosmos_base_v1beta1_IntProto_init_default {{{NULL}, NULL}}
#define cosmos_base_v1beta1_DecProto_init_default {{{NULL}, NULL}}
#define cosmos_base_v1beta1_Coin_init_zero       {{{NULL}, NULL}, {{NULL}, NULL}}
#define cosmos_base_v1beta1_DecCoin_init_zero    {{{NULL}, NULL}, {{NULL}, NULL}}
#define cosmos_base_v1beta1_IntProto_init_zero   {{{NULL}, NULL}}
#define cosmos_base_v1beta1_DecProto_init_zero   {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_base_v1beta1_Coin_denom_tag       1
#define cosmos_base_v1beta1_Coin_amount_tag      2
#define cosmos_base_v1beta1_DecCoin_denom_tag    1
#define cosmos_base_v1beta1_DecCoin_amount_tag   2
#define cosmos_base_v1beta1_IntProto_int_tag     1
#define cosmos_base_v1beta1_DecProto_dec_tag     1

/* Struct field encoding specification for nanopb */
#define cosmos_base_v1beta1_Coin_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   denom,             1) \
X(a, CALLBACK, SINGULAR, STRING,   amount,            2)
#define cosmos_base_v1beta1_Coin_CALLBACK pb_default_field_callback
#define cosmos_base_v1beta1_Coin_DEFAULT NULL

#define cosmos_base_v1beta1_DecCoin_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   denom,             1) \
X(a, CALLBACK, SINGULAR, STRING,   amount,            2)
#define cosmos_base_v1beta1_DecCoin_CALLBACK pb_default_field_callback
#define cosmos_base_v1beta1_DecCoin_DEFAULT NULL

#define cosmos_base_v1beta1_IntProto_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   int_,               1)
#define cosmos_base_v1beta1_IntProto_CALLBACK pb_default_field_callback
#define cosmos_base_v1beta1_IntProto_DEFAULT NULL

#define cosmos_base_v1beta1_DecProto_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   dec,               1)
#define cosmos_base_v1beta1_DecProto_CALLBACK pb_default_field_callback
#define cosmos_base_v1beta1_DecProto_DEFAULT NULL

extern const pb_msgdesc_t cosmos_base_v1beta1_Coin_msg;
extern const pb_msgdesc_t cosmos_base_v1beta1_DecCoin_msg;
extern const pb_msgdesc_t cosmos_base_v1beta1_IntProto_msg;
extern const pb_msgdesc_t cosmos_base_v1beta1_DecProto_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_base_v1beta1_Coin_fields &cosmos_base_v1beta1_Coin_msg
#define cosmos_base_v1beta1_DecCoin_fields &cosmos_base_v1beta1_DecCoin_msg
#define cosmos_base_v1beta1_IntProto_fields &cosmos_base_v1beta1_IntProto_msg
#define cosmos_base_v1beta1_DecProto_fields &cosmos_base_v1beta1_DecProto_msg

/* Maximum encoded size of messages (where known) */
/* cosmos_base_v1beta1_Coin_size depends on runtime parameters */
/* cosmos_base_v1beta1_DecCoin_size depends on runtime parameters */
/* cosmos_base_v1beta1_IntProto_size depends on runtime parameters */
/* cosmos_base_v1beta1_DecProto_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
