/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "cosmos/base/v1beta1/coin.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_base_v1beta1_Coin, cosmos_base_v1beta1_Coin, AUTO)


PB_BIND(cosmos_base_v1beta1_DecCoin, cosmos_base_v1beta1_DecCoin, AUTO)


PB_BIND(cosmos_base_v1beta1_IntProto, cosmos_base_v1beta1_IntProto, AUTO)


PB_BIND(cosmos_base_v1beta1_DecProto, cosmos_base_v1beta1_DecProto, AUTO)



