/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "planetmintgo/machine/machine.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(planetmintgo_machine_Machine, planetmintgo_machine_Machine, AUTO)


PB_BIND(planetmintgo_machine_Metadata, planetmintgo_machine_Metadata, AUTO)


PB_BIND(planetmintgo_machine_MachineIndex, planetmintgo_machine_MachineIndex, AUTO)



