/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PLANETMINTGO_MACHINE_PLANETMINTGO_MACHINE_TRUST_ANCHOR_PB_H_INCLUDED
#define PB_PLANETMINTGO_MACHINE_PLANETMINTGO_MACHINE_TRUST_ANCHOR_PB_H_INCLUDED
#define PB_NO_STATIC_ASSERT 1 
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _planetmintgo_machine_TrustAnchor {
    pb_callback_t pubkey;
} planetmintgo_machine_TrustAnchor;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define planetmintgo_machine_TrustAnchor_init_default {{{NULL}, NULL}}
#define planetmintgo_machine_TrustAnchor_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define planetmintgo_machine_TrustAnchor_pubkey_tag 1

/* Struct field encoding specification for nanopb */
#define planetmintgo_machine_TrustAnchor_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   pubkey,            1)
#define planetmintgo_machine_TrustAnchor_CALLBACK pb_default_field_callback
#define planetmintgo_machine_TrustAnchor_DEFAULT NULL

extern const pb_msgdesc_t planetmintgo_machine_TrustAnchor_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define planetmintgo_machine_TrustAnchor_fields &planetmintgo_machine_TrustAnchor_msg

/* Maximum encoded size of messages (where known) */
/* planetmintgo_machine_TrustAnchor_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
