/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "planetmintgo/machine/tx.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(planetmintgo_machine_MsgAttestMachine, planetmintgo_machine_MsgAttestMachine, AUTO)


PB_BIND(planetmintgo_machine_MsgAttestMachineResponse, planetmintgo_machine_MsgAttestMachineResponse, AUTO)


PB_BIND(planetmintgo_machine_MsgRegisterTrustAnchor, planetmintgo_machine_MsgRegisterTrustAnchor, AUTO)


PB_BIND(planetmintgo_machine_MsgRegisterTrustAnchorResponse, planetmintgo_machine_MsgRegisterTrustAnchorResponse, AUTO)


PB_BIND(planetmintgo_machine_MsgNotarizeLiquidAsset, planetmintgo_machine_MsgNotarizeLiquidAsset, AUTO)


PB_BIND(planetmintgo_machine_MsgNotarizeLiquidAssetResponse, planetmintgo_machine_MsgNotarizeLiquidAssetResponse, AUTO)



