/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_PLANETMINTGO_MACHINE_PLANETMINTGO_MACHINE_TX_PB_H_INCLUDED
#define PB_PLANETMINTGO_MACHINE_PLANETMINTGO_MACHINE_TX_PB_H_INCLUDED
#define PB_NO_STATIC_ASSERT 1 
#include <pb.h>
#include "planetmintgo/machine/machine.pb.h"
#include "planetmintgo/machine/trust_anchor.pb.h"
#include "planetmintgo/machine/liquid_asset.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _planetmintgo_machine_MsgAttestMachine {
    pb_callback_t creator;
    bool has_machine;
    planetmintgo_machine_Machine machine;
} planetmintgo_machine_MsgAttestMachine;

typedef struct _planetmintgo_machine_MsgAttestMachineResponse {
    char dummy_field;
} planetmintgo_machine_MsgAttestMachineResponse;

typedef struct _planetmintgo_machine_MsgRegisterTrustAnchor {
    pb_callback_t creator;
    bool has_trustAnchor;
    planetmintgo_machine_TrustAnchor trustAnchor;
} planetmintgo_machine_MsgRegisterTrustAnchor;

typedef struct _planetmintgo_machine_MsgRegisterTrustAnchorResponse {
    char dummy_field;
} planetmintgo_machine_MsgRegisterTrustAnchorResponse;

typedef struct _planetmintgo_machine_MsgNotarizeLiquidAsset {
    pb_callback_t creator;
    bool has_notarization;
    planetmintgo_machine_LiquidAsset notarization;
} planetmintgo_machine_MsgNotarizeLiquidAsset;

typedef struct _planetmintgo_machine_MsgNotarizeLiquidAssetResponse {
    char dummy_field;
} planetmintgo_machine_MsgNotarizeLiquidAssetResponse;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define planetmintgo_machine_MsgAttestMachine_init_default {{{NULL}, NULL}, false, planetmintgo_machine_Machine_init_default}
#define planetmintgo_machine_MsgAttestMachineResponse_init_default {0}
#define planetmintgo_machine_MsgRegisterTrustAnchor_init_default {{{NULL}, NULL}, false, planetmintgo_machine_TrustAnchor_init_default}
#define planetmintgo_machine_MsgRegisterTrustAnchorResponse_init_default {0}
#define planetmintgo_machine_MsgNotarizeLiquidAsset_init_default {{{NULL}, NULL}, false, planetmintgo_machine_LiquidAsset_init_default}
#define planetmintgo_machine_MsgNotarizeLiquidAssetResponse_init_default {0}
#define planetmintgo_machine_MsgAttestMachine_init_zero {{{NULL}, NULL}, false, planetmintgo_machine_Machine_init_zero}
#define planetmintgo_machine_MsgAttestMachineResponse_init_zero {0}
#define planetmintgo_machine_MsgRegisterTrustAnchor_init_zero {{{NULL}, NULL}, false, planetmintgo_machine_TrustAnchor_init_zero}
#define planetmintgo_machine_MsgRegisterTrustAnchorResponse_init_zero {0}
#define planetmintgo_machine_MsgNotarizeLiquidAsset_init_zero {{{NULL}, NULL}, false, planetmintgo_machine_LiquidAsset_init_zero}
#define planetmintgo_machine_MsgNotarizeLiquidAssetResponse_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define planetmintgo_machine_MsgAttestMachine_creator_tag 1
#define planetmintgo_machine_MsgAttestMachine_machine_tag 2
#define planetmintgo_machine_MsgRegisterTrustAnchor_creator_tag 1
#define planetmintgo_machine_MsgRegisterTrustAnchor_trustAnchor_tag 2
#define planetmintgo_machine_MsgNotarizeLiquidAsset_creator_tag 1
#define planetmintgo_machine_MsgNotarizeLiquidAsset_notarization_tag 2

/* Struct field encoding specification for nanopb */
#define planetmintgo_machine_MsgAttestMachine_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   creator,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  machine,           2)
#define planetmintgo_machine_MsgAttestMachine_CALLBACK pb_default_field_callback
#define planetmintgo_machine_MsgAttestMachine_DEFAULT NULL
#define planetmintgo_machine_MsgAttestMachine_machine_MSGTYPE planetmintgo_machine_Machine

#define planetmintgo_machine_MsgAttestMachineResponse_FIELDLIST(X, a) \

#define planetmintgo_machine_MsgAttestMachineResponse_CALLBACK NULL
#define planetmintgo_machine_MsgAttestMachineResponse_DEFAULT NULL

#define planetmintgo_machine_MsgRegisterTrustAnchor_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   creator,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  trustAnchor,       2)
#define planetmintgo_machine_MsgRegisterTrustAnchor_CALLBACK pb_default_field_callback
#define planetmintgo_machine_MsgRegisterTrustAnchor_DEFAULT NULL
#define planetmintgo_machine_MsgRegisterTrustAnchor_trustAnchor_MSGTYPE planetmintgo_machine_TrustAnchor

#define planetmintgo_machine_MsgRegisterTrustAnchorResponse_FIELDLIST(X, a) \

#define planetmintgo_machine_MsgRegisterTrustAnchorResponse_CALLBACK NULL
#define planetmintgo_machine_MsgRegisterTrustAnchorResponse_DEFAULT NULL

#define planetmintgo_machine_MsgNotarizeLiquidAsset_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   creator,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  notarization,      2)
#define planetmintgo_machine_MsgNotarizeLiquidAsset_CALLBACK pb_default_field_callback
#define planetmintgo_machine_MsgNotarizeLiquidAsset_DEFAULT NULL
#define planetmintgo_machine_MsgNotarizeLiquidAsset_notarization_MSGTYPE planetmintgo_machine_LiquidAsset

#define planetmintgo_machine_MsgNotarizeLiquidAssetResponse_FIELDLIST(X, a) \

#define planetmintgo_machine_MsgNotarizeLiquidAssetResponse_CALLBACK NULL
#define planetmintgo_machine_MsgNotarizeLiquidAssetResponse_DEFAULT NULL

extern const pb_msgdesc_t planetmintgo_machine_MsgAttestMachine_msg;
extern const pb_msgdesc_t planetmintgo_machine_MsgAttestMachineResponse_msg;
extern const pb_msgdesc_t planetmintgo_machine_MsgRegisterTrustAnchor_msg;
extern const pb_msgdesc_t planetmintgo_machine_MsgRegisterTrustAnchorResponse_msg;
extern const pb_msgdesc_t planetmintgo_machine_MsgNotarizeLiquidAsset_msg;
extern const pb_msgdesc_t planetmintgo_machine_MsgNotarizeLiquidAssetResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define planetmintgo_machine_MsgAttestMachine_fields &planetmintgo_machine_MsgAttestMachine_msg
#define planetmintgo_machine_MsgAttestMachineResponse_fields &planetmintgo_machine_MsgAttestMachineResponse_msg
#define planetmintgo_machine_MsgRegisterTrustAnchor_fields &planetmintgo_machine_MsgRegisterTrustAnchor_msg
#define planetmintgo_machine_MsgRegisterTrustAnchorResponse_fields &planetmintgo_machine_MsgRegisterTrustAnchorResponse_msg
#define planetmintgo_machine_MsgNotarizeLiquidAsset_fields &planetmintgo_machine_MsgNotarizeLiquidAsset_msg
#define planetmintgo_machine_MsgNotarizeLiquidAssetResponse_fields &planetmintgo_machine_MsgNotarizeLiquidAssetResponse_msg

/* Maximum encoded size of messages (where known) */
/* planetmintgo_machine_MsgAttestMachine_size depends on runtime parameters */
/* planetmintgo_machine_MsgRegisterTrustAnchor_size depends on runtime parameters */
/* planetmintgo_machine_MsgNotarizeLiquidAsset_size depends on runtime parameters */
#define planetmintgo_machine_MsgAttestMachineResponse_size 0
#define planetmintgo_machine_MsgNotarizeLiquidAssetResponse_size 0
#define planetmintgo_machine_MsgRegisterTrustAnchorResponse_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
