/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "cosmos/tx/signing/v1beta1/signing.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_tx_signing_v1beta1_SignatureDescriptors, cosmos_tx_signing_v1beta1_SignatureDescriptors, AUTO)


PB_BIND(cosmos_tx_signing_v1beta1_SignatureDescriptor, cosmos_tx_signing_v1beta1_SignatureDescriptor, AUTO)


PB_BIND(cosmos_tx_signing_v1beta1_SignatureDescriptor_Data, cosmos_tx_signing_v1beta1_SignatureDescriptor_Data, AUTO)


PB_BIND(cosmos_tx_signing_v1beta1_SignatureDescriptor_Data_Single, cosmos_tx_signing_v1beta1_SignatureDescriptor_Data_Single, AUTO)


PB_BIND(cosmos_tx_signing_v1beta1_SignatureDescriptor_Data_Multi, cosmos_tx_signing_v1beta1_SignatureDescriptor_Data_Multi, AUTO)




