/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "cosmos/crypto/secp256k1/keys.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_crypto_secp256k1_PubKey, cosmos_crypto_secp256k1_PubKey, AUTO)


PB_BIND(cosmos_crypto_secp256k1_PrivKey, cosmos_crypto_secp256k1_PrivKey, AUTO)



