/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_COSMOS_CRYPTO_SECP256K1_COSMOS_CRYPTO_SECP256K1_KEYS_PB_H_INCLUDED
#define PB_COSMOS_CRYPTO_SECP256K1_COSMOS_CRYPTO_SECP256K1_KEYS_PB_H_INCLUDED
#define PB_NO_STATIC_ASSERT 1 
#include <pb.h>
#include "amino/amino.pb.h"
#include "gogoproto/gogo.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* PubKey defines a secp256k1 public key
 Key is the compressed form of the pubkey. The first byte depends is a 0x02 byte
 if the y-coordinate is the lexicographically largest of the two associated with
 the x-coordinate. Otherwise the first byte is a 0x03.
 This prefix is followed with the x-coordinate. */
typedef struct _cosmos_crypto_secp256k1_PubKey {
    pb_callback_t key;
} cosmos_crypto_secp256k1_PubKey;

/* PrivKey defines a secp256k1 private key. */
typedef struct _cosmos_crypto_secp256k1_PrivKey {
    pb_callback_t key;
} cosmos_crypto_secp256k1_PrivKey;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define cosmos_crypto_secp256k1_PubKey_init_default {{{NULL}, NULL}}
#define cosmos_crypto_secp256k1_PrivKey_init_default {{{NULL}, NULL}}
#define cosmos_crypto_secp256k1_PubKey_init_zero {{{NULL}, NULL}}
#define cosmos_crypto_secp256k1_PrivKey_init_zero {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define cosmos_crypto_secp256k1_PubKey_key_tag   1
#define cosmos_crypto_secp256k1_PrivKey_key_tag  1

/* Struct field encoding specification for nanopb */
#define cosmos_crypto_secp256k1_PubKey_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    key,               1)
#define cosmos_crypto_secp256k1_PubKey_CALLBACK pb_default_field_callback
#define cosmos_crypto_secp256k1_PubKey_DEFAULT NULL

#define cosmos_crypto_secp256k1_PrivKey_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    key,               1)
#define cosmos_crypto_secp256k1_PrivKey_CALLBACK pb_default_field_callback
#define cosmos_crypto_secp256k1_PrivKey_DEFAULT NULL

extern const pb_msgdesc_t cosmos_crypto_secp256k1_PubKey_msg;
extern const pb_msgdesc_t cosmos_crypto_secp256k1_PrivKey_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define cosmos_crypto_secp256k1_PubKey_fields &cosmos_crypto_secp256k1_PubKey_msg
#define cosmos_crypto_secp256k1_PrivKey_fields &cosmos_crypto_secp256k1_PrivKey_msg

/* Maximum encoded size of messages (where known) */
/* cosmos_crypto_secp256k1_PubKey_size depends on runtime parameters */
/* cosmos_crypto_secp256k1_PrivKey_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
