/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: planetmintgo/machine/liquid_asset.proto */

#ifndef PROTOBUF_C_planetmintgo_2fmachine_2fliquid_5fasset_2eproto__INCLUDED
#define PROTOBUF_C_planetmintgo_2fmachine_2fliquid_5fasset_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Planetmintgo__Machine__LiquidAsset Planetmintgo__Machine__LiquidAsset;


/* --- enums --- */


/* --- messages --- */

struct  Planetmintgo__Machine__LiquidAsset
{
  ProtobufCMessage base;
  char *machineid;
  char *machineaddress;
  char *assetid;
  protobuf_c_boolean registered;
};
#define PLANETMINTGO__MACHINE__LIQUID_ASSET__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__machine__liquid_asset__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


/* Planetmintgo__Machine__LiquidAsset methods */
void   planetmintgo__machine__liquid_asset__init
                     (Planetmintgo__Machine__LiquidAsset         *message);
size_t planetmintgo__machine__liquid_asset__get_packed_size
                     (const Planetmintgo__Machine__LiquidAsset   *message);
size_t planetmintgo__machine__liquid_asset__pack
                     (const Planetmintgo__Machine__LiquidAsset   *message,
                      uint8_t             *out);
size_t planetmintgo__machine__liquid_asset__pack_to_buffer
                     (const Planetmintgo__Machine__LiquidAsset   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Machine__LiquidAsset *
       planetmintgo__machine__liquid_asset__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__machine__liquid_asset__free_unpacked
                     (Planetmintgo__Machine__LiquidAsset *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Planetmintgo__Machine__LiquidAsset_Closure)
                 (const Planetmintgo__Machine__LiquidAsset *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor planetmintgo__machine__liquid_asset__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_planetmintgo_2fmachine_2fliquid_5fasset_2eproto__INCLUDED */
