/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: planetmintgo/dao/mint_request.proto */

#ifndef PROTOBUF_C_planetmintgo_2fdao_2fmint_5frequest_2eproto__INCLUDED
#define PROTOBUF_C_planetmintgo_2fdao_2fmint_5frequest_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Planetmintgo__Dao__MintRequest Planetmintgo__Dao__MintRequest;


/* --- enums --- */


/* --- messages --- */

struct  Planetmintgo__Dao__MintRequest
{
  ProtobufCMessage base;
  char *beneficiary;
  uint64_t amount;
  char *liquidtxhash;
};
#define PLANETMINTGO__DAO__MINT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__mint_request__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string }


/* Planetmintgo__Dao__MintRequest methods */
void   planetmintgo__dao__mint_request__init
                     (Planetmintgo__Dao__MintRequest         *message);
size_t planetmintgo__dao__mint_request__get_packed_size
                     (const Planetmintgo__Dao__MintRequest   *message);
size_t planetmintgo__dao__mint_request__pack
                     (const Planetmintgo__Dao__MintRequest   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__mint_request__pack_to_buffer
                     (const Planetmintgo__Dao__MintRequest   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MintRequest *
       planetmintgo__dao__mint_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__mint_request__free_unpacked
                     (Planetmintgo__Dao__MintRequest *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Planetmintgo__Dao__MintRequest_Closure)
                 (const Planetmintgo__Dao__MintRequest *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor planetmintgo__dao__mint_request__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_planetmintgo_2fdao_2fmint_5frequest_2eproto__INCLUDED */
