/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: planetmintgo/dao/params.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "planetmintgo/dao/params.pb-c.h"
void   planetmintgo__dao__params__init
                     (Planetmintgo__Dao__Params         *message)
{
  static const Planetmintgo__Dao__Params init_value = PLANETMINTGO__DAO__PARAMS__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__params__get_packed_size
                     (const Planetmintgo__Dao__Params *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__params__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__params__pack
                     (const Planetmintgo__Dao__Params *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__params__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__params__pack_to_buffer
                     (const Planetmintgo__Dao__Params *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__params__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__Params *
       planetmintgo__dao__params__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__Params *)
     protobuf_c_message_unpack (&planetmintgo__dao__params__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__params__free_unpacked
                     (Planetmintgo__Dao__Params *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__params__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor planetmintgo__dao__params__field_descriptors[1] =
{
  {
    "mint_address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__Params, mint_address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__params__field_indices_by_name[] = {
  0,   /* field[0] = mint_address */
};
static const ProtobufCIntRange planetmintgo__dao__params__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__params__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.Params",
  "Params",
  "Planetmintgo__Dao__Params",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__Params),
  1,
  planetmintgo__dao__params__field_descriptors,
  planetmintgo__dao__params__field_indices_by_name,
  1,  planetmintgo__dao__params__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__params__init,
  NULL,NULL,NULL    /* reserved[123] */
};
