/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: planetmintgo/dao/query.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "planetmintgo/dao/query.pb-c.h"
void   planetmintgo__dao__query_params_request__init
                     (Planetmintgo__Dao__QueryParamsRequest         *message)
{
  static const Planetmintgo__Dao__QueryParamsRequest init_value = PLANETMINTGO__DAO__QUERY_PARAMS_REQUEST__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_params_request__get_packed_size
                     (const Planetmintgo__Dao__QueryParamsRequest *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_params_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_params_request__pack
                     (const Planetmintgo__Dao__QueryParamsRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_params_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_params_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryParamsRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_params_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryParamsRequest *
       planetmintgo__dao__query_params_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryParamsRequest *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_params_request__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_params_request__free_unpacked
                     (Planetmintgo__Dao__QueryParamsRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_params_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_params_response__init
                     (Planetmintgo__Dao__QueryParamsResponse         *message)
{
  static const Planetmintgo__Dao__QueryParamsResponse init_value = PLANETMINTGO__DAO__QUERY_PARAMS_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_params_response__get_packed_size
                     (const Planetmintgo__Dao__QueryParamsResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_params_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_params_response__pack
                     (const Planetmintgo__Dao__QueryParamsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_params_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_params_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryParamsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_params_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryParamsResponse *
       planetmintgo__dao__query_params_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryParamsResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_params_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_params_response__free_unpacked
                     (Planetmintgo__Dao__QueryParamsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_params_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_get_mint_requests_by_hash_request__init
                     (Planetmintgo__Dao__QueryGetMintRequestsByHashRequest         *message)
{
  static const Planetmintgo__Dao__QueryGetMintRequestsByHashRequest init_value = PLANETMINTGO__DAO__QUERY_GET_MINT_REQUESTS_BY_HASH_REQUEST__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_get_mint_requests_by_hash_request__get_packed_size
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_mint_requests_by_hash_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_get_mint_requests_by_hash_request__pack
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_mint_requests_by_hash_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_get_mint_requests_by_hash_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_mint_requests_by_hash_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *
       planetmintgo__dao__query_get_mint_requests_by_hash_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_get_mint_requests_by_hash_request__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_get_mint_requests_by_hash_request__free_unpacked
                     (Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_get_mint_requests_by_hash_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_get_mint_requests_by_hash_response__init
                     (Planetmintgo__Dao__QueryGetMintRequestsByHashResponse         *message)
{
  static const Planetmintgo__Dao__QueryGetMintRequestsByHashResponse init_value = PLANETMINTGO__DAO__QUERY_GET_MINT_REQUESTS_BY_HASH_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_get_mint_requests_by_hash_response__get_packed_size
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_mint_requests_by_hash_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_get_mint_requests_by_hash_response__pack
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_mint_requests_by_hash_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_get_mint_requests_by_hash_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_mint_requests_by_hash_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryGetMintRequestsByHashResponse *
       planetmintgo__dao__query_get_mint_requests_by_hash_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryGetMintRequestsByHashResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_get_mint_requests_by_hash_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_get_mint_requests_by_hash_response__free_unpacked
                     (Planetmintgo__Dao__QueryGetMintRequestsByHashResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_get_mint_requests_by_hash_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_mint_requests_by_address_request__init
                     (Planetmintgo__Dao__QueryMintRequestsByAddressRequest         *message)
{
  static const Planetmintgo__Dao__QueryMintRequestsByAddressRequest init_value = PLANETMINTGO__DAO__QUERY_MINT_REQUESTS_BY_ADDRESS_REQUEST__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_mint_requests_by_address_request__get_packed_size
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressRequest *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_mint_requests_by_address_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_mint_requests_by_address_request__pack
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_mint_requests_by_address_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_mint_requests_by_address_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_mint_requests_by_address_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryMintRequestsByAddressRequest *
       planetmintgo__dao__query_mint_requests_by_address_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryMintRequestsByAddressRequest *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_mint_requests_by_address_request__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_mint_requests_by_address_request__free_unpacked
                     (Planetmintgo__Dao__QueryMintRequestsByAddressRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_mint_requests_by_address_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_mint_requests_by_address_response__init
                     (Planetmintgo__Dao__QueryMintRequestsByAddressResponse         *message)
{
  static const Planetmintgo__Dao__QueryMintRequestsByAddressResponse init_value = PLANETMINTGO__DAO__QUERY_MINT_REQUESTS_BY_ADDRESS_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_mint_requests_by_address_response__get_packed_size
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_mint_requests_by_address_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_mint_requests_by_address_response__pack
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_mint_requests_by_address_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_mint_requests_by_address_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_mint_requests_by_address_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryMintRequestsByAddressResponse *
       planetmintgo__dao__query_mint_requests_by_address_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryMintRequestsByAddressResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_mint_requests_by_address_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_mint_requests_by_address_response__free_unpacked
                     (Planetmintgo__Dao__QueryMintRequestsByAddressResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_mint_requests_by_address_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_get_reissuance_request__init
                     (Planetmintgo__Dao__QueryGetReissuanceRequest         *message)
{
  static const Planetmintgo__Dao__QueryGetReissuanceRequest init_value = PLANETMINTGO__DAO__QUERY_GET_REISSUANCE_REQUEST__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_get_reissuance_request__get_packed_size
                     (const Planetmintgo__Dao__QueryGetReissuanceRequest *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_reissuance_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_get_reissuance_request__pack
                     (const Planetmintgo__Dao__QueryGetReissuanceRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_reissuance_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_get_reissuance_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetReissuanceRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_reissuance_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryGetReissuanceRequest *
       planetmintgo__dao__query_get_reissuance_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryGetReissuanceRequest *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_get_reissuance_request__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_get_reissuance_request__free_unpacked
                     (Planetmintgo__Dao__QueryGetReissuanceRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_get_reissuance_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_get_reissuance_response__init
                     (Planetmintgo__Dao__QueryGetReissuanceResponse         *message)
{
  static const Planetmintgo__Dao__QueryGetReissuanceResponse init_value = PLANETMINTGO__DAO__QUERY_GET_REISSUANCE_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_get_reissuance_response__get_packed_size
                     (const Planetmintgo__Dao__QueryGetReissuanceResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_reissuance_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_get_reissuance_response__pack
                     (const Planetmintgo__Dao__QueryGetReissuanceResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_reissuance_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_get_reissuance_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetReissuanceResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_reissuance_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryGetReissuanceResponse *
       planetmintgo__dao__query_get_reissuance_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryGetReissuanceResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_get_reissuance_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_get_reissuance_response__free_unpacked
                     (Planetmintgo__Dao__QueryGetReissuanceResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_get_reissuance_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_reissuances_request__init
                     (Planetmintgo__Dao__QueryReissuancesRequest         *message)
{
  static const Planetmintgo__Dao__QueryReissuancesRequest init_value = PLANETMINTGO__DAO__QUERY_REISSUANCES_REQUEST__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_reissuances_request__get_packed_size
                     (const Planetmintgo__Dao__QueryReissuancesRequest *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_reissuances_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_reissuances_request__pack
                     (const Planetmintgo__Dao__QueryReissuancesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_reissuances_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_reissuances_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryReissuancesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_reissuances_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryReissuancesRequest *
       planetmintgo__dao__query_reissuances_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryReissuancesRequest *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_reissuances_request__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_reissuances_request__free_unpacked
                     (Planetmintgo__Dao__QueryReissuancesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_reissuances_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_reissuances_response__init
                     (Planetmintgo__Dao__QueryReissuancesResponse         *message)
{
  static const Planetmintgo__Dao__QueryReissuancesResponse init_value = PLANETMINTGO__DAO__QUERY_REISSUANCES_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_reissuances_response__get_packed_size
                     (const Planetmintgo__Dao__QueryReissuancesResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_reissuances_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_reissuances_response__pack
                     (const Planetmintgo__Dao__QueryReissuancesResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_reissuances_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_reissuances_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryReissuancesResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_reissuances_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryReissuancesResponse *
       planetmintgo__dao__query_reissuances_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryReissuancesResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_reissuances_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_reissuances_response__free_unpacked
                     (Planetmintgo__Dao__QueryReissuancesResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_reissuances_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_get_challenge_request__init
                     (Planetmintgo__Dao__QueryGetChallengeRequest         *message)
{
  static const Planetmintgo__Dao__QueryGetChallengeRequest init_value = PLANETMINTGO__DAO__QUERY_GET_CHALLENGE_REQUEST__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_get_challenge_request__get_packed_size
                     (const Planetmintgo__Dao__QueryGetChallengeRequest *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_challenge_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_get_challenge_request__pack
                     (const Planetmintgo__Dao__QueryGetChallengeRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_challenge_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_get_challenge_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetChallengeRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_challenge_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryGetChallengeRequest *
       planetmintgo__dao__query_get_challenge_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryGetChallengeRequest *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_get_challenge_request__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_get_challenge_request__free_unpacked
                     (Planetmintgo__Dao__QueryGetChallengeRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_get_challenge_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_get_challenge_response__init
                     (Planetmintgo__Dao__QueryGetChallengeResponse         *message)
{
  static const Planetmintgo__Dao__QueryGetChallengeResponse init_value = PLANETMINTGO__DAO__QUERY_GET_CHALLENGE_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_get_challenge_response__get_packed_size
                     (const Planetmintgo__Dao__QueryGetChallengeResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_challenge_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_get_challenge_response__pack
                     (const Planetmintgo__Dao__QueryGetChallengeResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_challenge_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_get_challenge_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetChallengeResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_challenge_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryGetChallengeResponse *
       planetmintgo__dao__query_get_challenge_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryGetChallengeResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_get_challenge_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_get_challenge_response__free_unpacked
                     (Planetmintgo__Dao__QueryGetChallengeResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_get_challenge_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_challenges_request__init
                     (Planetmintgo__Dao__QueryChallengesRequest         *message)
{
  static const Planetmintgo__Dao__QueryChallengesRequest init_value = PLANETMINTGO__DAO__QUERY_CHALLENGES_REQUEST__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_challenges_request__get_packed_size
                     (const Planetmintgo__Dao__QueryChallengesRequest *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_challenges_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_challenges_request__pack
                     (const Planetmintgo__Dao__QueryChallengesRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_challenges_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_challenges_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryChallengesRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_challenges_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryChallengesRequest *
       planetmintgo__dao__query_challenges_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryChallengesRequest *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_challenges_request__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_challenges_request__free_unpacked
                     (Planetmintgo__Dao__QueryChallengesRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_challenges_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_challenges_response__init
                     (Planetmintgo__Dao__QueryChallengesResponse         *message)
{
  static const Planetmintgo__Dao__QueryChallengesResponse init_value = PLANETMINTGO__DAO__QUERY_CHALLENGES_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_challenges_response__get_packed_size
                     (const Planetmintgo__Dao__QueryChallengesResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_challenges_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_challenges_response__pack
                     (const Planetmintgo__Dao__QueryChallengesResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_challenges_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_challenges_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryChallengesResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_challenges_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryChallengesResponse *
       planetmintgo__dao__query_challenges_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryChallengesResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_challenges_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_challenges_response__free_unpacked
                     (Planetmintgo__Dao__QueryChallengesResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_challenges_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_get_distribution_request__init
                     (Planetmintgo__Dao__QueryGetDistributionRequest         *message)
{
  static const Planetmintgo__Dao__QueryGetDistributionRequest init_value = PLANETMINTGO__DAO__QUERY_GET_DISTRIBUTION_REQUEST__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_get_distribution_request__get_packed_size
                     (const Planetmintgo__Dao__QueryGetDistributionRequest *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_distribution_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_get_distribution_request__pack
                     (const Planetmintgo__Dao__QueryGetDistributionRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_distribution_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_get_distribution_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetDistributionRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_distribution_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryGetDistributionRequest *
       planetmintgo__dao__query_get_distribution_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryGetDistributionRequest *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_get_distribution_request__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_get_distribution_request__free_unpacked
                     (Planetmintgo__Dao__QueryGetDistributionRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_get_distribution_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__query_get_distribution_response__init
                     (Planetmintgo__Dao__QueryGetDistributionResponse         *message)
{
  static const Planetmintgo__Dao__QueryGetDistributionResponse init_value = PLANETMINTGO__DAO__QUERY_GET_DISTRIBUTION_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__query_get_distribution_response__get_packed_size
                     (const Planetmintgo__Dao__QueryGetDistributionResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_distribution_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__query_get_distribution_response__pack
                     (const Planetmintgo__Dao__QueryGetDistributionResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_distribution_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__query_get_distribution_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetDistributionResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__query_get_distribution_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__QueryGetDistributionResponse *
       planetmintgo__dao__query_get_distribution_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__QueryGetDistributionResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__query_get_distribution_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__query_get_distribution_response__free_unpacked
                     (Planetmintgo__Dao__QueryGetDistributionResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__query_get_distribution_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
#define planetmintgo__dao__query_params_request__field_descriptors NULL
#define planetmintgo__dao__query_params_request__field_indices_by_name NULL
#define planetmintgo__dao__query_params_request__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__query_params_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryParamsRequest",
  "QueryParamsRequest",
  "Planetmintgo__Dao__QueryParamsRequest",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryParamsRequest),
  0,
  planetmintgo__dao__query_params_request__field_descriptors,
  planetmintgo__dao__query_params_request__field_indices_by_name,
  0,  planetmintgo__dao__query_params_request__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_params_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_params_response__field_descriptors[1] =
{
  {
    "params",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryParamsResponse, params),
    &planetmintgo__dao__params__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_params_response__field_indices_by_name[] = {
  0,   /* field[0] = params */
};
static const ProtobufCIntRange planetmintgo__dao__query_params_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_params_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryParamsResponse",
  "QueryParamsResponse",
  "Planetmintgo__Dao__QueryParamsResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryParamsResponse),
  1,
  planetmintgo__dao__query_params_response__field_descriptors,
  planetmintgo__dao__query_params_response__field_indices_by_name,
  1,  planetmintgo__dao__query_params_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_params_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_get_mint_requests_by_hash_request__field_descriptors[1] =
{
  {
    "hash",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryGetMintRequestsByHashRequest, hash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_get_mint_requests_by_hash_request__field_indices_by_name[] = {
  0,   /* field[0] = hash */
};
static const ProtobufCIntRange planetmintgo__dao__query_get_mint_requests_by_hash_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_get_mint_requests_by_hash_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryGetMintRequestsByHashRequest",
  "QueryGetMintRequestsByHashRequest",
  "Planetmintgo__Dao__QueryGetMintRequestsByHashRequest",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryGetMintRequestsByHashRequest),
  1,
  planetmintgo__dao__query_get_mint_requests_by_hash_request__field_descriptors,
  planetmintgo__dao__query_get_mint_requests_by_hash_request__field_indices_by_name,
  1,  planetmintgo__dao__query_get_mint_requests_by_hash_request__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_get_mint_requests_by_hash_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_get_mint_requests_by_hash_response__field_descriptors[1] =
{
  {
    "mintRequest",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryGetMintRequestsByHashResponse, mintrequest),
    &planetmintgo__dao__mint_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_get_mint_requests_by_hash_response__field_indices_by_name[] = {
  0,   /* field[0] = mintRequest */
};
static const ProtobufCIntRange planetmintgo__dao__query_get_mint_requests_by_hash_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_get_mint_requests_by_hash_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryGetMintRequestsByHashResponse",
  "QueryGetMintRequestsByHashResponse",
  "Planetmintgo__Dao__QueryGetMintRequestsByHashResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryGetMintRequestsByHashResponse),
  1,
  planetmintgo__dao__query_get_mint_requests_by_hash_response__field_descriptors,
  planetmintgo__dao__query_get_mint_requests_by_hash_response__field_indices_by_name,
  1,  planetmintgo__dao__query_get_mint_requests_by_hash_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_get_mint_requests_by_hash_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_mint_requests_by_address_request__field_descriptors[1] =
{
  {
    "address",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryMintRequestsByAddressRequest, address),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_mint_requests_by_address_request__field_indices_by_name[] = {
  0,   /* field[0] = address */
};
static const ProtobufCIntRange planetmintgo__dao__query_mint_requests_by_address_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_mint_requests_by_address_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryMintRequestsByAddressRequest",
  "QueryMintRequestsByAddressRequest",
  "Planetmintgo__Dao__QueryMintRequestsByAddressRequest",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryMintRequestsByAddressRequest),
  1,
  planetmintgo__dao__query_mint_requests_by_address_request__field_descriptors,
  planetmintgo__dao__query_mint_requests_by_address_request__field_indices_by_name,
  1,  planetmintgo__dao__query_mint_requests_by_address_request__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_mint_requests_by_address_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_mint_requests_by_address_response__field_descriptors[1] =
{
  {
    "mintRequests",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryMintRequestsByAddressResponse, mintrequests),
    &planetmintgo__dao__mint_requests__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_mint_requests_by_address_response__field_indices_by_name[] = {
  0,   /* field[0] = mintRequests */
};
static const ProtobufCIntRange planetmintgo__dao__query_mint_requests_by_address_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_mint_requests_by_address_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryMintRequestsByAddressResponse",
  "QueryMintRequestsByAddressResponse",
  "Planetmintgo__Dao__QueryMintRequestsByAddressResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryMintRequestsByAddressResponse),
  1,
  planetmintgo__dao__query_mint_requests_by_address_response__field_descriptors,
  planetmintgo__dao__query_mint_requests_by_address_response__field_indices_by_name,
  1,  planetmintgo__dao__query_mint_requests_by_address_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_mint_requests_by_address_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_get_reissuance_request__field_descriptors[1] =
{
  {
    "blockHeight",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryGetReissuanceRequest, blockheight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_get_reissuance_request__field_indices_by_name[] = {
  0,   /* field[0] = blockHeight */
};
static const ProtobufCIntRange planetmintgo__dao__query_get_reissuance_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_get_reissuance_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryGetReissuanceRequest",
  "QueryGetReissuanceRequest",
  "Planetmintgo__Dao__QueryGetReissuanceRequest",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryGetReissuanceRequest),
  1,
  planetmintgo__dao__query_get_reissuance_request__field_descriptors,
  planetmintgo__dao__query_get_reissuance_request__field_indices_by_name,
  1,  planetmintgo__dao__query_get_reissuance_request__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_get_reissuance_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_get_reissuance_response__field_descriptors[1] =
{
  {
    "reissuance",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryGetReissuanceResponse, reissuance),
    &planetmintgo__dao__reissuance__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_get_reissuance_response__field_indices_by_name[] = {
  0,   /* field[0] = reissuance */
};
static const ProtobufCIntRange planetmintgo__dao__query_get_reissuance_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_get_reissuance_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryGetReissuanceResponse",
  "QueryGetReissuanceResponse",
  "Planetmintgo__Dao__QueryGetReissuanceResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryGetReissuanceResponse),
  1,
  planetmintgo__dao__query_get_reissuance_response__field_descriptors,
  planetmintgo__dao__query_get_reissuance_response__field_indices_by_name,
  1,  planetmintgo__dao__query_get_reissuance_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_get_reissuance_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_reissuances_request__field_descriptors[1] =
{
  {
    "pagination",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryReissuancesRequest, pagination),
    &cosmos__base__query__v1beta1__page_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_reissuances_request__field_indices_by_name[] = {
  0,   /* field[0] = pagination */
};
static const ProtobufCIntRange planetmintgo__dao__query_reissuances_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_reissuances_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryReissuancesRequest",
  "QueryReissuancesRequest",
  "Planetmintgo__Dao__QueryReissuancesRequest",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryReissuancesRequest),
  1,
  planetmintgo__dao__query_reissuances_request__field_descriptors,
  planetmintgo__dao__query_reissuances_request__field_indices_by_name,
  1,  planetmintgo__dao__query_reissuances_request__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_reissuances_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_reissuances_response__field_descriptors[2] =
{
  {
    "reissuances",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Planetmintgo__Dao__QueryReissuancesResponse, n_reissuances),
    offsetof(Planetmintgo__Dao__QueryReissuancesResponse, reissuances),
    &planetmintgo__dao__reissuance__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pagination",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryReissuancesResponse, pagination),
    &cosmos__base__query__v1beta1__page_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_reissuances_response__field_indices_by_name[] = {
  1,   /* field[1] = pagination */
  0,   /* field[0] = reissuances */
};
static const ProtobufCIntRange planetmintgo__dao__query_reissuances_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_reissuances_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryReissuancesResponse",
  "QueryReissuancesResponse",
  "Planetmintgo__Dao__QueryReissuancesResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryReissuancesResponse),
  2,
  planetmintgo__dao__query_reissuances_response__field_descriptors,
  planetmintgo__dao__query_reissuances_response__field_indices_by_name,
  1,  planetmintgo__dao__query_reissuances_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_reissuances_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_get_challenge_request__field_descriptors[1] =
{
  {
    "height",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryGetChallengeRequest, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_get_challenge_request__field_indices_by_name[] = {
  0,   /* field[0] = height */
};
static const ProtobufCIntRange planetmintgo__dao__query_get_challenge_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_get_challenge_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryGetChallengeRequest",
  "QueryGetChallengeRequest",
  "Planetmintgo__Dao__QueryGetChallengeRequest",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryGetChallengeRequest),
  1,
  planetmintgo__dao__query_get_challenge_request__field_descriptors,
  planetmintgo__dao__query_get_challenge_request__field_indices_by_name,
  1,  planetmintgo__dao__query_get_challenge_request__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_get_challenge_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_get_challenge_response__field_descriptors[1] =
{
  {
    "challenge",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryGetChallengeResponse, challenge),
    &planetmintgo__dao__challenge__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_get_challenge_response__field_indices_by_name[] = {
  0,   /* field[0] = challenge */
};
static const ProtobufCIntRange planetmintgo__dao__query_get_challenge_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_get_challenge_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryGetChallengeResponse",
  "QueryGetChallengeResponse",
  "Planetmintgo__Dao__QueryGetChallengeResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryGetChallengeResponse),
  1,
  planetmintgo__dao__query_get_challenge_response__field_descriptors,
  planetmintgo__dao__query_get_challenge_response__field_indices_by_name,
  1,  planetmintgo__dao__query_get_challenge_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_get_challenge_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_challenges_request__field_descriptors[1] =
{
  {
    "pagination",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryChallengesRequest, pagination),
    &cosmos__base__query__v1beta1__page_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_challenges_request__field_indices_by_name[] = {
  0,   /* field[0] = pagination */
};
static const ProtobufCIntRange planetmintgo__dao__query_challenges_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_challenges_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryChallengesRequest",
  "QueryChallengesRequest",
  "Planetmintgo__Dao__QueryChallengesRequest",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryChallengesRequest),
  1,
  planetmintgo__dao__query_challenges_request__field_descriptors,
  planetmintgo__dao__query_challenges_request__field_indices_by_name,
  1,  planetmintgo__dao__query_challenges_request__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_challenges_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_challenges_response__field_descriptors[2] =
{
  {
    "challenges",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Planetmintgo__Dao__QueryChallengesResponse, n_challenges),
    offsetof(Planetmintgo__Dao__QueryChallengesResponse, challenges),
    &planetmintgo__dao__challenge__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pagination",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryChallengesResponse, pagination),
    &cosmos__base__query__v1beta1__page_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_challenges_response__field_indices_by_name[] = {
  0,   /* field[0] = challenges */
  1,   /* field[1] = pagination */
};
static const ProtobufCIntRange planetmintgo__dao__query_challenges_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_challenges_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryChallengesResponse",
  "QueryChallengesResponse",
  "Planetmintgo__Dao__QueryChallengesResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryChallengesResponse),
  2,
  planetmintgo__dao__query_challenges_response__field_descriptors,
  planetmintgo__dao__query_challenges_response__field_indices_by_name,
  1,  planetmintgo__dao__query_challenges_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_challenges_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_get_distribution_request__field_descriptors[1] =
{
  {
    "lastPopHeight",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryGetDistributionRequest, lastpopheight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_get_distribution_request__field_indices_by_name[] = {
  0,   /* field[0] = lastPopHeight */
};
static const ProtobufCIntRange planetmintgo__dao__query_get_distribution_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_get_distribution_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryGetDistributionRequest",
  "QueryGetDistributionRequest",
  "Planetmintgo__Dao__QueryGetDistributionRequest",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryGetDistributionRequest),
  1,
  planetmintgo__dao__query_get_distribution_request__field_descriptors,
  planetmintgo__dao__query_get_distribution_request__field_indices_by_name,
  1,  planetmintgo__dao__query_get_distribution_request__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_get_distribution_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__query_get_distribution_response__field_descriptors[1] =
{
  {
    "distribution",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__QueryGetDistributionResponse, distribution),
    &planetmintgo__dao__distribution_order__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__query_get_distribution_response__field_indices_by_name[] = {
  0,   /* field[0] = distribution */
};
static const ProtobufCIntRange planetmintgo__dao__query_get_distribution_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__query_get_distribution_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.QueryGetDistributionResponse",
  "QueryGetDistributionResponse",
  "Planetmintgo__Dao__QueryGetDistributionResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__QueryGetDistributionResponse),
  1,
  planetmintgo__dao__query_get_distribution_response__field_descriptors,
  planetmintgo__dao__query_get_distribution_response__field_indices_by_name,
  1,  planetmintgo__dao__query_get_distribution_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__query_get_distribution_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor planetmintgo__dao__query__method_descriptors[8] =
{
  { "Params", &planetmintgo__dao__query_params_request__descriptor, &planetmintgo__dao__query_params_response__descriptor },
  { "GetMintRequestsByHash", &planetmintgo__dao__query_get_mint_requests_by_hash_request__descriptor, &planetmintgo__dao__query_get_mint_requests_by_hash_response__descriptor },
  { "MintRequestsByAddress", &planetmintgo__dao__query_mint_requests_by_address_request__descriptor, &planetmintgo__dao__query_mint_requests_by_address_response__descriptor },
  { "GetReissuance", &planetmintgo__dao__query_get_reissuance_request__descriptor, &planetmintgo__dao__query_get_reissuance_response__descriptor },
  { "Reissuances", &planetmintgo__dao__query_reissuances_request__descriptor, &planetmintgo__dao__query_reissuances_response__descriptor },
  { "GetChallenge", &planetmintgo__dao__query_get_challenge_request__descriptor, &planetmintgo__dao__query_get_challenge_response__descriptor },
  { "Challenges", &planetmintgo__dao__query_challenges_request__descriptor, &planetmintgo__dao__query_challenges_response__descriptor },
  { "GetDistribution", &planetmintgo__dao__query_get_distribution_request__descriptor, &planetmintgo__dao__query_get_distribution_response__descriptor },
};
const unsigned planetmintgo__dao__query__method_indices_by_name[] = {
  6,        /* Challenges */
  5,        /* GetChallenge */
  7,        /* GetDistribution */
  1,        /* GetMintRequestsByHash */
  3,        /* GetReissuance */
  2,        /* MintRequestsByAddress */
  0,        /* Params */
  4         /* Reissuances */
};
const ProtobufCServiceDescriptor planetmintgo__dao__query__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.Query",
  "Query",
  "Planetmintgo__Dao__Query",
  "planetmintgo.dao",
  8,
  planetmintgo__dao__query__method_descriptors,
  planetmintgo__dao__query__method_indices_by_name
};
void planetmintgo__dao__query__params(ProtobufCService *service,
                                      const Planetmintgo__Dao__QueryParamsRequest *input,
                                      Planetmintgo__Dao__QueryParamsResponse_Closure closure,
                                      void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__query__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__query__get_mint_requests_by_hash(ProtobufCService *service,
                                                         const Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *input,
                                                         Planetmintgo__Dao__QueryGetMintRequestsByHashResponse_Closure closure,
                                                         void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__query__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__query__mint_requests_by_address(ProtobufCService *service,
                                                        const Planetmintgo__Dao__QueryMintRequestsByAddressRequest *input,
                                                        Planetmintgo__Dao__QueryMintRequestsByAddressResponse_Closure closure,
                                                        void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__query__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__query__get_reissuance(ProtobufCService *service,
                                              const Planetmintgo__Dao__QueryGetReissuanceRequest *input,
                                              Planetmintgo__Dao__QueryGetReissuanceResponse_Closure closure,
                                              void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__query__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__query__reissuances(ProtobufCService *service,
                                           const Planetmintgo__Dao__QueryReissuancesRequest *input,
                                           Planetmintgo__Dao__QueryReissuancesResponse_Closure closure,
                                           void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__query__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__query__get_challenge(ProtobufCService *service,
                                             const Planetmintgo__Dao__QueryGetChallengeRequest *input,
                                             Planetmintgo__Dao__QueryGetChallengeResponse_Closure closure,
                                             void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__query__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__query__challenges(ProtobufCService *service,
                                          const Planetmintgo__Dao__QueryChallengesRequest *input,
                                          Planetmintgo__Dao__QueryChallengesResponse_Closure closure,
                                          void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__query__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__query__get_distribution(ProtobufCService *service,
                                                const Planetmintgo__Dao__QueryGetDistributionRequest *input,
                                                Planetmintgo__Dao__QueryGetDistributionResponse_Closure closure,
                                                void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__query__descriptor);
  service->invoke(service, 7, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__query__init (Planetmintgo__Dao__Query_Service *service,
                                     Planetmintgo__Dao__Query_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &planetmintgo__dao__query__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
