/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: planetmintgo/dao/query.proto */

#ifndef PROTOBUF_C_planetmintgo_2fdao_2fquery_2eproto__INCLUDED
#define PROTOBUF_C_planetmintgo_2fdao_2fquery_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "gogoproto/gogo.pb-c.h"
#include "google/api/annotations.pb-c.h"
#include "cosmos/base/query/v1beta1/pagination.pb-c.h"
#include "planetmintgo/dao/params.pb-c.h"
#include "planetmintgo/dao/mint_request.pb-c.h"
#include "planetmintgo/dao/mint_requests.pb-c.h"
#include "planetmintgo/dao/reissuance.pb-c.h"
#include "planetmintgo/dao/challenge.pb-c.h"
#include "amino/amino.pb-c.h"
#include "planetmintgo/dao/distribution_order.pb-c.h"

typedef struct Planetmintgo__Dao__QueryParamsRequest Planetmintgo__Dao__QueryParamsRequest;
typedef struct Planetmintgo__Dao__QueryParamsResponse Planetmintgo__Dao__QueryParamsResponse;
typedef struct Planetmintgo__Dao__QueryGetMintRequestsByHashRequest Planetmintgo__Dao__QueryGetMintRequestsByHashRequest;
typedef struct Planetmintgo__Dao__QueryGetMintRequestsByHashResponse Planetmintgo__Dao__QueryGetMintRequestsByHashResponse;
typedef struct Planetmintgo__Dao__QueryMintRequestsByAddressRequest Planetmintgo__Dao__QueryMintRequestsByAddressRequest;
typedef struct Planetmintgo__Dao__QueryMintRequestsByAddressResponse Planetmintgo__Dao__QueryMintRequestsByAddressResponse;
typedef struct Planetmintgo__Dao__QueryGetReissuanceRequest Planetmintgo__Dao__QueryGetReissuanceRequest;
typedef struct Planetmintgo__Dao__QueryGetReissuanceResponse Planetmintgo__Dao__QueryGetReissuanceResponse;
typedef struct Planetmintgo__Dao__QueryReissuancesRequest Planetmintgo__Dao__QueryReissuancesRequest;
typedef struct Planetmintgo__Dao__QueryReissuancesResponse Planetmintgo__Dao__QueryReissuancesResponse;
typedef struct Planetmintgo__Dao__QueryGetChallengeRequest Planetmintgo__Dao__QueryGetChallengeRequest;
typedef struct Planetmintgo__Dao__QueryGetChallengeResponse Planetmintgo__Dao__QueryGetChallengeResponse;
typedef struct Planetmintgo__Dao__QueryChallengesRequest Planetmintgo__Dao__QueryChallengesRequest;
typedef struct Planetmintgo__Dao__QueryChallengesResponse Planetmintgo__Dao__QueryChallengesResponse;
typedef struct Planetmintgo__Dao__QueryGetDistributionRequest Planetmintgo__Dao__QueryGetDistributionRequest;
typedef struct Planetmintgo__Dao__QueryGetDistributionResponse Planetmintgo__Dao__QueryGetDistributionResponse;


/* --- enums --- */


/* --- messages --- */

/*
 * QueryParamsRequest is request type for the Query/Params RPC method.
 */
struct  Planetmintgo__Dao__QueryParamsRequest
{
  ProtobufCMessage base;
};
#define PLANETMINTGO__DAO__QUERY_PARAMS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_params_request__descriptor) \
     }


/*
 * QueryParamsResponse is response type for the Query/Params RPC method.
 */
struct  Planetmintgo__Dao__QueryParamsResponse
{
  ProtobufCMessage base;
  /*
   * params holds all the parameters of this module.
   */
  Planetmintgo__Dao__Params *params;
};
#define PLANETMINTGO__DAO__QUERY_PARAMS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_params_response__descriptor) \
    , NULL }


struct  Planetmintgo__Dao__QueryGetMintRequestsByHashRequest
{
  ProtobufCMessage base;
  char *hash;
};
#define PLANETMINTGO__DAO__QUERY_GET_MINT_REQUESTS_BY_HASH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_get_mint_requests_by_hash_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  Planetmintgo__Dao__QueryGetMintRequestsByHashResponse
{
  ProtobufCMessage base;
  Planetmintgo__Dao__MintRequest *mintrequest;
};
#define PLANETMINTGO__DAO__QUERY_GET_MINT_REQUESTS_BY_HASH_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_get_mint_requests_by_hash_response__descriptor) \
    , NULL }


struct  Planetmintgo__Dao__QueryMintRequestsByAddressRequest
{
  ProtobufCMessage base;
  char *address;
};
#define PLANETMINTGO__DAO__QUERY_MINT_REQUESTS_BY_ADDRESS_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_mint_requests_by_address_request__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  Planetmintgo__Dao__QueryMintRequestsByAddressResponse
{
  ProtobufCMessage base;
  Planetmintgo__Dao__MintRequests *mintrequests;
};
#define PLANETMINTGO__DAO__QUERY_MINT_REQUESTS_BY_ADDRESS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_mint_requests_by_address_response__descriptor) \
    , NULL }


struct  Planetmintgo__Dao__QueryGetReissuanceRequest
{
  ProtobufCMessage base;
  int64_t blockheight;
};
#define PLANETMINTGO__DAO__QUERY_GET_REISSUANCE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_get_reissuance_request__descriptor) \
    , 0 }


struct  Planetmintgo__Dao__QueryGetReissuanceResponse
{
  ProtobufCMessage base;
  Planetmintgo__Dao__Reissuance *reissuance;
};
#define PLANETMINTGO__DAO__QUERY_GET_REISSUANCE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_get_reissuance_response__descriptor) \
    , NULL }


struct  Planetmintgo__Dao__QueryReissuancesRequest
{
  ProtobufCMessage base;
  Cosmos__Base__Query__V1beta1__PageRequest *pagination;
};
#define PLANETMINTGO__DAO__QUERY_REISSUANCES_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_reissuances_request__descriptor) \
    , NULL }


struct  Planetmintgo__Dao__QueryReissuancesResponse
{
  ProtobufCMessage base;
  size_t n_reissuances;
  Planetmintgo__Dao__Reissuance **reissuances;
  Cosmos__Base__Query__V1beta1__PageResponse *pagination;
};
#define PLANETMINTGO__DAO__QUERY_REISSUANCES_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_reissuances_response__descriptor) \
    , 0,NULL, NULL }


struct  Planetmintgo__Dao__QueryGetChallengeRequest
{
  ProtobufCMessage base;
  int64_t height;
};
#define PLANETMINTGO__DAO__QUERY_GET_CHALLENGE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_get_challenge_request__descriptor) \
    , 0 }


struct  Planetmintgo__Dao__QueryGetChallengeResponse
{
  ProtobufCMessage base;
  Planetmintgo__Dao__Challenge *challenge;
};
#define PLANETMINTGO__DAO__QUERY_GET_CHALLENGE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_get_challenge_response__descriptor) \
    , NULL }


struct  Planetmintgo__Dao__QueryChallengesRequest
{
  ProtobufCMessage base;
  Cosmos__Base__Query__V1beta1__PageRequest *pagination;
};
#define PLANETMINTGO__DAO__QUERY_CHALLENGES_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_challenges_request__descriptor) \
    , NULL }


struct  Planetmintgo__Dao__QueryChallengesResponse
{
  ProtobufCMessage base;
  size_t n_challenges;
  Planetmintgo__Dao__Challenge **challenges;
  Cosmos__Base__Query__V1beta1__PageResponse *pagination;
};
#define PLANETMINTGO__DAO__QUERY_CHALLENGES_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_challenges_response__descriptor) \
    , 0,NULL, NULL }


struct  Planetmintgo__Dao__QueryGetDistributionRequest
{
  ProtobufCMessage base;
  int64_t lastpopheight;
};
#define PLANETMINTGO__DAO__QUERY_GET_DISTRIBUTION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_get_distribution_request__descriptor) \
    , 0 }


struct  Planetmintgo__Dao__QueryGetDistributionResponse
{
  ProtobufCMessage base;
  Planetmintgo__Dao__DistributionOrder *distribution;
};
#define PLANETMINTGO__DAO__QUERY_GET_DISTRIBUTION_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__query_get_distribution_response__descriptor) \
    , NULL }


/* Planetmintgo__Dao__QueryParamsRequest methods */
void   planetmintgo__dao__query_params_request__init
                     (Planetmintgo__Dao__QueryParamsRequest         *message);
size_t planetmintgo__dao__query_params_request__get_packed_size
                     (const Planetmintgo__Dao__QueryParamsRequest   *message);
size_t planetmintgo__dao__query_params_request__pack
                     (const Planetmintgo__Dao__QueryParamsRequest   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_params_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryParamsRequest   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryParamsRequest *
       planetmintgo__dao__query_params_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_params_request__free_unpacked
                     (Planetmintgo__Dao__QueryParamsRequest *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryParamsResponse methods */
void   planetmintgo__dao__query_params_response__init
                     (Planetmintgo__Dao__QueryParamsResponse         *message);
size_t planetmintgo__dao__query_params_response__get_packed_size
                     (const Planetmintgo__Dao__QueryParamsResponse   *message);
size_t planetmintgo__dao__query_params_response__pack
                     (const Planetmintgo__Dao__QueryParamsResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_params_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryParamsResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryParamsResponse *
       planetmintgo__dao__query_params_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_params_response__free_unpacked
                     (Planetmintgo__Dao__QueryParamsResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryGetMintRequestsByHashRequest methods */
void   planetmintgo__dao__query_get_mint_requests_by_hash_request__init
                     (Planetmintgo__Dao__QueryGetMintRequestsByHashRequest         *message);
size_t planetmintgo__dao__query_get_mint_requests_by_hash_request__get_packed_size
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashRequest   *message);
size_t planetmintgo__dao__query_get_mint_requests_by_hash_request__pack
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashRequest   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_get_mint_requests_by_hash_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashRequest   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *
       planetmintgo__dao__query_get_mint_requests_by_hash_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_get_mint_requests_by_hash_request__free_unpacked
                     (Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryGetMintRequestsByHashResponse methods */
void   planetmintgo__dao__query_get_mint_requests_by_hash_response__init
                     (Planetmintgo__Dao__QueryGetMintRequestsByHashResponse         *message);
size_t planetmintgo__dao__query_get_mint_requests_by_hash_response__get_packed_size
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashResponse   *message);
size_t planetmintgo__dao__query_get_mint_requests_by_hash_response__pack
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_get_mint_requests_by_hash_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetMintRequestsByHashResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryGetMintRequestsByHashResponse *
       planetmintgo__dao__query_get_mint_requests_by_hash_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_get_mint_requests_by_hash_response__free_unpacked
                     (Planetmintgo__Dao__QueryGetMintRequestsByHashResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryMintRequestsByAddressRequest methods */
void   planetmintgo__dao__query_mint_requests_by_address_request__init
                     (Planetmintgo__Dao__QueryMintRequestsByAddressRequest         *message);
size_t planetmintgo__dao__query_mint_requests_by_address_request__get_packed_size
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressRequest   *message);
size_t planetmintgo__dao__query_mint_requests_by_address_request__pack
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressRequest   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_mint_requests_by_address_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressRequest   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryMintRequestsByAddressRequest *
       planetmintgo__dao__query_mint_requests_by_address_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_mint_requests_by_address_request__free_unpacked
                     (Planetmintgo__Dao__QueryMintRequestsByAddressRequest *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryMintRequestsByAddressResponse methods */
void   planetmintgo__dao__query_mint_requests_by_address_response__init
                     (Planetmintgo__Dao__QueryMintRequestsByAddressResponse         *message);
size_t planetmintgo__dao__query_mint_requests_by_address_response__get_packed_size
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressResponse   *message);
size_t planetmintgo__dao__query_mint_requests_by_address_response__pack
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_mint_requests_by_address_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryMintRequestsByAddressResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryMintRequestsByAddressResponse *
       planetmintgo__dao__query_mint_requests_by_address_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_mint_requests_by_address_response__free_unpacked
                     (Planetmintgo__Dao__QueryMintRequestsByAddressResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryGetReissuanceRequest methods */
void   planetmintgo__dao__query_get_reissuance_request__init
                     (Planetmintgo__Dao__QueryGetReissuanceRequest         *message);
size_t planetmintgo__dao__query_get_reissuance_request__get_packed_size
                     (const Planetmintgo__Dao__QueryGetReissuanceRequest   *message);
size_t planetmintgo__dao__query_get_reissuance_request__pack
                     (const Planetmintgo__Dao__QueryGetReissuanceRequest   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_get_reissuance_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetReissuanceRequest   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryGetReissuanceRequest *
       planetmintgo__dao__query_get_reissuance_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_get_reissuance_request__free_unpacked
                     (Planetmintgo__Dao__QueryGetReissuanceRequest *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryGetReissuanceResponse methods */
void   planetmintgo__dao__query_get_reissuance_response__init
                     (Planetmintgo__Dao__QueryGetReissuanceResponse         *message);
size_t planetmintgo__dao__query_get_reissuance_response__get_packed_size
                     (const Planetmintgo__Dao__QueryGetReissuanceResponse   *message);
size_t planetmintgo__dao__query_get_reissuance_response__pack
                     (const Planetmintgo__Dao__QueryGetReissuanceResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_get_reissuance_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetReissuanceResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryGetReissuanceResponse *
       planetmintgo__dao__query_get_reissuance_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_get_reissuance_response__free_unpacked
                     (Planetmintgo__Dao__QueryGetReissuanceResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryReissuancesRequest methods */
void   planetmintgo__dao__query_reissuances_request__init
                     (Planetmintgo__Dao__QueryReissuancesRequest         *message);
size_t planetmintgo__dao__query_reissuances_request__get_packed_size
                     (const Planetmintgo__Dao__QueryReissuancesRequest   *message);
size_t planetmintgo__dao__query_reissuances_request__pack
                     (const Planetmintgo__Dao__QueryReissuancesRequest   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_reissuances_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryReissuancesRequest   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryReissuancesRequest *
       planetmintgo__dao__query_reissuances_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_reissuances_request__free_unpacked
                     (Planetmintgo__Dao__QueryReissuancesRequest *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryReissuancesResponse methods */
void   planetmintgo__dao__query_reissuances_response__init
                     (Planetmintgo__Dao__QueryReissuancesResponse         *message);
size_t planetmintgo__dao__query_reissuances_response__get_packed_size
                     (const Planetmintgo__Dao__QueryReissuancesResponse   *message);
size_t planetmintgo__dao__query_reissuances_response__pack
                     (const Planetmintgo__Dao__QueryReissuancesResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_reissuances_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryReissuancesResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryReissuancesResponse *
       planetmintgo__dao__query_reissuances_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_reissuances_response__free_unpacked
                     (Planetmintgo__Dao__QueryReissuancesResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryGetChallengeRequest methods */
void   planetmintgo__dao__query_get_challenge_request__init
                     (Planetmintgo__Dao__QueryGetChallengeRequest         *message);
size_t planetmintgo__dao__query_get_challenge_request__get_packed_size
                     (const Planetmintgo__Dao__QueryGetChallengeRequest   *message);
size_t planetmintgo__dao__query_get_challenge_request__pack
                     (const Planetmintgo__Dao__QueryGetChallengeRequest   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_get_challenge_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetChallengeRequest   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryGetChallengeRequest *
       planetmintgo__dao__query_get_challenge_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_get_challenge_request__free_unpacked
                     (Planetmintgo__Dao__QueryGetChallengeRequest *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryGetChallengeResponse methods */
void   planetmintgo__dao__query_get_challenge_response__init
                     (Planetmintgo__Dao__QueryGetChallengeResponse         *message);
size_t planetmintgo__dao__query_get_challenge_response__get_packed_size
                     (const Planetmintgo__Dao__QueryGetChallengeResponse   *message);
size_t planetmintgo__dao__query_get_challenge_response__pack
                     (const Planetmintgo__Dao__QueryGetChallengeResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_get_challenge_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetChallengeResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryGetChallengeResponse *
       planetmintgo__dao__query_get_challenge_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_get_challenge_response__free_unpacked
                     (Planetmintgo__Dao__QueryGetChallengeResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryChallengesRequest methods */
void   planetmintgo__dao__query_challenges_request__init
                     (Planetmintgo__Dao__QueryChallengesRequest         *message);
size_t planetmintgo__dao__query_challenges_request__get_packed_size
                     (const Planetmintgo__Dao__QueryChallengesRequest   *message);
size_t planetmintgo__dao__query_challenges_request__pack
                     (const Planetmintgo__Dao__QueryChallengesRequest   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_challenges_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryChallengesRequest   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryChallengesRequest *
       planetmintgo__dao__query_challenges_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_challenges_request__free_unpacked
                     (Planetmintgo__Dao__QueryChallengesRequest *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryChallengesResponse methods */
void   planetmintgo__dao__query_challenges_response__init
                     (Planetmintgo__Dao__QueryChallengesResponse         *message);
size_t planetmintgo__dao__query_challenges_response__get_packed_size
                     (const Planetmintgo__Dao__QueryChallengesResponse   *message);
size_t planetmintgo__dao__query_challenges_response__pack
                     (const Planetmintgo__Dao__QueryChallengesResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_challenges_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryChallengesResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryChallengesResponse *
       planetmintgo__dao__query_challenges_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_challenges_response__free_unpacked
                     (Planetmintgo__Dao__QueryChallengesResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryGetDistributionRequest methods */
void   planetmintgo__dao__query_get_distribution_request__init
                     (Planetmintgo__Dao__QueryGetDistributionRequest         *message);
size_t planetmintgo__dao__query_get_distribution_request__get_packed_size
                     (const Planetmintgo__Dao__QueryGetDistributionRequest   *message);
size_t planetmintgo__dao__query_get_distribution_request__pack
                     (const Planetmintgo__Dao__QueryGetDistributionRequest   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_get_distribution_request__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetDistributionRequest   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryGetDistributionRequest *
       planetmintgo__dao__query_get_distribution_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_get_distribution_request__free_unpacked
                     (Planetmintgo__Dao__QueryGetDistributionRequest *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__QueryGetDistributionResponse methods */
void   planetmintgo__dao__query_get_distribution_response__init
                     (Planetmintgo__Dao__QueryGetDistributionResponse         *message);
size_t planetmintgo__dao__query_get_distribution_response__get_packed_size
                     (const Planetmintgo__Dao__QueryGetDistributionResponse   *message);
size_t planetmintgo__dao__query_get_distribution_response__pack
                     (const Planetmintgo__Dao__QueryGetDistributionResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__query_get_distribution_response__pack_to_buffer
                     (const Planetmintgo__Dao__QueryGetDistributionResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__QueryGetDistributionResponse *
       planetmintgo__dao__query_get_distribution_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__query_get_distribution_response__free_unpacked
                     (Planetmintgo__Dao__QueryGetDistributionResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Planetmintgo__Dao__QueryParamsRequest_Closure)
                 (const Planetmintgo__Dao__QueryParamsRequest *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryParamsResponse_Closure)
                 (const Planetmintgo__Dao__QueryParamsResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryGetMintRequestsByHashRequest_Closure)
                 (const Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryGetMintRequestsByHashResponse_Closure)
                 (const Planetmintgo__Dao__QueryGetMintRequestsByHashResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryMintRequestsByAddressRequest_Closure)
                 (const Planetmintgo__Dao__QueryMintRequestsByAddressRequest *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryMintRequestsByAddressResponse_Closure)
                 (const Planetmintgo__Dao__QueryMintRequestsByAddressResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryGetReissuanceRequest_Closure)
                 (const Planetmintgo__Dao__QueryGetReissuanceRequest *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryGetReissuanceResponse_Closure)
                 (const Planetmintgo__Dao__QueryGetReissuanceResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryReissuancesRequest_Closure)
                 (const Planetmintgo__Dao__QueryReissuancesRequest *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryReissuancesResponse_Closure)
                 (const Planetmintgo__Dao__QueryReissuancesResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryGetChallengeRequest_Closure)
                 (const Planetmintgo__Dao__QueryGetChallengeRequest *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryGetChallengeResponse_Closure)
                 (const Planetmintgo__Dao__QueryGetChallengeResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryChallengesRequest_Closure)
                 (const Planetmintgo__Dao__QueryChallengesRequest *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryChallengesResponse_Closure)
                 (const Planetmintgo__Dao__QueryChallengesResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryGetDistributionRequest_Closure)
                 (const Planetmintgo__Dao__QueryGetDistributionRequest *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__QueryGetDistributionResponse_Closure)
                 (const Planetmintgo__Dao__QueryGetDistributionResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct Planetmintgo__Dao__Query_Service Planetmintgo__Dao__Query_Service;
struct Planetmintgo__Dao__Query_Service
{
  ProtobufCService base;
  void (*params)(Planetmintgo__Dao__Query_Service *service,
                 const Planetmintgo__Dao__QueryParamsRequest *input,
                 Planetmintgo__Dao__QueryParamsResponse_Closure closure,
                 void *closure_data);
  void (*get_mint_requests_by_hash)(Planetmintgo__Dao__Query_Service *service,
                                    const Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *input,
                                    Planetmintgo__Dao__QueryGetMintRequestsByHashResponse_Closure closure,
                                    void *closure_data);
  void (*mint_requests_by_address)(Planetmintgo__Dao__Query_Service *service,
                                   const Planetmintgo__Dao__QueryMintRequestsByAddressRequest *input,
                                   Planetmintgo__Dao__QueryMintRequestsByAddressResponse_Closure closure,
                                   void *closure_data);
  void (*get_reissuance)(Planetmintgo__Dao__Query_Service *service,
                         const Planetmintgo__Dao__QueryGetReissuanceRequest *input,
                         Planetmintgo__Dao__QueryGetReissuanceResponse_Closure closure,
                         void *closure_data);
  void (*reissuances)(Planetmintgo__Dao__Query_Service *service,
                      const Planetmintgo__Dao__QueryReissuancesRequest *input,
                      Planetmintgo__Dao__QueryReissuancesResponse_Closure closure,
                      void *closure_data);
  void (*get_challenge)(Planetmintgo__Dao__Query_Service *service,
                        const Planetmintgo__Dao__QueryGetChallengeRequest *input,
                        Planetmintgo__Dao__QueryGetChallengeResponse_Closure closure,
                        void *closure_data);
  void (*challenges)(Planetmintgo__Dao__Query_Service *service,
                     const Planetmintgo__Dao__QueryChallengesRequest *input,
                     Planetmintgo__Dao__QueryChallengesResponse_Closure closure,
                     void *closure_data);
  void (*get_distribution)(Planetmintgo__Dao__Query_Service *service,
                           const Planetmintgo__Dao__QueryGetDistributionRequest *input,
                           Planetmintgo__Dao__QueryGetDistributionResponse_Closure closure,
                           void *closure_data);
};
typedef void (*Planetmintgo__Dao__Query_ServiceDestroy)(Planetmintgo__Dao__Query_Service *);
void planetmintgo__dao__query__init (Planetmintgo__Dao__Query_Service *service,
                                     Planetmintgo__Dao__Query_ServiceDestroy destroy);
#define PLANETMINTGO__DAO__QUERY__BASE_INIT \
    { &planetmintgo__dao__query__descriptor, protobuf_c_service_invoke_internal, NULL }
#define PLANETMINTGO__DAO__QUERY__INIT(function_prefix__) \
    { PLANETMINTGO__DAO__QUERY__BASE_INIT,\
      function_prefix__ ## params,\
      function_prefix__ ## get_mint_requests_by_hash,\
      function_prefix__ ## mint_requests_by_address,\
      function_prefix__ ## get_reissuance,\
      function_prefix__ ## reissuances,\
      function_prefix__ ## get_challenge,\
      function_prefix__ ## challenges,\
      function_prefix__ ## get_distribution  }
void planetmintgo__dao__query__params(ProtobufCService *service,
                                      const Planetmintgo__Dao__QueryParamsRequest *input,
                                      Planetmintgo__Dao__QueryParamsResponse_Closure closure,
                                      void *closure_data);
void planetmintgo__dao__query__get_mint_requests_by_hash(ProtobufCService *service,
                                                         const Planetmintgo__Dao__QueryGetMintRequestsByHashRequest *input,
                                                         Planetmintgo__Dao__QueryGetMintRequestsByHashResponse_Closure closure,
                                                         void *closure_data);
void planetmintgo__dao__query__mint_requests_by_address(ProtobufCService *service,
                                                        const Planetmintgo__Dao__QueryMintRequestsByAddressRequest *input,
                                                        Planetmintgo__Dao__QueryMintRequestsByAddressResponse_Closure closure,
                                                        void *closure_data);
void planetmintgo__dao__query__get_reissuance(ProtobufCService *service,
                                              const Planetmintgo__Dao__QueryGetReissuanceRequest *input,
                                              Planetmintgo__Dao__QueryGetReissuanceResponse_Closure closure,
                                              void *closure_data);
void planetmintgo__dao__query__reissuances(ProtobufCService *service,
                                           const Planetmintgo__Dao__QueryReissuancesRequest *input,
                                           Planetmintgo__Dao__QueryReissuancesResponse_Closure closure,
                                           void *closure_data);
void planetmintgo__dao__query__get_challenge(ProtobufCService *service,
                                             const Planetmintgo__Dao__QueryGetChallengeRequest *input,
                                             Planetmintgo__Dao__QueryGetChallengeResponse_Closure closure,
                                             void *closure_data);
void planetmintgo__dao__query__challenges(ProtobufCService *service,
                                          const Planetmintgo__Dao__QueryChallengesRequest *input,
                                          Planetmintgo__Dao__QueryChallengesResponse_Closure closure,
                                          void *closure_data);
void planetmintgo__dao__query__get_distribution(ProtobufCService *service,
                                                const Planetmintgo__Dao__QueryGetDistributionRequest *input,
                                                Planetmintgo__Dao__QueryGetDistributionResponse_Closure closure,
                                                void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor planetmintgo__dao__query_params_request__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_params_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_get_mint_requests_by_hash_request__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_get_mint_requests_by_hash_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_mint_requests_by_address_request__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_mint_requests_by_address_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_get_reissuance_request__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_get_reissuance_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_reissuances_request__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_reissuances_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_get_challenge_request__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_get_challenge_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_challenges_request__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_challenges_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_get_distribution_request__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__query_get_distribution_response__descriptor;
extern const ProtobufCServiceDescriptor planetmintgo__dao__query__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_planetmintgo_2fdao_2fquery_2eproto__INCLUDED */
