/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: planetmintgo/dao/reissuance.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "planetmintgo/dao/reissuance.pb-c.h"
void   planetmintgo__dao__reissuance__init
                     (Planetmintgo__Dao__Reissuance         *message)
{
  static const Planetmintgo__Dao__Reissuance init_value = PLANETMINTGO__DAO__REISSUANCE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__reissuance__get_packed_size
                     (const Planetmintgo__Dao__Reissuance *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__reissuance__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__reissuance__pack
                     (const Planetmintgo__Dao__Reissuance *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__reissuance__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__reissuance__pack_to_buffer
                     (const Planetmintgo__Dao__Reissuance *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__reissuance__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__Reissuance *
       planetmintgo__dao__reissuance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__Reissuance *)
     protobuf_c_message_unpack (&planetmintgo__dao__reissuance__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__reissuance__free_unpacked
                     (Planetmintgo__Dao__Reissuance *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__reissuance__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor planetmintgo__dao__reissuance__field_descriptors[6] =
{
  {
    "proposer",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__Reissuance, proposer),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rawTx",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__Reissuance, rawtx),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txID",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__Reissuance, txid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blockHeight",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__Reissuance, blockheight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firstIncludedPop",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__Reissuance, firstincludedpop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lastIncludedPop",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__Reissuance, lastincludedpop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__reissuance__field_indices_by_name[] = {
  3,   /* field[3] = blockHeight */
  4,   /* field[4] = firstIncludedPop */
  5,   /* field[5] = lastIncludedPop */
  0,   /* field[0] = proposer */
  1,   /* field[1] = rawTx */
  2,   /* field[2] = txID */
};
static const ProtobufCIntRange planetmintgo__dao__reissuance__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__reissuance__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.Reissuance",
  "Reissuance",
  "Planetmintgo__Dao__Reissuance",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__Reissuance),
  6,
  planetmintgo__dao__reissuance__field_descriptors,
  planetmintgo__dao__reissuance__field_indices_by_name,
  1,  planetmintgo__dao__reissuance__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__reissuance__init,
  NULL,NULL,NULL    /* reserved[123] */
};
