/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: planetmintgo/dao/tx.proto */

#ifndef PROTOBUF_C_planetmintgo_2fdao_2ftx_2eproto__INCLUDED
#define PROTOBUF_C_planetmintgo_2fdao_2ftx_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "planetmintgo/dao/challenge.pb-c.h"
#include "planetmintgo/dao/mint_request.pb-c.h"
#include "planetmintgo/dao/distribution_order.pb-c.h"
#include "planetmintgo/dao/params.pb-c.h"
#include "amino/amino.pb-c.h"
#include "gogoproto/gogo.pb-c.h"
#include "cosmos_proto/cosmos.pb-c.h"
#include "cosmos/msg/v1/msg.pb-c.h"

typedef struct Planetmintgo__Dao__MsgReportPopResult Planetmintgo__Dao__MsgReportPopResult;
typedef struct Planetmintgo__Dao__MsgReportPopResultResponse Planetmintgo__Dao__MsgReportPopResultResponse;
typedef struct Planetmintgo__Dao__MsgReissueRDDLProposal Planetmintgo__Dao__MsgReissueRDDLProposal;
typedef struct Planetmintgo__Dao__MsgReissueRDDLProposalResponse Planetmintgo__Dao__MsgReissueRDDLProposalResponse;
typedef struct Planetmintgo__Dao__MsgMintToken Planetmintgo__Dao__MsgMintToken;
typedef struct Planetmintgo__Dao__MsgMintTokenResponse Planetmintgo__Dao__MsgMintTokenResponse;
typedef struct Planetmintgo__Dao__MsgReissueRDDLResult Planetmintgo__Dao__MsgReissueRDDLResult;
typedef struct Planetmintgo__Dao__MsgReissueRDDLResultResponse Planetmintgo__Dao__MsgReissueRDDLResultResponse;
typedef struct Planetmintgo__Dao__MsgDistributionResult Planetmintgo__Dao__MsgDistributionResult;
typedef struct Planetmintgo__Dao__MsgDistributionResultResponse Planetmintgo__Dao__MsgDistributionResultResponse;
typedef struct Planetmintgo__Dao__MsgDistributionRequest Planetmintgo__Dao__MsgDistributionRequest;
typedef struct Planetmintgo__Dao__MsgDistributionRequestResponse Planetmintgo__Dao__MsgDistributionRequestResponse;
typedef struct Planetmintgo__Dao__MsgUpdateParams Planetmintgo__Dao__MsgUpdateParams;
typedef struct Planetmintgo__Dao__MsgUpdateParamsResponse Planetmintgo__Dao__MsgUpdateParamsResponse;
typedef struct Planetmintgo__Dao__MsgInitPop Planetmintgo__Dao__MsgInitPop;
typedef struct Planetmintgo__Dao__MsgInitPopResponse Planetmintgo__Dao__MsgInitPopResponse;


/* --- enums --- */


/* --- messages --- */

struct  Planetmintgo__Dao__MsgReportPopResult
{
  ProtobufCMessage base;
  char *creator;
  Planetmintgo__Dao__Challenge *challenge;
};
#define PLANETMINTGO__DAO__MSG_REPORT_POP_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_report_pop_result__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


struct  Planetmintgo__Dao__MsgReportPopResultResponse
{
  ProtobufCMessage base;
};
#define PLANETMINTGO__DAO__MSG_REPORT_POP_RESULT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_report_pop_result_response__descriptor) \
     }


struct  Planetmintgo__Dao__MsgReissueRDDLProposal
{
  ProtobufCMessage base;
  char *creator;
  char *proposer;
  char *tx;
  int64_t blockheight;
  int64_t firstincludedpop;
  int64_t lastincludedpop;
};
#define PLANETMINTGO__DAO__MSG_REISSUE_RDDLPROPOSAL__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_reissue_rddlproposal__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0, 0, 0 }


struct  Planetmintgo__Dao__MsgReissueRDDLProposalResponse
{
  ProtobufCMessage base;
};
#define PLANETMINTGO__DAO__MSG_REISSUE_RDDLPROPOSAL_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_reissue_rddlproposal_response__descriptor) \
     }


struct  Planetmintgo__Dao__MsgMintToken
{
  ProtobufCMessage base;
  char *creator;
  Planetmintgo__Dao__MintRequest *mintrequest;
};
#define PLANETMINTGO__DAO__MSG_MINT_TOKEN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_mint_token__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


struct  Planetmintgo__Dao__MsgMintTokenResponse
{
  ProtobufCMessage base;
};
#define PLANETMINTGO__DAO__MSG_MINT_TOKEN_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_mint_token_response__descriptor) \
     }


struct  Planetmintgo__Dao__MsgReissueRDDLResult
{
  ProtobufCMessage base;
  char *creator;
  char *proposer;
  char *txid;
  int64_t blockheight;
};
#define PLANETMINTGO__DAO__MSG_REISSUE_RDDLRESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_reissue_rddlresult__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Planetmintgo__Dao__MsgReissueRDDLResultResponse
{
  ProtobufCMessage base;
};
#define PLANETMINTGO__DAO__MSG_REISSUE_RDDLRESULT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_reissue_rddlresult_response__descriptor) \
     }


struct  Planetmintgo__Dao__MsgDistributionResult
{
  ProtobufCMessage base;
  char *creator;
  int64_t lastpop;
  char *daotxid;
  char *investortxid;
  char *poptxid;
};
#define PLANETMINTGO__DAO__MSG_DISTRIBUTION_RESULT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_distribution_result__descriptor) \
    , (char *)protobuf_c_empty_string, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  Planetmintgo__Dao__MsgDistributionResultResponse
{
  ProtobufCMessage base;
};
#define PLANETMINTGO__DAO__MSG_DISTRIBUTION_RESULT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_distribution_result_response__descriptor) \
     }


struct  Planetmintgo__Dao__MsgDistributionRequest
{
  ProtobufCMessage base;
  char *creator;
  Planetmintgo__Dao__DistributionOrder *distribution;
};
#define PLANETMINTGO__DAO__MSG_DISTRIBUTION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_distribution_request__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


struct  Planetmintgo__Dao__MsgDistributionRequestResponse
{
  ProtobufCMessage base;
};
#define PLANETMINTGO__DAO__MSG_DISTRIBUTION_REQUEST_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_distribution_request_response__descriptor) \
     }


struct  Planetmintgo__Dao__MsgUpdateParams
{
  ProtobufCMessage base;
  /*
   * authority is the address that controls the module (defaults to x/gov unless overwritten).
   */
  char *authority;
  /*
   * NOTE: All parameters must be supplied.
   */
  Planetmintgo__Dao__Params *params;
};
#define PLANETMINTGO__DAO__MSG_UPDATE_PARAMS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_update_params__descriptor) \
    , (char *)protobuf_c_empty_string, NULL }


struct  Planetmintgo__Dao__MsgUpdateParamsResponse
{
  ProtobufCMessage base;
};
#define PLANETMINTGO__DAO__MSG_UPDATE_PARAMS_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_update_params_response__descriptor) \
     }


struct  Planetmintgo__Dao__MsgInitPop
{
  ProtobufCMessage base;
  char *creator;
  char *initiator;
  char *challenger;
  char *challengee;
  int64_t height;
};
#define PLANETMINTGO__DAO__MSG_INIT_POP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_init_pop__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, 0 }


struct  Planetmintgo__Dao__MsgInitPopResponse
{
  ProtobufCMessage base;
};
#define PLANETMINTGO__DAO__MSG_INIT_POP_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&planetmintgo__dao__msg_init_pop_response__descriptor) \
     }


/* Planetmintgo__Dao__MsgReportPopResult methods */
void   planetmintgo__dao__msg_report_pop_result__init
                     (Planetmintgo__Dao__MsgReportPopResult         *message);
size_t planetmintgo__dao__msg_report_pop_result__get_packed_size
                     (const Planetmintgo__Dao__MsgReportPopResult   *message);
size_t planetmintgo__dao__msg_report_pop_result__pack
                     (const Planetmintgo__Dao__MsgReportPopResult   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_report_pop_result__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReportPopResult   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgReportPopResult *
       planetmintgo__dao__msg_report_pop_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_report_pop_result__free_unpacked
                     (Planetmintgo__Dao__MsgReportPopResult *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgReportPopResultResponse methods */
void   planetmintgo__dao__msg_report_pop_result_response__init
                     (Planetmintgo__Dao__MsgReportPopResultResponse         *message);
size_t planetmintgo__dao__msg_report_pop_result_response__get_packed_size
                     (const Planetmintgo__Dao__MsgReportPopResultResponse   *message);
size_t planetmintgo__dao__msg_report_pop_result_response__pack
                     (const Planetmintgo__Dao__MsgReportPopResultResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_report_pop_result_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReportPopResultResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgReportPopResultResponse *
       planetmintgo__dao__msg_report_pop_result_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_report_pop_result_response__free_unpacked
                     (Planetmintgo__Dao__MsgReportPopResultResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgReissueRDDLProposal methods */
void   planetmintgo__dao__msg_reissue_rddlproposal__init
                     (Planetmintgo__Dao__MsgReissueRDDLProposal         *message);
size_t planetmintgo__dao__msg_reissue_rddlproposal__get_packed_size
                     (const Planetmintgo__Dao__MsgReissueRDDLProposal   *message);
size_t planetmintgo__dao__msg_reissue_rddlproposal__pack
                     (const Planetmintgo__Dao__MsgReissueRDDLProposal   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_reissue_rddlproposal__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReissueRDDLProposal   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgReissueRDDLProposal *
       planetmintgo__dao__msg_reissue_rddlproposal__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_reissue_rddlproposal__free_unpacked
                     (Planetmintgo__Dao__MsgReissueRDDLProposal *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgReissueRDDLProposalResponse methods */
void   planetmintgo__dao__msg_reissue_rddlproposal_response__init
                     (Planetmintgo__Dao__MsgReissueRDDLProposalResponse         *message);
size_t planetmintgo__dao__msg_reissue_rddlproposal_response__get_packed_size
                     (const Planetmintgo__Dao__MsgReissueRDDLProposalResponse   *message);
size_t planetmintgo__dao__msg_reissue_rddlproposal_response__pack
                     (const Planetmintgo__Dao__MsgReissueRDDLProposalResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_reissue_rddlproposal_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReissueRDDLProposalResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgReissueRDDLProposalResponse *
       planetmintgo__dao__msg_reissue_rddlproposal_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_reissue_rddlproposal_response__free_unpacked
                     (Planetmintgo__Dao__MsgReissueRDDLProposalResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgMintToken methods */
void   planetmintgo__dao__msg_mint_token__init
                     (Planetmintgo__Dao__MsgMintToken         *message);
size_t planetmintgo__dao__msg_mint_token__get_packed_size
                     (const Planetmintgo__Dao__MsgMintToken   *message);
size_t planetmintgo__dao__msg_mint_token__pack
                     (const Planetmintgo__Dao__MsgMintToken   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_mint_token__pack_to_buffer
                     (const Planetmintgo__Dao__MsgMintToken   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgMintToken *
       planetmintgo__dao__msg_mint_token__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_mint_token__free_unpacked
                     (Planetmintgo__Dao__MsgMintToken *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgMintTokenResponse methods */
void   planetmintgo__dao__msg_mint_token_response__init
                     (Planetmintgo__Dao__MsgMintTokenResponse         *message);
size_t planetmintgo__dao__msg_mint_token_response__get_packed_size
                     (const Planetmintgo__Dao__MsgMintTokenResponse   *message);
size_t planetmintgo__dao__msg_mint_token_response__pack
                     (const Planetmintgo__Dao__MsgMintTokenResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_mint_token_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgMintTokenResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgMintTokenResponse *
       planetmintgo__dao__msg_mint_token_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_mint_token_response__free_unpacked
                     (Planetmintgo__Dao__MsgMintTokenResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgReissueRDDLResult methods */
void   planetmintgo__dao__msg_reissue_rddlresult__init
                     (Planetmintgo__Dao__MsgReissueRDDLResult         *message);
size_t planetmintgo__dao__msg_reissue_rddlresult__get_packed_size
                     (const Planetmintgo__Dao__MsgReissueRDDLResult   *message);
size_t planetmintgo__dao__msg_reissue_rddlresult__pack
                     (const Planetmintgo__Dao__MsgReissueRDDLResult   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_reissue_rddlresult__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReissueRDDLResult   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgReissueRDDLResult *
       planetmintgo__dao__msg_reissue_rddlresult__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_reissue_rddlresult__free_unpacked
                     (Planetmintgo__Dao__MsgReissueRDDLResult *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgReissueRDDLResultResponse methods */
void   planetmintgo__dao__msg_reissue_rddlresult_response__init
                     (Planetmintgo__Dao__MsgReissueRDDLResultResponse         *message);
size_t planetmintgo__dao__msg_reissue_rddlresult_response__get_packed_size
                     (const Planetmintgo__Dao__MsgReissueRDDLResultResponse   *message);
size_t planetmintgo__dao__msg_reissue_rddlresult_response__pack
                     (const Planetmintgo__Dao__MsgReissueRDDLResultResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_reissue_rddlresult_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReissueRDDLResultResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgReissueRDDLResultResponse *
       planetmintgo__dao__msg_reissue_rddlresult_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_reissue_rddlresult_response__free_unpacked
                     (Planetmintgo__Dao__MsgReissueRDDLResultResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgDistributionResult methods */
void   planetmintgo__dao__msg_distribution_result__init
                     (Planetmintgo__Dao__MsgDistributionResult         *message);
size_t planetmintgo__dao__msg_distribution_result__get_packed_size
                     (const Planetmintgo__Dao__MsgDistributionResult   *message);
size_t planetmintgo__dao__msg_distribution_result__pack
                     (const Planetmintgo__Dao__MsgDistributionResult   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_distribution_result__pack_to_buffer
                     (const Planetmintgo__Dao__MsgDistributionResult   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgDistributionResult *
       planetmintgo__dao__msg_distribution_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_distribution_result__free_unpacked
                     (Planetmintgo__Dao__MsgDistributionResult *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgDistributionResultResponse methods */
void   planetmintgo__dao__msg_distribution_result_response__init
                     (Planetmintgo__Dao__MsgDistributionResultResponse         *message);
size_t planetmintgo__dao__msg_distribution_result_response__get_packed_size
                     (const Planetmintgo__Dao__MsgDistributionResultResponse   *message);
size_t planetmintgo__dao__msg_distribution_result_response__pack
                     (const Planetmintgo__Dao__MsgDistributionResultResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_distribution_result_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgDistributionResultResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgDistributionResultResponse *
       planetmintgo__dao__msg_distribution_result_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_distribution_result_response__free_unpacked
                     (Planetmintgo__Dao__MsgDistributionResultResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgDistributionRequest methods */
void   planetmintgo__dao__msg_distribution_request__init
                     (Planetmintgo__Dao__MsgDistributionRequest         *message);
size_t planetmintgo__dao__msg_distribution_request__get_packed_size
                     (const Planetmintgo__Dao__MsgDistributionRequest   *message);
size_t planetmintgo__dao__msg_distribution_request__pack
                     (const Planetmintgo__Dao__MsgDistributionRequest   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_distribution_request__pack_to_buffer
                     (const Planetmintgo__Dao__MsgDistributionRequest   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgDistributionRequest *
       planetmintgo__dao__msg_distribution_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_distribution_request__free_unpacked
                     (Planetmintgo__Dao__MsgDistributionRequest *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgDistributionRequestResponse methods */
void   planetmintgo__dao__msg_distribution_request_response__init
                     (Planetmintgo__Dao__MsgDistributionRequestResponse         *message);
size_t planetmintgo__dao__msg_distribution_request_response__get_packed_size
                     (const Planetmintgo__Dao__MsgDistributionRequestResponse   *message);
size_t planetmintgo__dao__msg_distribution_request_response__pack
                     (const Planetmintgo__Dao__MsgDistributionRequestResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_distribution_request_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgDistributionRequestResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgDistributionRequestResponse *
       planetmintgo__dao__msg_distribution_request_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_distribution_request_response__free_unpacked
                     (Planetmintgo__Dao__MsgDistributionRequestResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgUpdateParams methods */
void   planetmintgo__dao__msg_update_params__init
                     (Planetmintgo__Dao__MsgUpdateParams         *message);
size_t planetmintgo__dao__msg_update_params__get_packed_size
                     (const Planetmintgo__Dao__MsgUpdateParams   *message);
size_t planetmintgo__dao__msg_update_params__pack
                     (const Planetmintgo__Dao__MsgUpdateParams   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_update_params__pack_to_buffer
                     (const Planetmintgo__Dao__MsgUpdateParams   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgUpdateParams *
       planetmintgo__dao__msg_update_params__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_update_params__free_unpacked
                     (Planetmintgo__Dao__MsgUpdateParams *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgUpdateParamsResponse methods */
void   planetmintgo__dao__msg_update_params_response__init
                     (Planetmintgo__Dao__MsgUpdateParamsResponse         *message);
size_t planetmintgo__dao__msg_update_params_response__get_packed_size
                     (const Planetmintgo__Dao__MsgUpdateParamsResponse   *message);
size_t planetmintgo__dao__msg_update_params_response__pack
                     (const Planetmintgo__Dao__MsgUpdateParamsResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_update_params_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgUpdateParamsResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgUpdateParamsResponse *
       planetmintgo__dao__msg_update_params_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_update_params_response__free_unpacked
                     (Planetmintgo__Dao__MsgUpdateParamsResponse *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgInitPop methods */
void   planetmintgo__dao__msg_init_pop__init
                     (Planetmintgo__Dao__MsgInitPop         *message);
size_t planetmintgo__dao__msg_init_pop__get_packed_size
                     (const Planetmintgo__Dao__MsgInitPop   *message);
size_t planetmintgo__dao__msg_init_pop__pack
                     (const Planetmintgo__Dao__MsgInitPop   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_init_pop__pack_to_buffer
                     (const Planetmintgo__Dao__MsgInitPop   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgInitPop *
       planetmintgo__dao__msg_init_pop__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_init_pop__free_unpacked
                     (Planetmintgo__Dao__MsgInitPop *message,
                      ProtobufCAllocator *allocator);
/* Planetmintgo__Dao__MsgInitPopResponse methods */
void   planetmintgo__dao__msg_init_pop_response__init
                     (Planetmintgo__Dao__MsgInitPopResponse         *message);
size_t planetmintgo__dao__msg_init_pop_response__get_packed_size
                     (const Planetmintgo__Dao__MsgInitPopResponse   *message);
size_t planetmintgo__dao__msg_init_pop_response__pack
                     (const Planetmintgo__Dao__MsgInitPopResponse   *message,
                      uint8_t             *out);
size_t planetmintgo__dao__msg_init_pop_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgInitPopResponse   *message,
                      ProtobufCBuffer     *buffer);
Planetmintgo__Dao__MsgInitPopResponse *
       planetmintgo__dao__msg_init_pop_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   planetmintgo__dao__msg_init_pop_response__free_unpacked
                     (Planetmintgo__Dao__MsgInitPopResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Planetmintgo__Dao__MsgReportPopResult_Closure)
                 (const Planetmintgo__Dao__MsgReportPopResult *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgReportPopResultResponse_Closure)
                 (const Planetmintgo__Dao__MsgReportPopResultResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgReissueRDDLProposal_Closure)
                 (const Planetmintgo__Dao__MsgReissueRDDLProposal *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgReissueRDDLProposalResponse_Closure)
                 (const Planetmintgo__Dao__MsgReissueRDDLProposalResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgMintToken_Closure)
                 (const Planetmintgo__Dao__MsgMintToken *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgMintTokenResponse_Closure)
                 (const Planetmintgo__Dao__MsgMintTokenResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgReissueRDDLResult_Closure)
                 (const Planetmintgo__Dao__MsgReissueRDDLResult *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgReissueRDDLResultResponse_Closure)
                 (const Planetmintgo__Dao__MsgReissueRDDLResultResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgDistributionResult_Closure)
                 (const Planetmintgo__Dao__MsgDistributionResult *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgDistributionResultResponse_Closure)
                 (const Planetmintgo__Dao__MsgDistributionResultResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgDistributionRequest_Closure)
                 (const Planetmintgo__Dao__MsgDistributionRequest *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgDistributionRequestResponse_Closure)
                 (const Planetmintgo__Dao__MsgDistributionRequestResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgUpdateParams_Closure)
                 (const Planetmintgo__Dao__MsgUpdateParams *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgUpdateParamsResponse_Closure)
                 (const Planetmintgo__Dao__MsgUpdateParamsResponse *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgInitPop_Closure)
                 (const Planetmintgo__Dao__MsgInitPop *message,
                  void *closure_data);
typedef void (*Planetmintgo__Dao__MsgInitPopResponse_Closure)
                 (const Planetmintgo__Dao__MsgInitPopResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct Planetmintgo__Dao__Msg_Service Planetmintgo__Dao__Msg_Service;
struct Planetmintgo__Dao__Msg_Service
{
  ProtobufCService base;
  void (*reissue_rddlproposal)(Planetmintgo__Dao__Msg_Service *service,
                               const Planetmintgo__Dao__MsgReissueRDDLProposal *input,
                               Planetmintgo__Dao__MsgReissueRDDLProposalResponse_Closure closure,
                               void *closure_data);
  void (*mint_token)(Planetmintgo__Dao__Msg_Service *service,
                     const Planetmintgo__Dao__MsgMintToken *input,
                     Planetmintgo__Dao__MsgMintTokenResponse_Closure closure,
                     void *closure_data);
  void (*reissue_rddlresult)(Planetmintgo__Dao__Msg_Service *service,
                             const Planetmintgo__Dao__MsgReissueRDDLResult *input,
                             Planetmintgo__Dao__MsgReissueRDDLResultResponse_Closure closure,
                             void *closure_data);
  void (*distribution_result)(Planetmintgo__Dao__Msg_Service *service,
                              const Planetmintgo__Dao__MsgDistributionResult *input,
                              Planetmintgo__Dao__MsgDistributionResultResponse_Closure closure,
                              void *closure_data);
  void (*distribution_request)(Planetmintgo__Dao__Msg_Service *service,
                               const Planetmintgo__Dao__MsgDistributionRequest *input,
                               Planetmintgo__Dao__MsgDistributionRequestResponse_Closure closure,
                               void *closure_data);
  void (*update_params)(Planetmintgo__Dao__Msg_Service *service,
                        const Planetmintgo__Dao__MsgUpdateParams *input,
                        Planetmintgo__Dao__MsgUpdateParamsResponse_Closure closure,
                        void *closure_data);
  void (*report_pop_result)(Planetmintgo__Dao__Msg_Service *service,
                            const Planetmintgo__Dao__MsgReportPopResult *input,
                            Planetmintgo__Dao__MsgReportPopResultResponse_Closure closure,
                            void *closure_data);
  void (*init_pop)(Planetmintgo__Dao__Msg_Service *service,
                   const Planetmintgo__Dao__MsgInitPop *input,
                   Planetmintgo__Dao__MsgInitPopResponse_Closure closure,
                   void *closure_data);
};
typedef void (*Planetmintgo__Dao__Msg_ServiceDestroy)(Planetmintgo__Dao__Msg_Service *);
void planetmintgo__dao__msg__init (Planetmintgo__Dao__Msg_Service *service,
                                   Planetmintgo__Dao__Msg_ServiceDestroy destroy);
#define PLANETMINTGO__DAO__MSG__BASE_INIT \
    { &planetmintgo__dao__msg__descriptor, protobuf_c_service_invoke_internal, NULL }
#define PLANETMINTGO__DAO__MSG__INIT(function_prefix__) \
    { PLANETMINTGO__DAO__MSG__BASE_INIT,\
      function_prefix__ ## reissue_rddlproposal,\
      function_prefix__ ## mint_token,\
      function_prefix__ ## reissue_rddlresult,\
      function_prefix__ ## distribution_result,\
      function_prefix__ ## distribution_request,\
      function_prefix__ ## update_params,\
      function_prefix__ ## report_pop_result,\
      function_prefix__ ## init_pop  }
void planetmintgo__dao__msg__reissue_rddlproposal(ProtobufCService *service,
                                                  const Planetmintgo__Dao__MsgReissueRDDLProposal *input,
                                                  Planetmintgo__Dao__MsgReissueRDDLProposalResponse_Closure closure,
                                                  void *closure_data);
void planetmintgo__dao__msg__mint_token(ProtobufCService *service,
                                        const Planetmintgo__Dao__MsgMintToken *input,
                                        Planetmintgo__Dao__MsgMintTokenResponse_Closure closure,
                                        void *closure_data);
void planetmintgo__dao__msg__reissue_rddlresult(ProtobufCService *service,
                                                const Planetmintgo__Dao__MsgReissueRDDLResult *input,
                                                Planetmintgo__Dao__MsgReissueRDDLResultResponse_Closure closure,
                                                void *closure_data);
void planetmintgo__dao__msg__distribution_result(ProtobufCService *service,
                                                 const Planetmintgo__Dao__MsgDistributionResult *input,
                                                 Planetmintgo__Dao__MsgDistributionResultResponse_Closure closure,
                                                 void *closure_data);
void planetmintgo__dao__msg__distribution_request(ProtobufCService *service,
                                                  const Planetmintgo__Dao__MsgDistributionRequest *input,
                                                  Planetmintgo__Dao__MsgDistributionRequestResponse_Closure closure,
                                                  void *closure_data);
void planetmintgo__dao__msg__update_params(ProtobufCService *service,
                                           const Planetmintgo__Dao__MsgUpdateParams *input,
                                           Planetmintgo__Dao__MsgUpdateParamsResponse_Closure closure,
                                           void *closure_data);
void planetmintgo__dao__msg__report_pop_result(ProtobufCService *service,
                                               const Planetmintgo__Dao__MsgReportPopResult *input,
                                               Planetmintgo__Dao__MsgReportPopResultResponse_Closure closure,
                                               void *closure_data);
void planetmintgo__dao__msg__init_pop(ProtobufCService *service,
                                      const Planetmintgo__Dao__MsgInitPop *input,
                                      Planetmintgo__Dao__MsgInitPopResponse_Closure closure,
                                      void *closure_data);

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_report_pop_result__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_report_pop_result_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_reissue_rddlproposal__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_reissue_rddlproposal_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_mint_token__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_mint_token_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_reissue_rddlresult__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_reissue_rddlresult_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_distribution_result__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_distribution_result_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_distribution_request__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_distribution_request_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_update_params__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_update_params_response__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_init_pop__descriptor;
extern const ProtobufCMessageDescriptor planetmintgo__dao__msg_init_pop_response__descriptor;
extern const ProtobufCServiceDescriptor planetmintgo__dao__msg__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_planetmintgo_2fdao_2ftx_2eproto__INCLUDED */
