/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: planetmintgo/dao/tx.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "planetmintgo/dao/tx.pb-c.h"
void   planetmintgo__dao__msg_report_pop_result__init
                     (Planetmintgo__Dao__MsgReportPopResult         *message)
{
  static const Planetmintgo__Dao__MsgReportPopResult init_value = PLANETMINTGO__DAO__MSG_REPORT_POP_RESULT__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_report_pop_result__get_packed_size
                     (const Planetmintgo__Dao__MsgReportPopResult *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_report_pop_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_report_pop_result__pack
                     (const Planetmintgo__Dao__MsgReportPopResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_report_pop_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_report_pop_result__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReportPopResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_report_pop_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgReportPopResult *
       planetmintgo__dao__msg_report_pop_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgReportPopResult *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_report_pop_result__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_report_pop_result__free_unpacked
                     (Planetmintgo__Dao__MsgReportPopResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_report_pop_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_report_pop_result_response__init
                     (Planetmintgo__Dao__MsgReportPopResultResponse         *message)
{
  static const Planetmintgo__Dao__MsgReportPopResultResponse init_value = PLANETMINTGO__DAO__MSG_REPORT_POP_RESULT_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_report_pop_result_response__get_packed_size
                     (const Planetmintgo__Dao__MsgReportPopResultResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_report_pop_result_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_report_pop_result_response__pack
                     (const Planetmintgo__Dao__MsgReportPopResultResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_report_pop_result_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_report_pop_result_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReportPopResultResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_report_pop_result_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgReportPopResultResponse *
       planetmintgo__dao__msg_report_pop_result_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgReportPopResultResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_report_pop_result_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_report_pop_result_response__free_unpacked
                     (Planetmintgo__Dao__MsgReportPopResultResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_report_pop_result_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_reissue_rddlproposal__init
                     (Planetmintgo__Dao__MsgReissueRDDLProposal         *message)
{
  static const Planetmintgo__Dao__MsgReissueRDDLProposal init_value = PLANETMINTGO__DAO__MSG_REISSUE_RDDLPROPOSAL__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_reissue_rddlproposal__get_packed_size
                     (const Planetmintgo__Dao__MsgReissueRDDLProposal *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlproposal__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_reissue_rddlproposal__pack
                     (const Planetmintgo__Dao__MsgReissueRDDLProposal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlproposal__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_reissue_rddlproposal__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReissueRDDLProposal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlproposal__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgReissueRDDLProposal *
       planetmintgo__dao__msg_reissue_rddlproposal__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgReissueRDDLProposal *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_reissue_rddlproposal__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_reissue_rddlproposal__free_unpacked
                     (Planetmintgo__Dao__MsgReissueRDDLProposal *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlproposal__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_reissue_rddlproposal_response__init
                     (Planetmintgo__Dao__MsgReissueRDDLProposalResponse         *message)
{
  static const Planetmintgo__Dao__MsgReissueRDDLProposalResponse init_value = PLANETMINTGO__DAO__MSG_REISSUE_RDDLPROPOSAL_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_reissue_rddlproposal_response__get_packed_size
                     (const Planetmintgo__Dao__MsgReissueRDDLProposalResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlproposal_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_reissue_rddlproposal_response__pack
                     (const Planetmintgo__Dao__MsgReissueRDDLProposalResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlproposal_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_reissue_rddlproposal_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReissueRDDLProposalResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlproposal_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgReissueRDDLProposalResponse *
       planetmintgo__dao__msg_reissue_rddlproposal_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgReissueRDDLProposalResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_reissue_rddlproposal_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_reissue_rddlproposal_response__free_unpacked
                     (Planetmintgo__Dao__MsgReissueRDDLProposalResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlproposal_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_mint_token__init
                     (Planetmintgo__Dao__MsgMintToken         *message)
{
  static const Planetmintgo__Dao__MsgMintToken init_value = PLANETMINTGO__DAO__MSG_MINT_TOKEN__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_mint_token__get_packed_size
                     (const Planetmintgo__Dao__MsgMintToken *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_mint_token__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_mint_token__pack
                     (const Planetmintgo__Dao__MsgMintToken *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_mint_token__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_mint_token__pack_to_buffer
                     (const Planetmintgo__Dao__MsgMintToken *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_mint_token__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgMintToken *
       planetmintgo__dao__msg_mint_token__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgMintToken *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_mint_token__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_mint_token__free_unpacked
                     (Planetmintgo__Dao__MsgMintToken *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_mint_token__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_mint_token_response__init
                     (Planetmintgo__Dao__MsgMintTokenResponse         *message)
{
  static const Planetmintgo__Dao__MsgMintTokenResponse init_value = PLANETMINTGO__DAO__MSG_MINT_TOKEN_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_mint_token_response__get_packed_size
                     (const Planetmintgo__Dao__MsgMintTokenResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_mint_token_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_mint_token_response__pack
                     (const Planetmintgo__Dao__MsgMintTokenResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_mint_token_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_mint_token_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgMintTokenResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_mint_token_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgMintTokenResponse *
       planetmintgo__dao__msg_mint_token_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgMintTokenResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_mint_token_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_mint_token_response__free_unpacked
                     (Planetmintgo__Dao__MsgMintTokenResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_mint_token_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_reissue_rddlresult__init
                     (Planetmintgo__Dao__MsgReissueRDDLResult         *message)
{
  static const Planetmintgo__Dao__MsgReissueRDDLResult init_value = PLANETMINTGO__DAO__MSG_REISSUE_RDDLRESULT__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_reissue_rddlresult__get_packed_size
                     (const Planetmintgo__Dao__MsgReissueRDDLResult *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlresult__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_reissue_rddlresult__pack
                     (const Planetmintgo__Dao__MsgReissueRDDLResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlresult__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_reissue_rddlresult__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReissueRDDLResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlresult__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgReissueRDDLResult *
       planetmintgo__dao__msg_reissue_rddlresult__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgReissueRDDLResult *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_reissue_rddlresult__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_reissue_rddlresult__free_unpacked
                     (Planetmintgo__Dao__MsgReissueRDDLResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlresult__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_reissue_rddlresult_response__init
                     (Planetmintgo__Dao__MsgReissueRDDLResultResponse         *message)
{
  static const Planetmintgo__Dao__MsgReissueRDDLResultResponse init_value = PLANETMINTGO__DAO__MSG_REISSUE_RDDLRESULT_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_reissue_rddlresult_response__get_packed_size
                     (const Planetmintgo__Dao__MsgReissueRDDLResultResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlresult_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_reissue_rddlresult_response__pack
                     (const Planetmintgo__Dao__MsgReissueRDDLResultResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlresult_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_reissue_rddlresult_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgReissueRDDLResultResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlresult_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgReissueRDDLResultResponse *
       planetmintgo__dao__msg_reissue_rddlresult_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgReissueRDDLResultResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_reissue_rddlresult_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_reissue_rddlresult_response__free_unpacked
                     (Planetmintgo__Dao__MsgReissueRDDLResultResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_reissue_rddlresult_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_distribution_result__init
                     (Planetmintgo__Dao__MsgDistributionResult         *message)
{
  static const Planetmintgo__Dao__MsgDistributionResult init_value = PLANETMINTGO__DAO__MSG_DISTRIBUTION_RESULT__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_distribution_result__get_packed_size
                     (const Planetmintgo__Dao__MsgDistributionResult *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_result__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_distribution_result__pack
                     (const Planetmintgo__Dao__MsgDistributionResult *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_result__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_distribution_result__pack_to_buffer
                     (const Planetmintgo__Dao__MsgDistributionResult *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_result__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgDistributionResult *
       planetmintgo__dao__msg_distribution_result__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgDistributionResult *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_distribution_result__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_distribution_result__free_unpacked
                     (Planetmintgo__Dao__MsgDistributionResult *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_result__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_distribution_result_response__init
                     (Planetmintgo__Dao__MsgDistributionResultResponse         *message)
{
  static const Planetmintgo__Dao__MsgDistributionResultResponse init_value = PLANETMINTGO__DAO__MSG_DISTRIBUTION_RESULT_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_distribution_result_response__get_packed_size
                     (const Planetmintgo__Dao__MsgDistributionResultResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_result_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_distribution_result_response__pack
                     (const Planetmintgo__Dao__MsgDistributionResultResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_result_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_distribution_result_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgDistributionResultResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_result_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgDistributionResultResponse *
       planetmintgo__dao__msg_distribution_result_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgDistributionResultResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_distribution_result_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_distribution_result_response__free_unpacked
                     (Planetmintgo__Dao__MsgDistributionResultResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_result_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_distribution_request__init
                     (Planetmintgo__Dao__MsgDistributionRequest         *message)
{
  static const Planetmintgo__Dao__MsgDistributionRequest init_value = PLANETMINTGO__DAO__MSG_DISTRIBUTION_REQUEST__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_distribution_request__get_packed_size
                     (const Planetmintgo__Dao__MsgDistributionRequest *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_distribution_request__pack
                     (const Planetmintgo__Dao__MsgDistributionRequest *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_distribution_request__pack_to_buffer
                     (const Planetmintgo__Dao__MsgDistributionRequest *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgDistributionRequest *
       planetmintgo__dao__msg_distribution_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgDistributionRequest *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_distribution_request__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_distribution_request__free_unpacked
                     (Planetmintgo__Dao__MsgDistributionRequest *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_distribution_request_response__init
                     (Planetmintgo__Dao__MsgDistributionRequestResponse         *message)
{
  static const Planetmintgo__Dao__MsgDistributionRequestResponse init_value = PLANETMINTGO__DAO__MSG_DISTRIBUTION_REQUEST_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_distribution_request_response__get_packed_size
                     (const Planetmintgo__Dao__MsgDistributionRequestResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_request_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_distribution_request_response__pack
                     (const Planetmintgo__Dao__MsgDistributionRequestResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_request_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_distribution_request_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgDistributionRequestResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_request_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgDistributionRequestResponse *
       planetmintgo__dao__msg_distribution_request_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgDistributionRequestResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_distribution_request_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_distribution_request_response__free_unpacked
                     (Planetmintgo__Dao__MsgDistributionRequestResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_distribution_request_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_update_params__init
                     (Planetmintgo__Dao__MsgUpdateParams         *message)
{
  static const Planetmintgo__Dao__MsgUpdateParams init_value = PLANETMINTGO__DAO__MSG_UPDATE_PARAMS__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_update_params__get_packed_size
                     (const Planetmintgo__Dao__MsgUpdateParams *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_params__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_update_params__pack
                     (const Planetmintgo__Dao__MsgUpdateParams *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_params__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_update_params__pack_to_buffer
                     (const Planetmintgo__Dao__MsgUpdateParams *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_params__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgUpdateParams *
       planetmintgo__dao__msg_update_params__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgUpdateParams *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_update_params__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_update_params__free_unpacked
                     (Planetmintgo__Dao__MsgUpdateParams *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_params__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_update_params_response__init
                     (Planetmintgo__Dao__MsgUpdateParamsResponse         *message)
{
  static const Planetmintgo__Dao__MsgUpdateParamsResponse init_value = PLANETMINTGO__DAO__MSG_UPDATE_PARAMS_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_update_params_response__get_packed_size
                     (const Planetmintgo__Dao__MsgUpdateParamsResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_params_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_update_params_response__pack
                     (const Planetmintgo__Dao__MsgUpdateParamsResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_params_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_update_params_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgUpdateParamsResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_params_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgUpdateParamsResponse *
       planetmintgo__dao__msg_update_params_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgUpdateParamsResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_update_params_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_update_params_response__free_unpacked
                     (Planetmintgo__Dao__MsgUpdateParamsResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_params_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_init_pop__init
                     (Planetmintgo__Dao__MsgInitPop         *message)
{
  static const Planetmintgo__Dao__MsgInitPop init_value = PLANETMINTGO__DAO__MSG_INIT_POP__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_init_pop__get_packed_size
                     (const Planetmintgo__Dao__MsgInitPop *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_init_pop__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_init_pop__pack
                     (const Planetmintgo__Dao__MsgInitPop *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_init_pop__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_init_pop__pack_to_buffer
                     (const Planetmintgo__Dao__MsgInitPop *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_init_pop__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgInitPop *
       planetmintgo__dao__msg_init_pop__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgInitPop *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_init_pop__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_init_pop__free_unpacked
                     (Planetmintgo__Dao__MsgInitPop *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_init_pop__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_init_pop_response__init
                     (Planetmintgo__Dao__MsgInitPopResponse         *message)
{
  static const Planetmintgo__Dao__MsgInitPopResponse init_value = PLANETMINTGO__DAO__MSG_INIT_POP_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_init_pop_response__get_packed_size
                     (const Planetmintgo__Dao__MsgInitPopResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_init_pop_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_init_pop_response__pack
                     (const Planetmintgo__Dao__MsgInitPopResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_init_pop_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_init_pop_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgInitPopResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_init_pop_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgInitPopResponse *
       planetmintgo__dao__msg_init_pop_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgInitPopResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_init_pop_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_init_pop_response__free_unpacked
                     (Planetmintgo__Dao__MsgInitPopResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_init_pop_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_create_redeem_claim__init
                     (Planetmintgo__Dao__MsgCreateRedeemClaim         *message)
{
  static const Planetmintgo__Dao__MsgCreateRedeemClaim init_value = PLANETMINTGO__DAO__MSG_CREATE_REDEEM_CLAIM__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_create_redeem_claim__get_packed_size
                     (const Planetmintgo__Dao__MsgCreateRedeemClaim *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_create_redeem_claim__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_create_redeem_claim__pack
                     (const Planetmintgo__Dao__MsgCreateRedeemClaim *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_create_redeem_claim__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_create_redeem_claim__pack_to_buffer
                     (const Planetmintgo__Dao__MsgCreateRedeemClaim *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_create_redeem_claim__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgCreateRedeemClaim *
       planetmintgo__dao__msg_create_redeem_claim__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgCreateRedeemClaim *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_create_redeem_claim__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_create_redeem_claim__free_unpacked
                     (Planetmintgo__Dao__MsgCreateRedeemClaim *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_create_redeem_claim__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_create_redeem_claim_response__init
                     (Planetmintgo__Dao__MsgCreateRedeemClaimResponse         *message)
{
  static const Planetmintgo__Dao__MsgCreateRedeemClaimResponse init_value = PLANETMINTGO__DAO__MSG_CREATE_REDEEM_CLAIM_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_create_redeem_claim_response__get_packed_size
                     (const Planetmintgo__Dao__MsgCreateRedeemClaimResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_create_redeem_claim_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_create_redeem_claim_response__pack
                     (const Planetmintgo__Dao__MsgCreateRedeemClaimResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_create_redeem_claim_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_create_redeem_claim_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgCreateRedeemClaimResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_create_redeem_claim_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgCreateRedeemClaimResponse *
       planetmintgo__dao__msg_create_redeem_claim_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgCreateRedeemClaimResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_create_redeem_claim_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_create_redeem_claim_response__free_unpacked
                     (Planetmintgo__Dao__MsgCreateRedeemClaimResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_create_redeem_claim_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_update_redeem_claim__init
                     (Planetmintgo__Dao__MsgUpdateRedeemClaim         *message)
{
  static const Planetmintgo__Dao__MsgUpdateRedeemClaim init_value = PLANETMINTGO__DAO__MSG_UPDATE_REDEEM_CLAIM__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_update_redeem_claim__get_packed_size
                     (const Planetmintgo__Dao__MsgUpdateRedeemClaim *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_redeem_claim__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_update_redeem_claim__pack
                     (const Planetmintgo__Dao__MsgUpdateRedeemClaim *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_redeem_claim__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_update_redeem_claim__pack_to_buffer
                     (const Planetmintgo__Dao__MsgUpdateRedeemClaim *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_redeem_claim__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgUpdateRedeemClaim *
       planetmintgo__dao__msg_update_redeem_claim__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgUpdateRedeemClaim *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_update_redeem_claim__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_update_redeem_claim__free_unpacked
                     (Planetmintgo__Dao__MsgUpdateRedeemClaim *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_redeem_claim__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_update_redeem_claim_response__init
                     (Planetmintgo__Dao__MsgUpdateRedeemClaimResponse         *message)
{
  static const Planetmintgo__Dao__MsgUpdateRedeemClaimResponse init_value = PLANETMINTGO__DAO__MSG_UPDATE_REDEEM_CLAIM_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_update_redeem_claim_response__get_packed_size
                     (const Planetmintgo__Dao__MsgUpdateRedeemClaimResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_redeem_claim_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_update_redeem_claim_response__pack
                     (const Planetmintgo__Dao__MsgUpdateRedeemClaimResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_redeem_claim_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_update_redeem_claim_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgUpdateRedeemClaimResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_redeem_claim_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgUpdateRedeemClaimResponse *
       planetmintgo__dao__msg_update_redeem_claim_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgUpdateRedeemClaimResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_update_redeem_claim_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_update_redeem_claim_response__free_unpacked
                     (Planetmintgo__Dao__MsgUpdateRedeemClaimResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_update_redeem_claim_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_confirm_redeem_claim__init
                     (Planetmintgo__Dao__MsgConfirmRedeemClaim         *message)
{
  static const Planetmintgo__Dao__MsgConfirmRedeemClaim init_value = PLANETMINTGO__DAO__MSG_CONFIRM_REDEEM_CLAIM__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_confirm_redeem_claim__get_packed_size
                     (const Planetmintgo__Dao__MsgConfirmRedeemClaim *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_confirm_redeem_claim__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_confirm_redeem_claim__pack
                     (const Planetmintgo__Dao__MsgConfirmRedeemClaim *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_confirm_redeem_claim__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_confirm_redeem_claim__pack_to_buffer
                     (const Planetmintgo__Dao__MsgConfirmRedeemClaim *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_confirm_redeem_claim__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgConfirmRedeemClaim *
       planetmintgo__dao__msg_confirm_redeem_claim__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgConfirmRedeemClaim *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_confirm_redeem_claim__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_confirm_redeem_claim__free_unpacked
                     (Planetmintgo__Dao__MsgConfirmRedeemClaim *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_confirm_redeem_claim__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   planetmintgo__dao__msg_confirm_redeem_claim_response__init
                     (Planetmintgo__Dao__MsgConfirmRedeemClaimResponse         *message)
{
  static const Planetmintgo__Dao__MsgConfirmRedeemClaimResponse init_value = PLANETMINTGO__DAO__MSG_CONFIRM_REDEEM_CLAIM_RESPONSE__INIT;
  *message = init_value;
}
size_t planetmintgo__dao__msg_confirm_redeem_claim_response__get_packed_size
                     (const Planetmintgo__Dao__MsgConfirmRedeemClaimResponse *message)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_confirm_redeem_claim_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t planetmintgo__dao__msg_confirm_redeem_claim_response__pack
                     (const Planetmintgo__Dao__MsgConfirmRedeemClaimResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_confirm_redeem_claim_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t planetmintgo__dao__msg_confirm_redeem_claim_response__pack_to_buffer
                     (const Planetmintgo__Dao__MsgConfirmRedeemClaimResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &planetmintgo__dao__msg_confirm_redeem_claim_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Planetmintgo__Dao__MsgConfirmRedeemClaimResponse *
       planetmintgo__dao__msg_confirm_redeem_claim_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Planetmintgo__Dao__MsgConfirmRedeemClaimResponse *)
     protobuf_c_message_unpack (&planetmintgo__dao__msg_confirm_redeem_claim_response__descriptor,
                                allocator, len, data);
}
void   planetmintgo__dao__msg_confirm_redeem_claim_response__free_unpacked
                     (Planetmintgo__Dao__MsgConfirmRedeemClaimResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &planetmintgo__dao__msg_confirm_redeem_claim_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor planetmintgo__dao__msg_report_pop_result__field_descriptors[2] =
{
  {
    "creator",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReportPopResult, creator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "challenge",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReportPopResult, challenge),
    &planetmintgo__dao__challenge__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__msg_report_pop_result__field_indices_by_name[] = {
  1,   /* field[1] = challenge */
  0,   /* field[0] = creator */
};
static const ProtobufCIntRange planetmintgo__dao__msg_report_pop_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__msg_report_pop_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgReportPopResult",
  "MsgReportPopResult",
  "Planetmintgo__Dao__MsgReportPopResult",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgReportPopResult),
  2,
  planetmintgo__dao__msg_report_pop_result__field_descriptors,
  planetmintgo__dao__msg_report_pop_result__field_indices_by_name,
  1,  planetmintgo__dao__msg_report_pop_result__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_report_pop_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define planetmintgo__dao__msg_report_pop_result_response__field_descriptors NULL
#define planetmintgo__dao__msg_report_pop_result_response__field_indices_by_name NULL
#define planetmintgo__dao__msg_report_pop_result_response__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__msg_report_pop_result_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgReportPopResultResponse",
  "MsgReportPopResultResponse",
  "Planetmintgo__Dao__MsgReportPopResultResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgReportPopResultResponse),
  0,
  planetmintgo__dao__msg_report_pop_result_response__field_descriptors,
  planetmintgo__dao__msg_report_pop_result_response__field_indices_by_name,
  0,  planetmintgo__dao__msg_report_pop_result_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_report_pop_result_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__msg_reissue_rddlproposal__field_descriptors[6] =
{
  {
    "creator",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReissueRDDLProposal, creator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proposer",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReissueRDDLProposal, proposer),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReissueRDDLProposal, command),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blockHeight",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReissueRDDLProposal, blockheight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "firstIncludedPop",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReissueRDDLProposal, firstincludedpop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lastIncludedPop",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReissueRDDLProposal, lastincludedpop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__msg_reissue_rddlproposal__field_indices_by_name[] = {
  3,   /* field[3] = blockHeight */
  2,   /* field[2] = command */
  0,   /* field[0] = creator */
  4,   /* field[4] = firstIncludedPop */
  5,   /* field[5] = lastIncludedPop */
  1,   /* field[1] = proposer */
};
static const ProtobufCIntRange planetmintgo__dao__msg_reissue_rddlproposal__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__msg_reissue_rddlproposal__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgReissueRDDLProposal",
  "MsgReissueRDDLProposal",
  "Planetmintgo__Dao__MsgReissueRDDLProposal",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgReissueRDDLProposal),
  6,
  planetmintgo__dao__msg_reissue_rddlproposal__field_descriptors,
  planetmintgo__dao__msg_reissue_rddlproposal__field_indices_by_name,
  1,  planetmintgo__dao__msg_reissue_rddlproposal__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_reissue_rddlproposal__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define planetmintgo__dao__msg_reissue_rddlproposal_response__field_descriptors NULL
#define planetmintgo__dao__msg_reissue_rddlproposal_response__field_indices_by_name NULL
#define planetmintgo__dao__msg_reissue_rddlproposal_response__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__msg_reissue_rddlproposal_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgReissueRDDLProposalResponse",
  "MsgReissueRDDLProposalResponse",
  "Planetmintgo__Dao__MsgReissueRDDLProposalResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgReissueRDDLProposalResponse),
  0,
  planetmintgo__dao__msg_reissue_rddlproposal_response__field_descriptors,
  planetmintgo__dao__msg_reissue_rddlproposal_response__field_indices_by_name,
  0,  planetmintgo__dao__msg_reissue_rddlproposal_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_reissue_rddlproposal_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__msg_mint_token__field_descriptors[2] =
{
  {
    "creator",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgMintToken, creator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mintRequest",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgMintToken, mintrequest),
    &planetmintgo__dao__mint_request__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__msg_mint_token__field_indices_by_name[] = {
  0,   /* field[0] = creator */
  1,   /* field[1] = mintRequest */
};
static const ProtobufCIntRange planetmintgo__dao__msg_mint_token__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__msg_mint_token__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgMintToken",
  "MsgMintToken",
  "Planetmintgo__Dao__MsgMintToken",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgMintToken),
  2,
  planetmintgo__dao__msg_mint_token__field_descriptors,
  planetmintgo__dao__msg_mint_token__field_indices_by_name,
  1,  planetmintgo__dao__msg_mint_token__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_mint_token__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define planetmintgo__dao__msg_mint_token_response__field_descriptors NULL
#define planetmintgo__dao__msg_mint_token_response__field_indices_by_name NULL
#define planetmintgo__dao__msg_mint_token_response__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__msg_mint_token_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgMintTokenResponse",
  "MsgMintTokenResponse",
  "Planetmintgo__Dao__MsgMintTokenResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgMintTokenResponse),
  0,
  planetmintgo__dao__msg_mint_token_response__field_descriptors,
  planetmintgo__dao__msg_mint_token_response__field_indices_by_name,
  0,  planetmintgo__dao__msg_mint_token_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_mint_token_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__msg_reissue_rddlresult__field_descriptors[4] =
{
  {
    "creator",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReissueRDDLResult, creator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proposer",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReissueRDDLResult, proposer),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "txID",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReissueRDDLResult, txid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blockHeight",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgReissueRDDLResult, blockheight),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__msg_reissue_rddlresult__field_indices_by_name[] = {
  3,   /* field[3] = blockHeight */
  0,   /* field[0] = creator */
  1,   /* field[1] = proposer */
  2,   /* field[2] = txID */
};
static const ProtobufCIntRange planetmintgo__dao__msg_reissue_rddlresult__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__msg_reissue_rddlresult__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgReissueRDDLResult",
  "MsgReissueRDDLResult",
  "Planetmintgo__Dao__MsgReissueRDDLResult",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgReissueRDDLResult),
  4,
  planetmintgo__dao__msg_reissue_rddlresult__field_descriptors,
  planetmintgo__dao__msg_reissue_rddlresult__field_indices_by_name,
  1,  planetmintgo__dao__msg_reissue_rddlresult__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_reissue_rddlresult__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define planetmintgo__dao__msg_reissue_rddlresult_response__field_descriptors NULL
#define planetmintgo__dao__msg_reissue_rddlresult_response__field_indices_by_name NULL
#define planetmintgo__dao__msg_reissue_rddlresult_response__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__msg_reissue_rddlresult_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgReissueRDDLResultResponse",
  "MsgReissueRDDLResultResponse",
  "Planetmintgo__Dao__MsgReissueRDDLResultResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgReissueRDDLResultResponse),
  0,
  planetmintgo__dao__msg_reissue_rddlresult_response__field_descriptors,
  planetmintgo__dao__msg_reissue_rddlresult_response__field_indices_by_name,
  0,  planetmintgo__dao__msg_reissue_rddlresult_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_reissue_rddlresult_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__msg_distribution_result__field_descriptors[7] =
{
  {
    "creator",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgDistributionResult, creator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lastPop",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgDistributionResult, lastpop),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "daoTxID",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgDistributionResult, daotxid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "investorTxID",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgDistributionResult, investortxid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "popTxID",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgDistributionResult, poptxid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "earlyInvestorTxID",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgDistributionResult, earlyinvestortxid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "strategicTxID",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgDistributionResult, strategictxid),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__msg_distribution_result__field_indices_by_name[] = {
  0,   /* field[0] = creator */
  2,   /* field[2] = daoTxID */
  5,   /* field[5] = earlyInvestorTxID */
  3,   /* field[3] = investorTxID */
  1,   /* field[1] = lastPop */
  4,   /* field[4] = popTxID */
  6,   /* field[6] = strategicTxID */
};
static const ProtobufCIntRange planetmintgo__dao__msg_distribution_result__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__msg_distribution_result__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgDistributionResult",
  "MsgDistributionResult",
  "Planetmintgo__Dao__MsgDistributionResult",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgDistributionResult),
  7,
  planetmintgo__dao__msg_distribution_result__field_descriptors,
  planetmintgo__dao__msg_distribution_result__field_indices_by_name,
  1,  planetmintgo__dao__msg_distribution_result__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_distribution_result__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define planetmintgo__dao__msg_distribution_result_response__field_descriptors NULL
#define planetmintgo__dao__msg_distribution_result_response__field_indices_by_name NULL
#define planetmintgo__dao__msg_distribution_result_response__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__msg_distribution_result_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgDistributionResultResponse",
  "MsgDistributionResultResponse",
  "Planetmintgo__Dao__MsgDistributionResultResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgDistributionResultResponse),
  0,
  planetmintgo__dao__msg_distribution_result_response__field_descriptors,
  planetmintgo__dao__msg_distribution_result_response__field_indices_by_name,
  0,  planetmintgo__dao__msg_distribution_result_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_distribution_result_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__msg_distribution_request__field_descriptors[2] =
{
  {
    "creator",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgDistributionRequest, creator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distribution",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgDistributionRequest, distribution),
    &planetmintgo__dao__distribution_order__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__msg_distribution_request__field_indices_by_name[] = {
  0,   /* field[0] = creator */
  1,   /* field[1] = distribution */
};
static const ProtobufCIntRange planetmintgo__dao__msg_distribution_request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__msg_distribution_request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgDistributionRequest",
  "MsgDistributionRequest",
  "Planetmintgo__Dao__MsgDistributionRequest",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgDistributionRequest),
  2,
  planetmintgo__dao__msg_distribution_request__field_descriptors,
  planetmintgo__dao__msg_distribution_request__field_indices_by_name,
  1,  planetmintgo__dao__msg_distribution_request__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_distribution_request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define planetmintgo__dao__msg_distribution_request_response__field_descriptors NULL
#define planetmintgo__dao__msg_distribution_request_response__field_indices_by_name NULL
#define planetmintgo__dao__msg_distribution_request_response__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__msg_distribution_request_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgDistributionRequestResponse",
  "MsgDistributionRequestResponse",
  "Planetmintgo__Dao__MsgDistributionRequestResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgDistributionRequestResponse),
  0,
  planetmintgo__dao__msg_distribution_request_response__field_descriptors,
  planetmintgo__dao__msg_distribution_request_response__field_indices_by_name,
  0,  planetmintgo__dao__msg_distribution_request_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_distribution_request_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__msg_update_params__field_descriptors[2] =
{
  {
    "authority",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgUpdateParams, authority),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "params",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgUpdateParams, params),
    &planetmintgo__dao__params__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__msg_update_params__field_indices_by_name[] = {
  0,   /* field[0] = authority */
  1,   /* field[1] = params */
};
static const ProtobufCIntRange planetmintgo__dao__msg_update_params__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__msg_update_params__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgUpdateParams",
  "MsgUpdateParams",
  "Planetmintgo__Dao__MsgUpdateParams",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgUpdateParams),
  2,
  planetmintgo__dao__msg_update_params__field_descriptors,
  planetmintgo__dao__msg_update_params__field_indices_by_name,
  1,  planetmintgo__dao__msg_update_params__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_update_params__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define planetmintgo__dao__msg_update_params_response__field_descriptors NULL
#define planetmintgo__dao__msg_update_params_response__field_indices_by_name NULL
#define planetmintgo__dao__msg_update_params_response__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__msg_update_params_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgUpdateParamsResponse",
  "MsgUpdateParamsResponse",
  "Planetmintgo__Dao__MsgUpdateParamsResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgUpdateParamsResponse),
  0,
  planetmintgo__dao__msg_update_params_response__field_descriptors,
  planetmintgo__dao__msg_update_params_response__field_indices_by_name,
  0,  planetmintgo__dao__msg_update_params_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_update_params_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__msg_init_pop__field_descriptors[5] =
{
  {
    "creator",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgInitPop, creator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "initiator",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgInitPop, initiator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "challenger",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgInitPop, challenger),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "challengee",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgInitPop, challengee),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgInitPop, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__msg_init_pop__field_indices_by_name[] = {
  3,   /* field[3] = challengee */
  2,   /* field[2] = challenger */
  0,   /* field[0] = creator */
  4,   /* field[4] = height */
  1,   /* field[1] = initiator */
};
static const ProtobufCIntRange planetmintgo__dao__msg_init_pop__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__msg_init_pop__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgInitPop",
  "MsgInitPop",
  "Planetmintgo__Dao__MsgInitPop",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgInitPop),
  5,
  planetmintgo__dao__msg_init_pop__field_descriptors,
  planetmintgo__dao__msg_init_pop__field_indices_by_name,
  1,  planetmintgo__dao__msg_init_pop__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_init_pop__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define planetmintgo__dao__msg_init_pop_response__field_descriptors NULL
#define planetmintgo__dao__msg_init_pop_response__field_indices_by_name NULL
#define planetmintgo__dao__msg_init_pop_response__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__msg_init_pop_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgInitPopResponse",
  "MsgInitPopResponse",
  "Planetmintgo__Dao__MsgInitPopResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgInitPopResponse),
  0,
  planetmintgo__dao__msg_init_pop_response__field_descriptors,
  planetmintgo__dao__msg_init_pop_response__field_indices_by_name,
  0,  planetmintgo__dao__msg_init_pop_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_init_pop_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__msg_create_redeem_claim__field_descriptors[2] =
{
  {
    "creator",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgCreateRedeemClaim, creator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beneficiary",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgCreateRedeemClaim, beneficiary),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__msg_create_redeem_claim__field_indices_by_name[] = {
  1,   /* field[1] = beneficiary */
  0,   /* field[0] = creator */
};
static const ProtobufCIntRange planetmintgo__dao__msg_create_redeem_claim__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__msg_create_redeem_claim__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgCreateRedeemClaim",
  "MsgCreateRedeemClaim",
  "Planetmintgo__Dao__MsgCreateRedeemClaim",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgCreateRedeemClaim),
  2,
  planetmintgo__dao__msg_create_redeem_claim__field_descriptors,
  planetmintgo__dao__msg_create_redeem_claim__field_indices_by_name,
  1,  planetmintgo__dao__msg_create_redeem_claim__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_create_redeem_claim__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define planetmintgo__dao__msg_create_redeem_claim_response__field_descriptors NULL
#define planetmintgo__dao__msg_create_redeem_claim_response__field_indices_by_name NULL
#define planetmintgo__dao__msg_create_redeem_claim_response__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__msg_create_redeem_claim_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgCreateRedeemClaimResponse",
  "MsgCreateRedeemClaimResponse",
  "Planetmintgo__Dao__MsgCreateRedeemClaimResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgCreateRedeemClaimResponse),
  0,
  planetmintgo__dao__msg_create_redeem_claim_response__field_descriptors,
  planetmintgo__dao__msg_create_redeem_claim_response__field_indices_by_name,
  0,  planetmintgo__dao__msg_create_redeem_claim_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_create_redeem_claim_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__msg_update_redeem_claim__field_descriptors[4] =
{
  {
    "creator",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgUpdateRedeemClaim, creator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgUpdateRedeemClaim, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beneficiary",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgUpdateRedeemClaim, beneficiary),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "liquidTxHash",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgUpdateRedeemClaim, liquidtxhash),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__msg_update_redeem_claim__field_indices_by_name[] = {
  2,   /* field[2] = beneficiary */
  0,   /* field[0] = creator */
  1,   /* field[1] = id */
  3,   /* field[3] = liquidTxHash */
};
static const ProtobufCIntRange planetmintgo__dao__msg_update_redeem_claim__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__msg_update_redeem_claim__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgUpdateRedeemClaim",
  "MsgUpdateRedeemClaim",
  "Planetmintgo__Dao__MsgUpdateRedeemClaim",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgUpdateRedeemClaim),
  4,
  planetmintgo__dao__msg_update_redeem_claim__field_descriptors,
  planetmintgo__dao__msg_update_redeem_claim__field_indices_by_name,
  1,  planetmintgo__dao__msg_update_redeem_claim__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_update_redeem_claim__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define planetmintgo__dao__msg_update_redeem_claim_response__field_descriptors NULL
#define planetmintgo__dao__msg_update_redeem_claim_response__field_indices_by_name NULL
#define planetmintgo__dao__msg_update_redeem_claim_response__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__msg_update_redeem_claim_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgUpdateRedeemClaimResponse",
  "MsgUpdateRedeemClaimResponse",
  "Planetmintgo__Dao__MsgUpdateRedeemClaimResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgUpdateRedeemClaimResponse),
  0,
  planetmintgo__dao__msg_update_redeem_claim_response__field_descriptors,
  planetmintgo__dao__msg_update_redeem_claim_response__field_indices_by_name,
  0,  planetmintgo__dao__msg_update_redeem_claim_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_update_redeem_claim_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor planetmintgo__dao__msg_confirm_redeem_claim__field_descriptors[3] =
{
  {
    "creator",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgConfirmRedeemClaim, creator),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgConfirmRedeemClaim, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "beneficiary",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Planetmintgo__Dao__MsgConfirmRedeemClaim, beneficiary),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned planetmintgo__dao__msg_confirm_redeem_claim__field_indices_by_name[] = {
  2,   /* field[2] = beneficiary */
  0,   /* field[0] = creator */
  1,   /* field[1] = id */
};
static const ProtobufCIntRange planetmintgo__dao__msg_confirm_redeem_claim__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor planetmintgo__dao__msg_confirm_redeem_claim__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgConfirmRedeemClaim",
  "MsgConfirmRedeemClaim",
  "Planetmintgo__Dao__MsgConfirmRedeemClaim",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgConfirmRedeemClaim),
  3,
  planetmintgo__dao__msg_confirm_redeem_claim__field_descriptors,
  planetmintgo__dao__msg_confirm_redeem_claim__field_indices_by_name,
  1,  planetmintgo__dao__msg_confirm_redeem_claim__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_confirm_redeem_claim__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define planetmintgo__dao__msg_confirm_redeem_claim_response__field_descriptors NULL
#define planetmintgo__dao__msg_confirm_redeem_claim_response__field_indices_by_name NULL
#define planetmintgo__dao__msg_confirm_redeem_claim_response__number_ranges NULL
const ProtobufCMessageDescriptor planetmintgo__dao__msg_confirm_redeem_claim_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.MsgConfirmRedeemClaimResponse",
  "MsgConfirmRedeemClaimResponse",
  "Planetmintgo__Dao__MsgConfirmRedeemClaimResponse",
  "planetmintgo.dao",
  sizeof(Planetmintgo__Dao__MsgConfirmRedeemClaimResponse),
  0,
  planetmintgo__dao__msg_confirm_redeem_claim_response__field_descriptors,
  planetmintgo__dao__msg_confirm_redeem_claim_response__field_indices_by_name,
  0,  planetmintgo__dao__msg_confirm_redeem_claim_response__number_ranges,
  (ProtobufCMessageInit) planetmintgo__dao__msg_confirm_redeem_claim_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor planetmintgo__dao__msg__method_descriptors[11] =
{
  { "ReissueRDDLProposal", &planetmintgo__dao__msg_reissue_rddlproposal__descriptor, &planetmintgo__dao__msg_reissue_rddlproposal_response__descriptor },
  { "MintToken", &planetmintgo__dao__msg_mint_token__descriptor, &planetmintgo__dao__msg_mint_token_response__descriptor },
  { "ReissueRDDLResult", &planetmintgo__dao__msg_reissue_rddlresult__descriptor, &planetmintgo__dao__msg_reissue_rddlresult_response__descriptor },
  { "DistributionResult", &planetmintgo__dao__msg_distribution_result__descriptor, &planetmintgo__dao__msg_distribution_result_response__descriptor },
  { "DistributionRequest", &planetmintgo__dao__msg_distribution_request__descriptor, &planetmintgo__dao__msg_distribution_request_response__descriptor },
  { "UpdateParams", &planetmintgo__dao__msg_update_params__descriptor, &planetmintgo__dao__msg_update_params_response__descriptor },
  { "ReportPopResult", &planetmintgo__dao__msg_report_pop_result__descriptor, &planetmintgo__dao__msg_report_pop_result_response__descriptor },
  { "InitPop", &planetmintgo__dao__msg_init_pop__descriptor, &planetmintgo__dao__msg_init_pop_response__descriptor },
  { "CreateRedeemClaim", &planetmintgo__dao__msg_create_redeem_claim__descriptor, &planetmintgo__dao__msg_create_redeem_claim_response__descriptor },
  { "UpdateRedeemClaim", &planetmintgo__dao__msg_update_redeem_claim__descriptor, &planetmintgo__dao__msg_update_redeem_claim_response__descriptor },
  { "ConfirmRedeemClaim", &planetmintgo__dao__msg_confirm_redeem_claim__descriptor, &planetmintgo__dao__msg_confirm_redeem_claim_response__descriptor },
};
const unsigned planetmintgo__dao__msg__method_indices_by_name[] = {
  10,        /* ConfirmRedeemClaim */
  8,        /* CreateRedeemClaim */
  4,        /* DistributionRequest */
  3,        /* DistributionResult */
  7,        /* InitPop */
  1,        /* MintToken */
  0,        /* ReissueRDDLProposal */
  2,        /* ReissueRDDLResult */
  6,        /* ReportPopResult */
  5,        /* UpdateParams */
  9         /* UpdateRedeemClaim */
};
const ProtobufCServiceDescriptor planetmintgo__dao__msg__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "planetmintgo.dao.Msg",
  "Msg",
  "Planetmintgo__Dao__Msg",
  "planetmintgo.dao",
  11,
  planetmintgo__dao__msg__method_descriptors,
  planetmintgo__dao__msg__method_indices_by_name
};
void planetmintgo__dao__msg__reissue_rddlproposal(ProtobufCService *service,
                                                  const Planetmintgo__Dao__MsgReissueRDDLProposal *input,
                                                  Planetmintgo__Dao__MsgReissueRDDLProposalResponse_Closure closure,
                                                  void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__msg__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__msg__mint_token(ProtobufCService *service,
                                        const Planetmintgo__Dao__MsgMintToken *input,
                                        Planetmintgo__Dao__MsgMintTokenResponse_Closure closure,
                                        void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__msg__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__msg__reissue_rddlresult(ProtobufCService *service,
                                                const Planetmintgo__Dao__MsgReissueRDDLResult *input,
                                                Planetmintgo__Dao__MsgReissueRDDLResultResponse_Closure closure,
                                                void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__msg__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__msg__distribution_result(ProtobufCService *service,
                                                 const Planetmintgo__Dao__MsgDistributionResult *input,
                                                 Planetmintgo__Dao__MsgDistributionResultResponse_Closure closure,
                                                 void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__msg__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__msg__distribution_request(ProtobufCService *service,
                                                  const Planetmintgo__Dao__MsgDistributionRequest *input,
                                                  Planetmintgo__Dao__MsgDistributionRequestResponse_Closure closure,
                                                  void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__msg__descriptor);
  service->invoke(service, 4, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__msg__update_params(ProtobufCService *service,
                                           const Planetmintgo__Dao__MsgUpdateParams *input,
                                           Planetmintgo__Dao__MsgUpdateParamsResponse_Closure closure,
                                           void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__msg__descriptor);
  service->invoke(service, 5, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__msg__report_pop_result(ProtobufCService *service,
                                               const Planetmintgo__Dao__MsgReportPopResult *input,
                                               Planetmintgo__Dao__MsgReportPopResultResponse_Closure closure,
                                               void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__msg__descriptor);
  service->invoke(service, 6, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__msg__init_pop(ProtobufCService *service,
                                      const Planetmintgo__Dao__MsgInitPop *input,
                                      Planetmintgo__Dao__MsgInitPopResponse_Closure closure,
                                      void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__msg__descriptor);
  service->invoke(service, 7, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__msg__create_redeem_claim(ProtobufCService *service,
                                                 const Planetmintgo__Dao__MsgCreateRedeemClaim *input,
                                                 Planetmintgo__Dao__MsgCreateRedeemClaimResponse_Closure closure,
                                                 void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__msg__descriptor);
  service->invoke(service, 8, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__msg__update_redeem_claim(ProtobufCService *service,
                                                 const Planetmintgo__Dao__MsgUpdateRedeemClaim *input,
                                                 Planetmintgo__Dao__MsgUpdateRedeemClaimResponse_Closure closure,
                                                 void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__msg__descriptor);
  service->invoke(service, 9, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__msg__confirm_redeem_claim(ProtobufCService *service,
                                                  const Planetmintgo__Dao__MsgConfirmRedeemClaim *input,
                                                  Planetmintgo__Dao__MsgConfirmRedeemClaimResponse_Closure closure,
                                                  void *closure_data)
{
  assert(service->descriptor == &planetmintgo__dao__msg__descriptor);
  service->invoke(service, 10, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void planetmintgo__dao__msg__init (Planetmintgo__Dao__Msg_Service *service,
                                   Planetmintgo__Dao__Msg_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &planetmintgo__dao__msg__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
