# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planetmintgo/dao/genesis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from gogoproto import gogo_pb2 as gogoproto_dot_gogo__pb2
from planetmintgo.dao import params_pb2 as planetmintgo_dot_dao_dot_params__pb2
from planetmintgo.dao import redeem_claim_pb2 as planetmintgo_dot_dao_dot_redeem__claim__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eplanetmintgo/dao/genesis.proto\x12\x10planetmintgo.dao\x1a\x14gogoproto/gogo.proto\x1a\x1dplanetmintgo/dao/params.proto\x1a#planetmintgo/dao/redeem_claim.proto\">\n\x0cGenesisState\x12.\n\x06params\x18\x01 \x01(\x0b\x32\x18.planetmintgo.dao.ParamsB\x04\xc8\xde\x1f\x00\x42\x31Z/github.com/planetmint/planetmint-go/x/dao/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planetmintgo.dao.genesis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/planetmint/planetmint-go/x/dao/types'
  _GENESISSTATE.fields_by_name['params']._options = None
  _GENESISSTATE.fields_by_name['params']._serialized_options = b'\310\336\037\000'
  _GENESISSTATE._serialized_start=142
  _GENESISSTATE._serialized_end=204
# @@protoc_insertion_point(module_scope)
