# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: planetmintgo/dao/reissuance.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!planetmintgo/dao/reissuance.proto\x12\x10planetmintgo.dao\"\x85\x01\n\nReissuance\x12\x10\n\x08proposer\x18\x01 \x01(\t\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\t\x12\x0c\n\x04txID\x18\x03 \x01(\t\x12\x13\n\x0b\x62lockHeight\x18\x04 \x01(\x03\x12\x18\n\x10\x66irstIncludedPop\x18\x05 \x01(\x03\x12\x17\n\x0flastIncludedPop\x18\x06 \x01(\x03\x42\x31Z/github.com/planetmint/planetmint-go/x/dao/typesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'planetmintgo.dao.reissuance_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z/github.com/planetmint/planetmint-go/x/dao/types'
  _REISSUANCE._serialized_start=56
  _REISSUANCE._serialized_end=189
# @@protoc_insertion_point(module_scope)
