/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "cosmos_proto/cosmos.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_proto_InterfaceDescriptor, cosmos_proto_InterfaceDescriptor, AUTO)


PB_BIND(cosmos_proto_ScalarDescriptor, cosmos_proto_ScalarDescriptor, AUTO)









