/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9-dev */

#ifndef PB_COSMOS_MSG_V1_COSMOS_MSG_V1_MSG_PB_H_INCLUDED
#define PB_COSMOS_MSG_V1_COSMOS_MSG_V1_MSG_PB_H_INCLUDED
#define PB_NO_STATIC_ASSERT 1 
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Extensions */
/* Extension field cosmos_msg_v1_service was skipped because only "optional"
   type of extension fields is currently supported. */
/* Extension field cosmos_msg_v1_signer was skipped because only "optional"
   type of extension fields is currently supported. */

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
