---
# Run unit tests using CTest
name: Tests

on:
    schedule:
        - cron: "0 3 * * *"
    push:
        branches:
            - "*"
        tags:
            - "v*.*.*"
    pull_request:
        branches:
            - "main"

jobs:
    unit-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - name: Install Protobuf
              run: sudo apt install libprotobuf-c-dev libprotobuf-dev protobuf-compiler cmake tree gcc g++
            - name: Build and Test
              run: |
                  mkdir build
                  cd build
                  cmake ../
                  make
                  ctest
