/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9-dev */

#include "cosmos/crypto/multisig/v1beta1/multisig.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(cosmos_crypto_multisig_v1beta1_MultiSignature, cosmos_crypto_multisig_v1beta1_MultiSignature, AUTO)


PB_BIND(cosmos_crypto_multisig_v1beta1_CompactBitArray, cosmos_crypto_multisig_v1beta1_CompactBitArray, AUTO)



